In [1]:
import pandas as pd

In [2]:
climate_df = pd.read_csv("../data/raw/climate_change_dataset.csv")

In [3]:
# First 5 rows
climate_df.head()

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,37,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77

In [4]:
climate_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   year                        1200 non-null   int64
 1   country                     1200 non-null   str
 2   global_avg_temperature      1200 non-null   float64
 3   temperature_anomaly         1200 non-null   float64
 4   max_temperature             1200 non-null   float64
 5   min_temperature             1200 non-null   float64
 6   co2_concentration_ppm       1200 non-null   float64
 7   annual_rainfall_mm          1200 non-null   float64
 8   sea_level_rise_mm           1200 non-null   float64
 9   sea_surface_temperature     1200 non-null   float64
 10  heatwave_days               1200 non-null   int64
 11  drought_index               1200 non-null   float64
 12  flood_events_count          1200 non-null   int64
 13  forest_cover_percent        1200 non-null   float64
 14  deforestation_rate          1200 non-null   float64
 15  fossil_fuel_consumption     1200 non-null   float64
 16  renewable_energy_share      1200 non-null   float64
 17  air_quality_index           1200 non-null   int64
 18  predicted_temperature_2050  1200 non-null   float64
 19  climate_risk_index          1200 non-null   float64
dtypes: float64(15), int64(4), str(1)
memory usage: 187.6 KB

# Selecting A Single Column

In [5]:
# Selecting one column - Countries column
climate_df["country"]

0         Germany
1           India
2        Pakistan
3             USA
4       Australia
          ...
1195        India
1196       Canada
1197           UK
1198           UK
1199      Germany
Name: country, Length: 1200, dtype: str

In [6]:
type(climate_df["country"])

pandas.Series

In [7]:
# Selecting More than one column
climate_df[["year", "country","annual_rainfall_mm"]]

      year    country  annual_rainfall_mm
0     2018    Germany              814.11
1     2008      India              735.61
2     1994   Pakistan             1982.92
3     2022        USA             1162.01
4     1987  Australia             1170.25
...    ...        ...                 ...
1195  1980      India             1483.91
1196  1993     Canada              777.83
1197  1981         UK              251.69
1198  2007         UK             1343.91
1199  2009    Germany              914.09

[1200 rows x 3 columns]

In [8]:
type(climate_df[["country"]])

pandas.DataFrame

# Lesson 2: Selecting Rows with iLoc

In [9]:
climate_df.iloc[0]

year                             2018
country                       Germany
global_avg_temperature          14.03
temperature_anomaly              1.16
max_temperature                 37.02
min_temperature                  4.31
co2_concentration_ppm          387.85
annual_rainfall_mm             814.11
sea_level_rise_mm                2.14
sea_surface_temperature         14.38
heatwave_days                      50
drought_index                    0.85
flood_events_count                 11
forest_cover_percent            64.33
deforestation_rate               1.26
fossil_fuel_consumption         28.14
renewable_energy_share           42.3
air_quality_index                 148
predicted_temperature_2050        3.3
climate_risk_index              23.69
Name: 0, dtype: object

In [10]:
type(climate_df.iloc[0])

pandas.Series

In [11]:
climate_df.iloc[0:1]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.3,148,3.3,23.69

In [12]:
numbers = [10, 20, 30, 40]

print(numbers[0])
print(type(numbers[0]))

print(numbers[0:1])
print(type(numbers[0:1]))

10
<class 'int'>
[10]
<class 'list'>

In [13]:
climate_df.iloc[2:5]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77

# Lesson 3: Selecting Rows with loc

In [14]:
climate_df.loc[0]

year                             2018
country                       Germany
global_avg_temperature          14.03
temperature_anomaly              1.16
max_temperature                 37.02
min_temperature                  4.31
co2_concentration_ppm          387.85
annual_rainfall_mm             814.11
sea_level_rise_mm                2.14
sea_surface_temperature         14.38
heatwave_days                      50
drought_index                    0.85
flood_events_count                 11
forest_cover_percent            64.33
deforestation_rate               1.26
fossil_fuel_consumption         28.14
renewable_energy_share           42.3
air_quality_index                 148
predicted_temperature_2050        3.3
climate_risk_index              23.69
Name: 0, dtype: object

# Lesson 4: Filtering Rows

In [15]:
# Countries where the temperature is greater than 20.

#Step 1: Build the condition
climate_df["global_avg_temperature"] > 20

0       False
1       False
2       False
3       False
4       False
        ...
1195    False
1196    False
1197    False
1198    False
1199    False
Name: global_avg_temperature, Length: 1200, dtype: bool

In [16]:
# Step 2: Use the boolean series to filter
climate_df[climate_df["global_avg_temperature"] > 16]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
189,1994,Australia,16.10,1.42,43.52,10.76,417.07,1168.58,4.88,15.80,35,2.51,4,30.47,3.30,41.54,17.32,88,2.62,87.53
361,1981,Australia,16.11,1.30,39.91,3.69,420.52,573.56,4.10,16.49,42,1.36,11,40.58,2.61,45.79,45.29,103,1.60,57.08
399,1994,Germany,16.14,1.28,26.79,5.79,456.13,753.30,7.75,14.25,18,4.01,8,68.69,3.15,63.71,58.55,160,1.96,63.54
444,2005,Germany,16.11,1.24,25.56,13.00,424.43,1176.85,2.68,16.09,44,2.23,12,67.77,0.57,35.03,45.03,70,2.36,93.10
548,1996,Australia,16.13,1.31,32.50,9.22,402.82,786.50,3.20,17.84,29,1.42,3,43.26,2.92,22.86,47.17,118,1.61,41.10
833,2005,France,16.08,0.88,28.13,12.46,346.85,1603.08,4.08,16.99,46,2.13,13,24.75,3.45,61.60,6.40,180,2.28,51.96

In [17]:
type(climate_df["global_avg_temperature"] > 16)

pandas.Series

In [18]:
type(climate_df[climate_df["global_avg_temperature"] > 16])

pandas.DataFrame

In [19]:
climate_df["country"] == "Germany"

0        True
1       False
2       False
3       False
4       False
        ...
1195    False
1196    False
1197    False
1198    False
1199     True
Name: country, Length: 1200, dtype: bool

In [20]:
climate_df[climate_df["country"] == "Germany"].describe().T

,count,mean,std,min,25%,50%,75%,max
year,114.0,2002.754386,13.472070,1980.00,1991.0000,2005.000,2014.7500,2025.00
global_avg_temperature,114.0,14.545000,0.525762,13.39,14.1750,14.555,14.8750,16.14
temperature_anomaly,114.0,1.197281,0.347737,0.43,0.9500,1.165,1.4375,2.17
max_temperature,114.0,35.111491,5.099588,20.48,31.7000,34.885,38.4025,47.56
min_temperature,114.0,5.024912,4.415771,-4.85,1.7300,4.930,8.2375,17.96
co2_concentration_ppm,114.0,414.623421,24.827153,359.24,400.3850,411.320,432.7950,478.51
annual_rainfall_mm,114.0,984.862632,272.732239,161.47,833.5750,960.375,1176.8275,1721.84
sea_level_rise_mm,114.0,3.490175,1.195571,0.24,2.7525,3.285,4.1350,7.75
sea_surface_temperature,114.0,16.332895,1.458381,12.78,15.3050,16.330,17.3625,19.52
heatwave_days,114.0,28.877193,19.240049,0.00,11.2500,29.000,45.7500,59.00
drought_index,114.0,2.408772,1.438129,0.07,1.0150,2.195,3.5875,4.99
flood_events_count,114.0,7.368421,4.464735,0.00,3.0000,8.000,11.0000,14.00
forest_cover_percent,114.0,41.383596,17.686284,10.28,27.6600,40.865,57.5300,69.81
deforestation_rate,114.0,1.655000,1.042971,0.10,0.7350,1.490,2.6500,3.48
fossil_fuel_consumption,114.0,56.987719,20.522609,20.07,41.5225,58.785,75.1975,89.67
renewable_energy_share,114.0,28.057456,16.157331,5.05,14.2350,24.365,42.5775,59.94
air_quality_index,114.0,123.894737,52.208969,40.00,76.5000,124.000,169.7500,199.00
predicted_temperature_2050,114.0,2.214474,0.501742,0.78,1.8125,2.195,2.5775,3.52
climate_risk_index,114.0,46.760526,29.568648,0.61,19.0400,44.535,72.1325,98.96

In [21]:
climate_df[climate_df["country"] == "Germany"].shape

(114, 20)

# Lesson 5: Filtering Rows With Multiple Conditions

In [22]:
climate_df.columns

Index(['year', 'country', 'global_avg_temperature', 'temperature_anomaly',
       'max_temperature', 'min_temperature', 'co2_concentration_ppm',
       'annual_rainfall_mm', 'sea_level_rise_mm', 'sea_surface_temperature',
       'heatwave_days', 'drought_index', 'flood_events_count',
       'forest_cover_percent', 'deforestation_rate', 'fossil_fuel_consumption',
       'renewable_energy_share', 'air_quality_index',
       'predicted_temperature_2050', 'climate_risk_index'],
      dtype='str')

In [23]:
climate_df["global_avg_temperature"] > 20

0       False
1       False
2       False
3       False
4       False
        ...
1195    False
1196    False
1197    False
1198    False
1199    False
Name: global_avg_temperature, Length: 1200, dtype: bool

In [24]:
climate_df["co2_concentration_ppm"] > 400

0       False
1        True
2        True
3        True
4        True
        ...
1195     True
1196     True
1197     True
1198     True
1199     True
Name: co2_concentration_ppm, Length: 1200, dtype: bool

In [25]:
# Combining conditions using & (All conditions must be true)
climate_df[(climate_df["global_avg_temperature"] > 16) & (climate_df["co2_concentration_ppm"] > 400)]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
189,1994,Australia,16.10,1.42,43.52,10.76,417.07,1168.58,4.88,15.80,35,2.51,4,30.47,3.30,41.54,17.32,88,2.62,87.53
361,1981,Australia,16.11,1.30,39.91,3.69,420.52,573.56,4.10,16.49,42,1.36,11,40.58,2.61,45.79,45.29,103,1.60,57.08
399,1994,Germany,16.14,1.28,26.79,5.79,456.13,753.30,7.75,14.25,18,4.01,8,68.69,3.15,63.71,58.55,160,1.96,63.54
444,2005,Germany,16.11,1.24,25.56,13.00,424.43,1176.85,2.68,16.09,44,2.23,12,67.77,0.57,35.03,45.03,70,2.36,93.10
548,1996,Australia,16.13,1.31,32.50,9.22,402.82,786.50,3.20,17.84,29,1.42,3,43.26,2.92,22.86,47.17,118,1.61,41.10

In [26]:
# Using | for OR
climate_df[(climate_df["country"] == "USA") | (climate_df["country"] == "Germany")]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
12,2015,USA,15.37,0.70,27.99,2.78,396.88,1201.52,2.02,18.83,41,3.90,11,44.90,2.73,27.40,8.42,79,2.56,45.24
18,2003,USA,14.83,1.44,33.61,7.67,440.49,1189.91,1.98,15.89,57,2.80,7,26.47,1.58,71.99,12.34,157,2.44,71.99
25,1991,Germany,14.59,0.93,42.02,-1.70,429.06,470.02,4.35,16.88,4,0.79,12,63.05,0.64,58.88,57.31,92,2.93,30.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1167,2005,USA,15.06,1.23,31.56,9.21,383.24,945.77,2.86,14.60,15,1.23,10,58.64,0.75,81.71,35.17,165,2.10,53.31
1172,1999,USA,14.38,1.02,24.64,9.49,383.04,858.09,2.97,15.55,15,2.42,4,62.24,2.18,34.25,54.85,146,1.99,92.69
1179,1980,USA,13.62,0.51,36.45,-2.57,453.07,782.18,4.59,16.28,44,1.49,8,63.11,0.82,43.30,48.41,172,2.00,49.09
1184,1998,USA,15.27,0.90,44.29,-0.90,464.54,1254.08,2.49,16.88,19,2.78,2,20.96,1.01,45.86,5.71,140,1.99,72.15
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,9,0.91,12,66.56,0.48,62.18,7.55,102,1.64,88.74

In [27]:
# Using ~ for NOT
climate_df[~(climate_df["country"] == "USA")]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,37,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77
5,2000,France,14.20,1.68,27.62,10.17,342.89,1178.57,2.31,16.28,22,4.38,9,43.17,0.77,50.15,59.28,172,1.17,68.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,44,1.96,3,19.13,2.38,21.56,22.78,112,1.91,25.39
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,54,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,5,3.99,13,19.46,2.76,64.51,12.09,103,1.40,83.67
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,41,0.47,4,33.91,1.78,54.68,46.40,91,2.92,6.43
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,9,0.91,12,66.56,0.48,62.18,7.55,102,1.64,88.74

# Lesson 6: Sorting Data

In [28]:
sorted_climate_df = climate_df.sort_values(by="global_avg_temperature", ascending= False)
sorted_climate_df.head()

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
399,1994,Germany,16.14,1.28,26.79,5.79,456.13,753.30,7.75,14.25,18,4.01,8,68.69,3.15,63.71,58.55,160,1.96,63.54
548,1996,Australia,16.13,1.31,32.50,9.22,402.82,786.50,3.20,17.84,29,1.42,3,43.26,2.92,22.86,47.17,118,1.61,41.10
444,2005,Germany,16.11,1.24,25.56,13.00,424.43,1176.85,2.68,16.09,44,2.23,12,67.77,0.57,35.03,45.03,70,2.36,93.10
361,1981,Australia,16.11,1.30,39.91,3.69,420.52,573.56,4.10,16.49,42,1.36,11,40.58,2.61,45.79,45.29,103,1.60,57.08
189,1994,Australia,16.10,1.42,43.52,10.76,417.07,1168.58,4.88,15.80,35,2.51,4,30.47,3.30,41.54,17.32,88,2.62,87.53

In [29]:
print(id(climate_df))
print(id(sorted_climate_df))

2142534969264
2142536592624

In [30]:
# Top 10 Hottest global average temp
sorted_climate_df.head(10)

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
399,1994,Germany,16.14,1.28,26.79,5.79,456.13,753.30,7.75,14.25,18,4.01,8,68.69,3.15,63.71,58.55,160,1.96,63.54
548,1996,Australia,16.13,1.31,32.50,9.22,402.82,786.50,3.20,17.84,29,1.42,3,43.26,2.92,22.86,47.17,118,1.61,41.10
444,2005,Germany,16.11,1.24,25.56,13.00,424.43,1176.85,2.68,16.09,44,2.23,12,67.77,0.57,35.03,45.03,70,2.36,93.10
361,1981,Australia,16.11,1.30,39.91,3.69,420.52,573.56,4.10,16.49,42,1.36,11,40.58,2.61,45.79,45.29,103,1.60,57.08
189,1994,Australia,16.10,1.42,43.52,10.76,417.07,1168.58,4.88,15.80,35,2.51,4,30.47,3.30,41.54,17.32,88,2.62,87.53
833,2005,France,16.08,0.88,28.13,12.46,346.85,1603.08,4.08,16.99,46,2.13,13,24.75,3.45,61.60,6.40,180,2.28,51.96
179,2018,India,15.95,1.09,39.10,5.91,401.88,292.69,3.14,14.80,32,3.42,9,15.06,0.50,47.63,46.89,118,2.63,50.70
558,1991,India,15.90,0.95,32.97,13.07,416.99,1055.04,5.25,15.56,9,2.32,1,11.44,0.70,63.21,12.63,46,1.87,64.86
519,1983,China,15.90,0.99,46.39,-0.56,416.59,646.40,3.16,14.73,49,1.05,5,29.96,1.46,74.09,48.91,80,2.18,30.51
52,1987,China,15.88,0.61,33.77,6.72,465.88,1120.25,1.86,16.44,36,4.79,14,34.17,1.36,56.21,25.27,107,1.77,66.93

In [31]:
# Sorting a single column
climate_df.sort_values("country")

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
469,2013,Australia,13.77,1.07,38.42,-0.16,419.36,1390.30,4.50,16.68,12,3.26,0,41.63,2.03,37.25,33.64,190,1.68,38.66
397,2021,Australia,14.15,0.58,35.12,4.00,432.18,602.92,3.32,17.63,46,2.90,9,45.16,2.52,48.99,10.77,192,2.81,38.64
395,2001,Australia,14.50,1.07,35.73,-0.91,395.25,1036.77,3.55,13.98,1,0.55,10,20.20,1.77,68.52,43.25,108,2.04,52.22
216,1990,Australia,14.28,0.58,36.40,3.38,399.28,995.70,5.31,15.98,53,1.41,0,31.39,0.34,75.21,27.89,127,3.20,40.90
516,2013,Australia,14.40,0.85,35.85,2.52,388.40,1207.08,3.45,17.41,4,1.41,9,49.42,2.07,57.10,10.15,126,3.26,16.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,2012,USA,14.52,0.77,34.46,1.58,414.24,922.10,4.69,17.65,42,4.80,5,37.66,2.86,22.07,57.93,106,0.89,19.24
693,1992,USA,14.41,1.24,32.05,3.49,367.30,739.42,2.74,17.09,50,2.56,3,11.56,2.44,30.89,55.19,83,0.96,64.31
740,2025,USA,14.70,0.73,43.14,0.02,454.73,793.41,3.15,16.26,40,2.18,14,54.41,1.20,60.08,54.73,145,2.31,21.62
888,1983,USA,13.55,1.58,34.54,13.37,444.41,1234.81,3.25,18.80,24,2.14,7,39.71,2.60,56.74,33.67,191,2.60,94.90
661,1980,USA,15.14,0.76,31.73,7.90,415.14,1119.78,1.63,15.52,29,2.73,5,20.35,0.49,29.60,59.47,139,1.79,46.70

In [32]:
# Sorting multiple columns
temp_sorted_climate_df = climate_df.sort_values(["max_temperature", "min_temperature"], ascending= [False,True])

temp_sorted_climate_df.head(10)

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
1188,2024,Australia,14.66,1.42,50.07,5.35,424.36,877.68,2.57,16.20,43,2.00,13,62.69,1.85,24.91,23.49,102,1.82,88.58
826,2001,Pakistan,13.58,0.48,48.84,7.69,451.48,1391.22,3.35,15.47,17,1.79,6,21.42,3.43,71.21,55.27,160,2.22,49.21
831,2020,Canada,15.69,1.02,48.19,0.58,423.14,1460.96,3.10,13.65,54,1.52,6,54.96,2.97,49.56,50.63,186,1.60,45.57
369,2008,Australia,13.83,1.93,48.19,2.13,402.42,726.55,3.35,17.51,55,4.52,12,43.65,3.16,78.44,51.52,129,1.85,16.18
1054,2017,UK,13.53,1.24,47.97,1.37,444.76,537.47,3.70,16.41,56,3.43,11,42.46,3.18,88.98,17.47,127,2.20,50.76
406,1984,Germany,14.56,1.09,47.56,5.02,359.24,843.17,3.16,15.29,44,0.39,4,11.91,3.00,50.69,33.67,68,1.90,63.96
163,2007,Brazil,14.49,0.64,47.51,2.30,425.78,719.87,4.14,18.69,42,1.48,4,57.51,2.27,39.09,34.28,70,2.29,28.23
150,1994,Canada,14.74,0.84,47.42,8.19,369.80,1062.51,5.73,15.34,2,4.53,5,46.98,0.91,22.76,39.78,45,2.81,34.76
49,2007,India,13.60,1.30,47.07,-2.21,418.52,1282.72,4.27,15.23,46,4.94,13,65.05,1.12,53.92,52.42,143,1.59,3.42
190,2011,UK,14.32,1.59,46.95,1.44,452.06,563.86,2.64,17.22,39,3.23,11,21.73,2.05,40.01,41.72,128,1.87,48.80

In [33]:
climate_df.head(10)["country"]

0      Germany
1        India
2     Pakistan
3          USA
4    Australia
5       France
6       France
7        India
8       Canada
9       Canada
Name: country, dtype: str

In [34]:
climate_df["country"].head(10)

0      Germany
1        India
2     Pakistan
3          USA
4    Australia
5       France
6       France
7        India
8       Canada
9       Canada
Name: country, dtype: str

In [35]:
climate_df.head(10)[["country"]]

     country
0    Germany
1      India
2   Pakistan
3        USA
4  Australia
5     France
6     France
7      India
8     Canada
9     Canada

Using only one line of code, create a new DataFrame that:

sorts the data by annual rainfall,
from highest to lowest,
and displays the top 10 rows.

Don't modify climate_df itself.

In [36]:
sorted_annual_rainfall_df = climate_df.sort_values("annual_rainfall_mm", ascending= False)

sorted_annual_rainfall_df.head(10)

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
839,2006,Canada,14.26,0.96,37.78,6.66,404.23,2019.44,2.67,15.39,18,1.82,7,51.24,2.50,78.77,33.46,51,2.44,63.98
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
459,2000,China,14.79,1.57,35.23,2.67,412.65,1895.90,3.37,17.42,6,1.12,3,23.41,2.40,28.32,21.22,138,3.26,39.14
457,2005,Canada,15.36,1.60,24.38,11.35,371.77,1814.09,2.34,16.64,58,2.21,6,45.04,2.62,60.72,13.21,183,1.99,16.76
752,2018,Brazil,14.34,0.38,32.47,1.39,431.95,1804.15,5.52,15.32,12,2.00,4,23.09,2.49,22.78,56.24,66,2.47,3.97
976,1999,Australia,14.00,1.36,25.54,1.68,414.45,1796.12,2.63,15.29,15,3.32,10,46.98,1.38,27.22,48.84,119,2.86,30.40
725,1984,USA,13.94,0.63,34.43,0.87,435.16,1789.18,2.81,14.51,24,2.61,1,33.87,1.25,71.04,11.42,194,1.76,21.78
846,2005,France,14.28,1.51,31.54,1.84,399.71,1781.25,3.53,16.05,57,1.78,2,20.86,0.93,45.08,49.75,99,1.82,81.50
1001,2008,USA,15.52,1.75,39.34,5.91,404.34,1762.40,0.02,17.69,23,0.72,3,44.93,2.72,47.69,29.83,140,1.47,73.23
935,1994,UK,14.99,0.74,31.70,3.38,405.55,1760.00,2.36,18.05,36,4.02,10,39.20,1.84,75.84,40.13,61,1.86,44.88

Create a new DataFrame that:

- Sorts by country in alphabetical order (A–Z).
- If a country has multiple rows, sort those rows by year, from oldest to newest.
- Display the first 15 rows.

In [37]:
sorted_countries = climate_df.sort_values(["country", "year"], ascending=[True,True])
sorted_countries.head(15)

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
495,1980,Australia,14.64,0.90,29.77,6.16,408.61,372.44,3.74,15.55,58,1.58,7,43.72,0.54,59.71,52.69,79,2.31,71.61
720,1980,Australia,15.09,0.95,26.39,2.49,433.33,1083.79,3.96,14.68,10,4.15,5,43.71,3.17,62.21,30.59,43,2.76,76.76
955,1980,Australia,14.40,0.78,38.69,4.13,409.03,1239.98,2.64,14.88,16,1.37,4,48.55,1.94,28.23,19.45,41,1.91,53.13
17,1981,Australia,14.72,0.83,40.91,6.98,414.47,488.33,3.27,18.75,41,1.54,11,29.24,2.80,60.22,54.92,112,2.82,40.87
22,1981,Australia,13.46,1.19,40.92,-1.38,459.18,731.00,3.02,14.73,37,3.38,7,43.19,3.00,72.88,34.06,138,1.96,44.40
196,1981,Australia,13.74,-0.23,31.42,6.06,398.70,1126.40,3.93,16.64,36,1.59,10,22.37,2.19,73.98,33.62,56,2.94,53.37
361,1981,Australia,16.11,1.30,39.91,3.69,420.52,573.56,4.10,16.49,42,1.36,11,40.58,2.61,45.79,45.29,103,1.60,57.08
975,1981,Australia,13.50,1.18,32.40,0.85,464.72,1037.79,4.67,15.23,33,0.83,3,54.82,2.61,69.98,39.53,134,1.35,58.72
35,1982,Australia,14.01,0.86,32.11,8.61,394.00,1234.71,3.14,15.72,57,2.86,12,33.70,2.24,83.88,53.26,115,2.21,39.03
346,1982,Australia,14.76,1.41,30.24,9.55,340.27,1204.31,1.65,17.47,58,4.95,8,27.42,2.05,70.33,50.80,57,2.00,63.86
636,1982,Australia,14.12,1.57,42.79,-2.72,374.30,1053.07,2.71,16.56,18,3.16,2,64.38,2.49,51.24,45.14,193,2.22,29.93
864,1982,Australia,14.06,0.04,29.13,8.14,367.27,1093.30,2.90,17.26,22,4.27,13,53.96,3.12,23.93,13.45,101,2.65,87.26
144,1983,Australia,12.78,1.03,36.67,7.53,454.34,1417.10,3.70,18.96,47,3.38,12,25.20,3.09,86.62,5.19,148,2.16,71.19
475,1984,Australia,15.23,0.91,29.40,7.39,387.21,1396.39,4.95,16.59,54,0.57,14,61.68,2.81,75.92,58.89,64,2.33,57.81
936,1985,Australia,14.11,1.13,36.25,9.96,407.55,842.01,4.97,17.35,59,0.56,1,50.45,0.20,44.49,53.19,196,1.79,12.13

Create a new DataFrame that:

- Sorts by global average temperature from highest to lowest.
- If two rows have the same global average temperature, sort those rows by annual rainfall, from lowest to highest.
- Display the top 20 rows.

This challenge is testing whether you understand that each sort column can have its own sort direction.

In [38]:
sorted_temp_rainfall = climate_df.sort_values(["global_avg_temperature","annual_rainfall_mm"], ascending=[False,True])
sorted_temp_rainfall.head(20)

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
399,1994,Germany,16.14,1.28,26.79,5.79,456.13,753.30,7.75,14.25,18,4.01,8,68.69,3.15,63.71,58.55,160,1.96,63.54
548,1996,Australia,16.13,1.31,32.50,9.22,402.82,786.50,3.20,17.84,29,1.42,3,43.26,2.92,22.86,47.17,118,1.61,41.10
361,1981,Australia,16.11,1.30,39.91,3.69,420.52,573.56,4.10,16.49,42,1.36,11,40.58,2.61,45.79,45.29,103,1.60,57.08
444,2005,Germany,16.11,1.24,25.56,13.00,424.43,1176.85,2.68,16.09,44,2.23,12,67.77,0.57,35.03,45.03,70,2.36,93.10
189,1994,Australia,16.10,1.42,43.52,10.76,417.07,1168.58,4.88,15.80,35,2.51,4,30.47,3.30,41.54,17.32,88,2.62,87.53
833,2005,France,16.08,0.88,28.13,12.46,346.85,1603.08,4.08,16.99,46,2.13,13,24.75,3.45,61.60,6.40,180,2.28,51.96
179,2018,India,15.95,1.09,39.10,5.91,401.88,292.69,3.14,14.80,32,3.42,9,15.06,0.50,47.63,46.89,118,2.63,50.70
519,1983,China,15.90,0.99,46.39,-0.56,416.59,646.40,3.16,14.73,49,1.05,5,29.96,1.46,74.09,48.91,80,2.18,30.51
558,1991,India,15.90,0.95,32.97,13.07,416.99,1055.04,5.25,15.56,9,2.32,1,11.44,0.70,63.21,12.63,46,1.87,64.86
52,1987,China,15.88,0.61,33.77,6.72,465.88,1120.25,1.86,16.44,36,4.79,14,34.17,1.36,56.21,25.27,107,1.77,66.93
382,2025,France,15.87,0.35,31.62,7.75,425.04,752.94,4.06,15.00,33,3.31,14,49.26,1.29,76.46,11.07,142,2.10,9.81
1133,2015,UK,15.83,0.86,35.94,4.42,390.56,736.83,3.43,16.74,31,1.22,11,12.95,0.15,62.45,18.33,88,2.18,48.78
92,1988,Canada,15.83,1.38,29.32,7.51,418.15,1006.75,4.52,19.12,23,3.81,5,69.25,2.09,76.20,47.33,147,1.82,42.26
766,2000,Brazil,15.81,1.17,38.63,3.44,432.27,512.86,4.43,17.64,47,4.40,7,45.20,3.26,34.56,17.26,88,2.15,81.74
618,1998,India,15.81,1.19,37.98,7.45,410.64,789.65,1.90,17.13,17,2.70,0,69.66,0.86,68.44,39.69,186,2.57,10.38
1050,2018,Brazil,15.78,1.02,32.33,11.15,414.73,523.29,2.94,16.40,50,0.17,10,10.78,3.02,75.93,49.62,77,2.40,31.92
1187,2008,UK,15.77,1.11,33.32,-0.48,418.64,526.29,4.68,16.40,55,1.26,7,11.06,3.06,86.35,14.11,108,2.10,45.38
679,1987,China,15.76,0.94,29.78,2.05,453.91,732.76,4.09,13.00,46,4.94,5,10.08,2.02,82.14,35.01,148,1.96,55.53
368,2018,India,15.76,1.27,26.46,9.29,405.87,1246.28,4.72,16.34,10,3.41,1,58.43,2.54,36.17,18.09,114,2.34,22.53
1148,2017,Brazil,15.72,0.67,42.64,-0.93,430.48,1000.44,3.18,15.50,42,4.50,2,18.77,0.93,89.63,37.71,141,2.05,99.27

Create a new DataFrame that:

- Sorts by country from Z → A.
- Within each country, sort by global average temperature from highest to lowest.
- If there is still a tie, sort by year from oldest to newest.
- Display the first 25 rows.

In [39]:
sorted_country_weather = climate_df.sort_values(
    ["country", "global_avg_temperature", "year"],
    ascending= [False, False,True]
)

sorted_country_weather.head(25)

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
266,2020,USA,15.58,1.11,32.96,6.44,450.18,1065.89,2.36,16.72,50,4.54,10,22.30,0.22,75.47,42.02,120,2.68,35.65
1001,2008,USA,15.52,1.75,39.34,5.91,404.34,1762.40,0.02,17.69,23,0.72,3,44.93,2.72,47.69,29.83,140,1.47,73.23
1016,2004,USA,15.51,0.50,30.95,4.83,380.56,879.92,3.15,16.90,34,2.95,0,51.98,1.61,63.83,48.92,142,2.79,21.47
417,2021,USA,15.42,0.74,25.45,1.92,386.62,889.79,3.16,15.19,7,2.37,9,63.38,2.28,29.00,59.77,173,3.77,42.93
467,1984,USA,15.39,0.39,31.71,3.83,422.73,591.34,2.61,18.73,59,4.83,12,16.49,1.57,30.12,38.38,180,2.34,41.07
12,2015,USA,15.37,0.70,27.99,2.78,396.88,1201.52,2.02,18.83,41,3.90,11,44.90,2.73,27.40,8.42,79,2.56,45.24
838,2024,USA,15.35,0.15,46.08,-2.48,417.69,1214.90,3.31,16.07,56,4.43,4,22.86,1.96,56.87,47.38,106,2.30,62.72
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
277,2015,USA,15.28,0.74,38.80,-3.32,391.96,1070.27,2.48,16.24,11,4.79,12,52.22,2.33,46.92,24.79,98,2.24,50.87
1184,1998,USA,15.27,0.90,44.29,-0.90,464.54,1254.08,2.49,16.88,19,2.78,2,20.96,1.01,45.86,5.71,140,1.99,72.15
481,1981,USA,15.26,0.64,31.60,0.17,390.84,1172.53,4.13,16.61,57,0.18,3,29.86,1.85,86.51,13.66,100,2.86,65.45
674,2007,USA,15.24,0.77,32.46,4.40,395.38,1105.90,4.57,16.38,18,1.69,11,32.38,1.86,23.54,37.30,141,2.86,29.79
370,2021,USA,15.23,0.40,39.47,4.55,441.19,1102.76,4.90,15.24,16,1.16,8,66.17,0.54,49.34,41.60,140,1.92,40.00
122,2006,USA,15.19,0.44,26.77,8.00,408.00,513.18,2.72,15.96,32,2.62,12,48.89,3.18,55.58,15.21,75,1.45,65.69
523,2015,USA,15.18,0.88,28.28,2.42,397.46,743.90,5.62,14.29,50,3.59,8,46.65,0.60,39.36,55.30,175,2.31,66.77
104,1984,USA,15.17,0.58,29.93,5.23,394.56,1119.42,1.81,17.21,29,1.12,7,38.27,2.38,25.18,34.23,78,1.98,61.91
661,1980,USA,15.14,0.76,31.73,7.90,415.14,1119.78,1.63,15.52,29,2.73,5,20.35,0.49,29.60,59.47,139,1.79,46.70
1127,1980,USA,15.13,1.42,39.47,0.04,387.08,779.77,6.82,14.89,56,4.68,7,46.41,2.51,41.17,8.25,55,1.91,8.18
226,2012,USA,15.12,0.96,39.37,6.59,404.01,806.97,2.99,15.90,26,0.37,14,51.80,2.89,70.78,53.76,188,2.86,46.76
1149,1981,USA,15.08,0.78,36.83,3.50,417.24,797.90,3.93,15.39,27,3.63,10,24.24,2.13,76.22,33.32,59,1.47,2.28
514,1989,USA,15.08,1.00,39.30,2.33,440.85,1272.94,3.79,19.14,9,2.80,4,62.22,1.27,87.19,38.39,150,1.58,41.64
1167,2005,USA,15.06,1.23,31.56,9.21,383.24,945.77,2.86,14.60,15,1.23,10,58.64,0.75,81.71,35.17,165,2.10,53.31
521,1990,USA,15.04,1.36,34.59,7.17,375.99,1459.65,5.15,14.98,52,0.78,13,46.13,2.41,74.93,9.40,126,2.50,55.12
414,2019,USA,15.00,1.05,33.02,7.35,452.87,1280.64,3.30,15.30,59,4.41,4,21.82,2.90,23.89,58.63,74,2.48,64.87
46,2005,USA,14.99,0.92,40.02,11.03,423.60,1169.86,3.14,15.44,48,3.91,4,16.85,3.47,52.34,18.40,150,2.01,74.68

Find the 10 coldest records in the dataset.

Requirements:

- Sort by global average temperature (lowest first).
- If two rows have the same global average temperature, show the one with the highest annual rainfall first.
- Display only these columns:
- _country_
- _year_
- _global_avg_temperature_
- _annual_rainfall_mm_

In [40]:
sorted_coldest_records = climate_df.sort_values(
    ["global_avg_temperature","annual_rainfall_mm"],
    ascending= [True,False]
)

sorted_coldest_records[["country","year","global_avg_temperature","annual_rainfall_mm"]].head(10)

        country  year  global_avg_temperature  annual_rainfall_mm
841   Australia  2005                   12.42             1007.27
144   Australia  1983                   12.78             1417.10
668    Pakistan  2011                   12.80             1426.19
108      Canada  2007                   12.84              738.81
1144     Canada  2014                   12.89              790.16
701      Brazil  1989                   12.92             1318.83
863      Canada  1986                   12.96              761.37
547   Australia  2009                   13.05              855.20
703      Brazil  2024                   13.05              555.47
377      France  2015                   13.06              473.39

# Lesson 7: Creating New Columns

In [41]:
climate_df.head(20)

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,37,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77
5,2000,France,14.20,1.68,27.62,10.17,342.89,1178.57,2.31,16.28,22,4.38,9,43.17,0.77,50.15,59.28,172,1.17,68.62
6,2018,France,14.67,1.41,33.10,3.75,426.67,1422.19,1.48,15.78,45,1.05,5,44.54,3.46,65.85,21.51,71,2.67,23.87
7,1998,India,13.94,1.22,33.35,9.91,434.75,1122.34,4.60,14.54,48,3.13,10,22.86,0.93,31.12,11.51,110,2.10,83.59
8,2002,Canada,14.89,1.85,36.39,4.31,372.50,1244.87,4.16,17.39,29,0.41,13,38.26,2.95,71.61,45.23,113,2.86,72.18
9,1990,Canada,15.23,1.54,39.31,3.69,413.33,682.43,2.94,17.35,2,4.40,5,37.57,1.70,68.29,58.82,177,2.16,23.41
10,1990,India,14.15,1.06,28.75,5.23,419.83,1295.18,5.55,15.57,27,0.26,13,47.37,1.58,58.02,11.42,138,2.37,97.50
11,2003,China,14.52,0.61,29.46,6.14,439.12,928.97,1.38,14.85,32,2.77,13,25.58,1.10,59.61,28.74,60,2.38,66.48
12,2015,USA,15.37,0.70,27.99,2.78,396.88,1201.52,2.02,18.83,41,3.90,11,44.90,2.73,27.40,8.42,79,2.56,45.24
13,2019,France,15.58,1.47,41.60,5.09,393.12,485.46,2.85,16.87,2,0.58,13,24.46,3.09,50.52,47.71,81,2.42,15.75
14,2003,France,14.95,0.85,36.49,8.15,403.59,1189.05,3.07,17.10,4,2.02,10,36.79,0.99,26.06,57.18,111,1.75,53.32
15,1982,China,14.86,0.70,29.58,5.52,447.11,327.43,5.26,17.16,56,0.21,5,17.36,0.42,41.55,32.44,85,2.07,16.48
16,2001,France,13.99,0.80,32.78,5.17,441.10,917.23,3.56,14.70,18,3.41,9,12.24,0.57,83.02,27.52,121,2.20,42.95
17,1981,Australia,14.72,0.83,40.91,6.98,414.47,488.33,3.27,18.75,41,1.54,11,29.24,2.80,60.22,54.92,112,2.82,40.87
18,2003,USA,14.83,1.44,33.61,7.67,440.49,1189.91,1.98,15.89,57,2.80,7,26.47,1.58,71.99,12.34,157,2.44,71.99
19,2023,Brazil,14.37,1.04,33.31,4.75,355.78,1020.78,4.80,17.73,56,4.66,9,34.42,0.55,60.17,54.04,80,1.87,19.24

In [42]:
# Creating a new column

climate_df["doubled_temp"] = climate_df["global_avg_temperature"] * 2
climate_df

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,doubled_temp
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,...,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69,28.06
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,...,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10,30.06
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,...,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74,29.72
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,...,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59,30.58
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,...,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77,27.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,...,1.96,3,19.13,2.38,21.56,22.78,112,1.91,25.39,29.06
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,...,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97,30.28
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,...,3.99,13,19.46,2.76,64.51,12.09,103,1.40,83.67,30.84
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,...,0.47,4,33.91,1.78,54.68,46.40,91,2.92,6.43,28.14
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,...,0.91,12,66.56,0.48,62.18,7.55,102,1.64,88.74,29.64

In [43]:
# Rounding of global_avg_temperature to one decimal place into a new column
climate_df["rounded_global_avg_temp"] = climate_df["global_avg_temperature"].round(1)
climate_df

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,doubled_temp,rounded_global_avg_temp
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,...,11,64.33,1.26,28.14,42.30,148,3.30,23.69,28.06,14.0
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,...,11,42.69,0.62,86.40,53.65,50,2.63,70.10,30.06,15.0
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,...,1,65.47,2.08,34.95,47.20,107,1.33,34.74,29.72,14.9
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,...,6,44.34,2.15,77.11,36.65,129,2.51,45.59,30.58,15.3
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,...,4,14.18,0.76,37.27,50.35,149,2.87,55.77,27.50,13.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,...,3,19.13,2.38,21.56,22.78,112,1.91,25.39,29.06,14.5
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,...,4,40.94,1.77,74.75,20.81,96,2.71,4.97,30.28,15.1
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,...,13,19.46,2.76,64.51,12.09,103,1.40,83.67,30.84,15.4
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,...,4,33.91,1.78,54.68,46.40,91,2.92,6.43,28.14,14.1
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,...,12,66.56,0.48,62.18,7.55,102,1.64,88.74,29.64,14.8

In [44]:
# Creating a  new column for temperatures under 2 as cold

climate_df["is_cold"] = climate_df["max_temperature"] < 22
climate_df[climate_df["is_cold"] == True]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,doubled_temp,rounded_global_avg_temp,is_cold
69,2015,India,13.66,1.36,20.50,5.01,431.02,429.85,3.34,17.85,...,23.28,0.89,38.96,8.15,44,1.82,32.20,27.32,13.7,True
319,2012,India,13.13,1.29,21.90,2.21,402.70,848.40,1.63,14.82,...,67.01,3.43,73.27,47.28,174,2.36,76.91,26.26,13.1,True
325,2014,India,13.93,1.43,21.43,1.10,454.16,1397.26,3.14,18.23,...,64.47,2.22,72.80,52.56,134,2.66,61.38,27.86,13.9,True
428,1991,Germany,15.41,0.91,20.48,-0.83,415.86,1193.93,4.00,12.99,...,54.58,0.91,71.54,44.05,140,2.61,73.69,30.82,15.4,True
853,1993,Germany,15.07,1.43,21.89,4.28,436.60,834.79,3.81,18.37,...,47.77,3.35,45.80,26.84,186,1.49,93.74,30.14,15.1,True
924,2019,India,15.59,1.00,19.50,16.57,368.25,1528.50,4.20,19.59,...,14.22,1.34,57.23,12.07,51,2.13,13.96,31.18,15.6,True
960,1990,Brazil,13.79,0.48,18.62,1.92,357.65,1032.40,2.67,11.32,...,52.69,2.16,73.77,43.74,117,2.05,11.39,27.58,13.8,True
1169,2000,Australia,14.53,0.91,20.85,4.59,432.01,1541.53,2.89,16.23,...,62.62,1.76,40.69,24.40,149,1.44,35.72,29.06,14.5,True

In [45]:
climate_df["max_temperature"].min()

np.float64(18.62)

# Lesson 8: Group by and Pivot Tables

In [46]:
# Single column grouping (returns a series)
climate_df.groupby("country")["annual_rainfall_mm"].mean()

country
Australia    1027.148718
Brazil        946.186752
Canada       1014.297931
China         997.718986
France        990.668525
Germany       984.862632
India        1000.260085
Pakistan      996.769298
UK            954.305118
USA          1021.074407
Name: annual_rainfall_mm, dtype: float64

In [47]:
# Multiple columns grouping (returns a dataframe)
climate_df.groupby("country")[["global_avg_temperature", "annual_rainfall_mm"]].mean()

           global_avg_temperature  annual_rainfall_mm
country
Australia               14.423590         1027.148718
Brazil                  14.501368          946.186752
Canada                  14.476897         1014.297931
China                   14.542681          997.718986
France                  14.508525          990.668525
Germany                 14.545000          984.862632
India                   14.469487         1000.260085
Pakistan                14.446053          996.769298
UK                      14.548189          954.305118
USA                     14.452712         1021.074407

For every country, I want:

- Average temperature
- Maximum temperature
- Minimum temperature"

In [48]:
country_data = climate_df.groupby("country")["global_avg_temperature"].agg(["mean", "max", "min"])

country_data.head()

                mean    max    min
country
Australia  14.423590  16.13  12.42
Brazil     14.501368  15.81  12.92
Canada     14.476897  15.83  12.84
China      14.542681  15.90  13.14
France     14.508525  16.08  13.06

In [49]:
country_data.loc["Brazil"]

mean    14.501368
max     15.810000
min     12.920000
Name: Brazil, dtype: float64

In [50]:
country_data.loc["Brazil","mean"]

np.float64(14.501367521367522)

### Challenges

### GroupBy Challenge 1

Using `groupby()`:

- Calculate the average (`mean`) **global average temperature** for each country.
- Store the result in a variable called `country_avg_temp`.
- Sort the results from **highest average temperature to lowest**.
- Display the top **5** countries.

Requirements:
- Do not use `pivot_table()`.
- Do not use `.agg()` for this challenge.
- Use only `groupby()`, `mean()`, `sort_values()`, and `head()`.

In [51]:
country_avg_temp = climate_df.groupby("country")["global_avg_temperature"].mean()
country_avg_temp.sort_values(ascending=False).head(5)

country
UK         14.548189
Germany    14.545000
China      14.542681
France     14.508525
Brazil     14.501368
Name: global_avg_temperature, dtype: float64

### GroupBy Challenge 2

Using `groupby()`:

- Calculate the **maximum annual rainfall** for each country.
- Store the result in a variable called `country_max_rainfall`.
- Display the countries from **highest rainfall to lowest rainfall**.
- Show **all** countries.

Requirements:
- Do not use `.agg()`.
- Do not use `pivot_table()`.
- Use only `groupby()`, `max()`, and `sort_values()`.

In [52]:
country_max_rainfall = climate_df.groupby("country")["annual_rainfall_mm"].max()
country_max_rainfall.sort_values(ascending=False)

country
Canada       2019.44
Pakistan     1982.92
China        1895.90
Brazil       1804.15
Australia    1796.12
USA          1789.18
France       1781.25
UK           1760.00
Germany      1721.84
India        1693.38
Name: annual_rainfall_mm, dtype: float64

### GroupBy Challenge 3 (Final)

Without using `.agg()`:

Create a summary that shows, for each country:

- The **minimum** global average temperature.
- Sort the results from the **coldest country** to the **warmest country** (based on that minimum temperature).
- Display only the **top 3** countries.

Requirements:
- Use only `groupby()`, `min()`, `sort_values()`, and `head()`.

In [53]:
cold_to_warm_countries = climate_df.groupby("country")["global_avg_temperature"].min()
cold_to_warm_countries.sort_values().head(3)

country
Australia    12.42
Pakistan     12.80
Canada       12.84
Name: global_avg_temperature, dtype: float64

## Pivot Tables

Create a pivot table that shows:

- Rows = Country
- Columns = Year
- Values = Global Average Temperature
- Aggregation = Mean

In [54]:
climate_df.pivot_table(
    index = "country",
    values= "global_avg_temperature",
    columns= "year",
    aggfunc= "mean"
).head()

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.7100,14.306000,14.2375,12.780,15.230000,14.155000,14.105,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360,14.900000,14.74,14.360000,14.5275,14.410000,13.28
Brazil,14.8350,14.202500,14.3300,13.760,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730,15.130000,NaN,14.200000,14.7300,14.273333,14.00
Canada,14.8200,14.595000,14.0200,14.495,15.190000,14.500000,14.360,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295,15.690000,14.14,13.606667,14.0700,14.610000,14.02
China,14.7325,14.883333,14.0375,15.100,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938,14.240000,14.32,14.530000,14.3640,14.202000,NaN
France,14.5800,14.506667,14.6400,14.050,14.325714,14.320000,14.365,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680,14.216667,14.60,13.810000,15.5800,15.320000,15.35

In [55]:
climate_df.pivot_table(
    index = "year",
    values= "max_temperature",
    columns= "country",
    aggfunc= ("max")
)

country,Australia,Brazil,Canada,China,France,Germany,India,Pakistan,UK,USA
year,,,,,,,,,,
1980,38.69,30.78,35.36,39.86,36.49,44.70,43.91,40.83,40.82,39.47
1981,40.92,39.06,38.66,41.73,35.61,44.22,42.55,NaN,35.28,36.83
1982,42.79,31.95,33.81,42.54,41.85,NaN,33.46,35.62,39.32,41.97
1983,36.67,38.20,44.16,46.39,28.22,32.53,45.93,38.72,36.96,34.54
1984,29.40,NaN,30.49,34.00,40.17,47.56,33.13,33.83,40.41,41.04
1985,36.25,45.14,33.94,43.74,35.17,36.92,43.10,41.79,40.92,37.08
1986,36.15,NaN,42.82,NaN,45.22,37.65,32.65,28.08,39.00,36.62
1987,40.99,46.40,41.07,34.37,32.78,42.78,38.02,30.58,40.47,36.60
1988,44.19,31.92,32.27,NaN,33.32,44.17,46.03,28.92,39.41,35.16
1989,42.25,41.00,39.36,37.92,42.78,43.11,34.67,41.03,32.12,39.30
1990,36.40,18.62,39.31,33.15,32.84,31.25,31.83,40.79,35.04,38.19
1991,35.53,35.02,36.81,40.78,30.52,42.02,38.75,35.11,42.33,NaN
1992,35.69,29.14,41.04,NaN,41.66,39.69,42.29,35.91,37.17,41.22
1993,NaN,40.16,38.31,30.71,37.95,40.61,34.07,38.49,35.73,41.63
1994,43.52,32.15,47.42,36.48,37.00,42.57,40.74,41.57,31.70,37.60
1995,NaN,43.10,29.35,46.02,37.56,NaN,36.69,34.94,38.54,40.97
1996,36.78,35.14,43.65,40.08,36.47,45.54,32.58,45.75,41.54,45.58
1997,40.09,38.35,NaN,42.13,34.77,35.56,41.57,31.28,34.28,28.11
1998,34.79,31.88,42.55,41.83,36.00,33.11,37.98,34.60,43.42,44.29
1999,35.96,35.45,34.60,37.19,35.13,28.80,36.33,35.84,42.73,36.18
2000,37.03,38.63,31.62,35.23,43.37,36.66,41.22,NaN,39.90,31.60
2001,36.36,37.15,38.97,35.62,42.94,37.79,NaN,48.84,NaN,40.17
2002,43.59,40.42,40.33,36.16,37.09,38.29,33.57,45.73,40.73,34.20
2003,35.97,36.47,38.39,39.98,38.25,NaN,34.47,NaN,37.30,41.87
2004,38.11,NaN,NaN,37.94,36.98,30.44,42.05,41.11,39.28,39.23
2005,37.82,38.92,38.66,37.48,38.15,38.94,45.56,41.00,38.02,40.02
2006,30.17,40.29,39.88,39.60,34.09,33.02,43.42,40.00,36.57,34.85
2007,39.01,47.51,40.89,40.37,31.37,39.79,47.07,43.25,39.96,37.92
2008,48.19,35.09,38.13,NaN,34.38,36.11,44.24,37.73,39.70,39.34
2009,42.65,36.84,35.68,44.86,40.64,37.61,39.63,35.42,34.51,41.43
2010,32.67,33.03,34.24,41.03,36.85,44.99,38.82,37.78,NaN,38.26
2011,NaN,37.33,40.29,44.74,44.29,41.09,33.29,44.66,46.95,36.89
2012,42.34,42.59,44.94,41.80,34.69,34.75,44.66,46.69,42.66,44.67
2013,38.42,33.58,43.49,35.37,45.74,40.18,35.05,NaN,41.82,35.99
2014,40.48,33.47,42.53,37.98,34.19,35.30,42.36,28.16,36.50,32.12
2015,39.49,NaN,40.72,36.42,37.81,39.44,36.73,36.91,36.83,38.80
2016,37.25,44.98,39.33,42.88,39.52,35.48,40.03,35.54,37.59,44.75
2017,40.92,42.64,40.01,31.74,36.88,32.70,29.88,40.39,47.97,NaN
2018,43.88,38.74,37.23,37.94,33.10,37.02,41.65,35.62,29.69,NaN
2019,43.01,44.37,36.11,43.16,41.60,32.01,35.93,40.62,37.07,33.02
2020,31.17,40.47,48.19,39.78,35.99,38.94,NaN,34.06,29.96,42.62
2021,35.12,NaN,35.89,40.58,29.31,36.76,33.63,41.33,39.24,39.47
2022,39.68,34.83,40.65,35.16,33.73,30.42,40.46,41.26,46.37,32.17
2023,42.27,40.23,28.82,38.31,41.43,40.12,NaN,32.85,43.11,36.78
2024,50.07,37.08,39.07,44.34,31.87,37.83,33.78,39.84,42.54,46.08
2025,38.85,33.75,36.41,NaN,34.08,26.06,39.85,30.94,40.52,43.14

In [56]:
climate_df.columns

Index(['year', 'country', 'global_avg_temperature', 'temperature_anomaly',
       'max_temperature', 'min_temperature', 'co2_concentration_ppm',
       'annual_rainfall_mm', 'sea_level_rise_mm', 'sea_surface_temperature',
       'heatwave_days', 'drought_index', 'flood_events_count',
       'forest_cover_percent', 'deforestation_rate', 'fossil_fuel_consumption',
       'renewable_energy_share', 'air_quality_index',
       'predicted_temperature_2050', 'climate_risk_index', 'doubled_temp',
       'rounded_global_avg_temp', 'is_cold'],
      dtype='str')

### Pivot Table Challenge 1

Create a pivot table that shows:

- Rows as `country`
- Columns as `year`
- Values as `annual_rainfall_mm`
- Display the **average annual rainfall** for each country in each year.

Requirements:
- Use `pivot_table()`.
- Do not use `groupby()`.
- Store the result in a variable called `country_year_rainfall`.

In [57]:
country_year_rainfall = climate_df.pivot_table(
    index = "country",
    columns= "year",
    values = "annual_rainfall_mm",
    aggfunc= "mean"
)

country_year_rainfall

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,898.736667,791.416000,1146.347500,1417.100,1396.390000,1038.165000,1316.870,1004.824000,864.157500,1116.530000,...,994.030000,1022.200000,1194.517500,1177.090000,896.600000,606.075000,1505.915,881.535,964.550000,1227.710000
Brazil,1191.460000,814.047500,1273.305000,1171.890,NaN,1148.580000,NaN,853.700000,1013.440000,1023.235000,...,1039.217500,941.802000,890.438333,1096.982500,530.070000,NaN,1123.750,891.000,663.886667,1289.185000
Canada,613.603333,1091.285000,596.160000,1424.050,843.140000,1012.530000,988.285,1128.360000,1042.323333,525.590000,...,1104.605000,1110.606667,961.520000,924.760000,1460.960000,1015.600000,985.580,807.810,567.086667,509.300000
China,899.170000,951.723333,888.030000,1067.610,1449.053333,1088.233333,NaN,899.253333,NaN,895.240000,...,962.731429,1308.110000,1093.326667,947.048000,849.410000,957.920000,1089.990,969.592,1007.426000,NaN
France,962.890000,1014.456667,862.225000,1650.170,1053.224286,1075.016000,959.190,1038.330000,1242.790000,989.553333,...,1266.290000,730.172500,1422.190000,818.756667,1042.236667,1009.465000,793.560,1715.040,605.570000,828.965000
Germany,1148.970000,1205.923333,NaN,1279.580,915.662500,1065.840000,1091.210,953.303333,855.390000,878.340000,...,1585.290000,863.070000,897.580000,1239.090000,804.835000,1085.016667,833.170,898.720,1045.017500,910.090000
India,1202.857500,1029.442500,857.790000,801.960,1078.130000,1011.517500,1036.785,1350.675000,1089.265000,992.013333,...,712.986667,1430.320000,991.678000,1196.980000,NaN,988.080000,590.940,NaN,456.520000,606.175000
Pakistan,937.775000,NaN,1056.226667,1151.790,888.067500,1088.950000,703.380,1167.250000,1153.520000,1027.570000,...,1029.465000,1154.965000,1168.405000,1021.293333,889.690000,979.200000,1105.430,1350.510,1203.670000,1345.160000
UK,1060.505000,251.690000,759.246000,1043.845,1090.303333,928.956667,622.005,1267.280000,1036.625000,838.180000,...,1127.490000,884.086667,1060.340000,775.726667,1254.760000,1260.955000,1070.810,854.865,948.287500,1105.346667
USA,1092.763750,846.003333,1176.403333,1234.810,1196.546000,1202.730000,595.120,1007.570000,1208.040000,1273.610000,...,892.546667,NaN,NaN,1361.680000,918.060000,902.095000,1162.010,903.285,1144.572500,912.965000

### Data Analysis Question

A climate researcher wants to compare how **global average temperatures** have changed over the years for every country.

Create a table that allows the researcher to quickly compare each country's average global temperature across all available years.

In [58]:
yearly_temp_change = climate_df.pivot_table(
    index = "country",
    columns = "year",
    values = "global_avg_temperature",
    aggfunc= "mean"
)

yearly_temp_change

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

### Data Analysis Question

A climate policy team wants to identify years that experienced the highest temperatures in each country.

Create a table that makes it easy to see the **highest recorded maximum temperature** for every country in every year.

In [59]:
yearly_max_temp = climate_df.pivot_table(
    index = "country",
    columns = "year",
    values = "max_temperature",
    aggfunc= "max"
)

yearly_max_temp

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,38.69,40.92,42.79,36.67,29.40,36.25,36.15,40.99,44.19,42.25,...,37.25,40.92,43.88,43.01,31.17,35.12,39.68,42.27,50.07,38.85
Brazil,30.78,39.06,31.95,38.20,NaN,45.14,NaN,46.40,31.92,41.00,...,44.98,42.64,38.74,44.37,40.47,NaN,34.83,40.23,37.08,33.75
Canada,35.36,38.66,33.81,44.16,30.49,33.94,42.82,41.07,32.27,39.36,...,39.33,40.01,37.23,36.11,48.19,35.89,40.65,28.82,39.07,36.41
China,39.86,41.73,42.54,46.39,34.00,43.74,NaN,34.37,NaN,37.92,...,42.88,31.74,37.94,43.16,39.78,40.58,35.16,38.31,44.34,NaN
France,36.49,35.61,41.85,28.22,40.17,35.17,45.22,32.78,33.32,42.78,...,39.52,36.88,33.10,41.60,35.99,29.31,33.73,41.43,31.87,34.08
Germany,44.70,44.22,NaN,32.53,47.56,36.92,37.65,42.78,44.17,43.11,...,35.48,32.70,37.02,32.01,38.94,36.76,30.42,40.12,37.83,26.06
India,43.91,42.55,33.46,45.93,33.13,43.10,32.65,38.02,46.03,34.67,...,40.03,29.88,41.65,35.93,NaN,33.63,40.46,NaN,33.78,39.85
Pakistan,40.83,NaN,35.62,38.72,33.83,41.79,28.08,30.58,28.92,41.03,...,35.54,40.39,35.62,40.62,34.06,41.33,41.26,32.85,39.84,30.94
UK,40.82,35.28,39.32,36.96,40.41,40.92,39.00,40.47,39.41,32.12,...,37.59,47.97,29.69,37.07,29.96,39.24,46.37,43.11,42.54,40.52
USA,39.47,36.83,41.97,34.54,41.04,37.08,36.62,36.60,35.16,39.30,...,44.75,NaN,NaN,33.02,42.62,39.47,32.17,36.78,46.08,43.14

In [63]:
climate_df["country"].unique()

<StringArray>
[  'Germany',     'India',  'Pakistan',       'USA', 'Australia',    'France',
    'Canada',     'China',    'Brazil',        'UK']
Length: 10, dtype: str