In [27]:
import pandas as pd

In [28]:
climate_df = pd.read_csv("../data/raw/climate_change_dataset.csv")

In [29]:
# First 5 rows
climate_df.head()

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,37,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77

# Selecting A Single Column

In [30]:
# Selecting one column - Countries column
climate_df["country"]

0         Germany
1           India
2        Pakistan
3             USA
4       Australia
          ...
1195        India
1196       Canada
1197           UK
1198           UK
1199      Germany
Name: country, Length: 1200, dtype: str

In [31]:
type(climate_df["country"])

pandas.Series

In [32]:
# Selecting More than one column
climate_df[["year", "country","annual_rainfall_mm"]]

      year    country  annual_rainfall_mm
0     2018    Germany              814.11
1     2008      India              735.61
2     1994   Pakistan             1982.92
3     2022        USA             1162.01
4     1987  Australia             1170.25
...    ...        ...                 ...
1195  1980      India             1483.91
1196  1993     Canada              777.83
1197  1981         UK              251.69
1198  2007         UK             1343.91
1199  2009    Germany              914.09

[1200 rows x 3 columns]

In [33]:
type(climate_df[["country"]])

pandas.DataFrame

# Lesson 2: Selecting Rows with iLoc

In [34]:
climate_df.iloc[0]

year                             2018
country                       Germany
global_avg_temperature          14.03
temperature_anomaly              1.16
max_temperature                 37.02
min_temperature                  4.31
co2_concentration_ppm          387.85
annual_rainfall_mm             814.11
sea_level_rise_mm                2.14
sea_surface_temperature         14.38
heatwave_days                      50
drought_index                    0.85
flood_events_count                 11
forest_cover_percent            64.33
deforestation_rate               1.26
fossil_fuel_consumption         28.14
renewable_energy_share           42.3
air_quality_index                 148
predicted_temperature_2050        3.3
climate_risk_index              23.69
Name: 0, dtype: object

In [35]:
type(climate_df.iloc[0])

pandas.Series

In [36]:
climate_df.iloc[0:1]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.3,148,3.3,23.69

In [37]:
numbers = [10, 20, 30, 40]

print(numbers[0])
print(type(numbers[0]))

print(numbers[0:1])
print(type(numbers[0:1]))

10
<class 'int'>
[10]
<class 'list'>

In [38]:
climate_df.iloc[2:5]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77

# Lesson 3: Selecting Rows with loc

In [39]:
climate_df.loc[0]

year                             2018
country                       Germany
global_avg_temperature          14.03
temperature_anomaly              1.16
max_temperature                 37.02
min_temperature                  4.31
co2_concentration_ppm          387.85
annual_rainfall_mm             814.11
sea_level_rise_mm                2.14
sea_surface_temperature         14.38
heatwave_days                      50
drought_index                    0.85
flood_events_count                 11
forest_cover_percent            64.33
deforestation_rate               1.26
fossil_fuel_consumption         28.14
renewable_energy_share           42.3
air_quality_index                 148
predicted_temperature_2050        3.3
climate_risk_index              23.69
Name: 0, dtype: object

# Lesson 4: Filtering Rows

In [40]:
# Countries where the temperature is greater than 20.

#Step 1: Build the condition
climate_df["global_avg_temperature"] > 20

0       False
1       False
2       False
3       False
4       False
        ...
1195    False
1196    False
1197    False
1198    False
1199    False
Name: global_avg_temperature, Length: 1200, dtype: bool

In [41]:
# Step 2: Use the boolean series to filter
climate_df[climate_df["global_avg_temperature"] > 16]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
189,1994,Australia,16.10,1.42,43.52,10.76,417.07,1168.58,4.88,15.80,35,2.51,4,30.47,3.30,41.54,17.32,88,2.62,87.53
361,1981,Australia,16.11,1.30,39.91,3.69,420.52,573.56,4.10,16.49,42,1.36,11,40.58,2.61,45.79,45.29,103,1.60,57.08
399,1994,Germany,16.14,1.28,26.79,5.79,456.13,753.30,7.75,14.25,18,4.01,8,68.69,3.15,63.71,58.55,160,1.96,63.54
444,2005,Germany,16.11,1.24,25.56,13.00,424.43,1176.85,2.68,16.09,44,2.23,12,67.77,0.57,35.03,45.03,70,2.36,93.10
548,1996,Australia,16.13,1.31,32.50,9.22,402.82,786.50,3.20,17.84,29,1.42,3,43.26,2.92,22.86,47.17,118,1.61,41.10
833,2005,France,16.08,0.88,28.13,12.46,346.85,1603.08,4.08,16.99,46,2.13,13,24.75,3.45,61.60,6.40,180,2.28,51.96

In [42]:
type(climate_df[climate_df["global_avg_temperature"] > 16])

pandas.DataFrame

In [43]:
climate_df["country"] == "Germany"

0        True
1       False
2       False
3       False
4       False
        ...
1195    False
1196    False
1197    False
1198    False
1199     True
Name: country, Length: 1200, dtype: bool

In [44]:
climate_df[climate_df["country"] == "Germany"].describe().T

,count,mean,std,min,25%,50%,75%,max
year,114.0,2002.754386,13.472070,1980.00,1991.0000,2005.000,2014.7500,2025.00
global_avg_temperature,114.0,14.545000,0.525762,13.39,14.1750,14.555,14.8750,16.14
temperature_anomaly,114.0,1.197281,0.347737,0.43,0.9500,1.165,1.4375,2.17
max_temperature,114.0,35.111491,5.099588,20.48,31.7000,34.885,38.4025,47.56
min_temperature,114.0,5.024912,4.415771,-4.85,1.7300,4.930,8.2375,17.96
co2_concentration_ppm,114.0,414.623421,24.827153,359.24,400.3850,411.320,432.7950,478.51
annual_rainfall_mm,114.0,984.862632,272.732239,161.47,833.5750,960.375,1176.8275,1721.84
sea_level_rise_mm,114.0,3.490175,1.195571,0.24,2.7525,3.285,4.1350,7.75
sea_surface_temperature,114.0,16.332895,1.458381,12.78,15.3050,16.330,17.3625,19.52
heatwave_days,114.0,28.877193,19.240049,0.00,11.2500,29.000,45.7500,59.00
drought_index,114.0,2.408772,1.438129,0.07,1.0150,2.195,3.5875,4.99
flood_events_count,114.0,7.368421,4.464735,0.00,3.0000,8.000,11.0000,14.00
forest_cover_percent,114.0,41.383596,17.686284,10.28,27.6600,40.865,57.5300,69.81
deforestation_rate,114.0,1.655000,1.042971,0.10,0.7350,1.490,2.6500,3.48
fossil_fuel_consumption,114.0,56.987719,20.522609,20.07,41.5225,58.785,75.1975,89.67
renewable_energy_share,114.0,28.057456,16.157331,5.05,14.2350,24.365,42.5775,59.94
air_quality_index,114.0,123.894737,52.208969,40.00,76.5000,124.000,169.7500,199.00
predicted_temperature_2050,114.0,2.214474,0.501742,0.78,1.8125,2.195,2.5775,3.52
climate_risk_index,114.0,46.760526,29.568648,0.61,19.0400,44.535,72.1325,98.96

In [45]:
climate_df[climate_df["country"] == "Germany"].shape

(114, 20)

# Lesson 5: Filtering Rows With Multiple Conditions

In [46]:
climate_df.columns

Index(['year', 'country', 'global_avg_temperature', 'temperature_anomaly',
       'max_temperature', 'min_temperature', 'co2_concentration_ppm',
       'annual_rainfall_mm', 'sea_level_rise_mm', 'sea_surface_temperature',
       'heatwave_days', 'drought_index', 'flood_events_count',
       'forest_cover_percent', 'deforestation_rate', 'fossil_fuel_consumption',
       'renewable_energy_share', 'air_quality_index',
       'predicted_temperature_2050', 'climate_risk_index'],
      dtype='str')

In [47]:
climate_df["global_avg_temperature"] > 20

0       False
1       False
2       False
3       False
4       False
        ...
1195    False
1196    False
1197    False
1198    False
1199    False
Name: global_avg_temperature, Length: 1200, dtype: bool

In [48]:
climate_df["co2_concentration_ppm"] > 400

0       False
1        True
2        True
3        True
4        True
        ...
1195     True
1196     True
1197     True
1198     True
1199     True
Name: co2_concentration_ppm, Length: 1200, dtype: bool

In [49]:
# Combining conditions using &
climate_df[(climate_df["global_avg_temperature"] > 16) & (climate_df["co2_concentration_ppm"] > 400)]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
189,1994,Australia,16.10,1.42,43.52,10.76,417.07,1168.58,4.88,15.80,35,2.51,4,30.47,3.30,41.54,17.32,88,2.62,87.53
361,1981,Australia,16.11,1.30,39.91,3.69,420.52,573.56,4.10,16.49,42,1.36,11,40.58,2.61,45.79,45.29,103,1.60,57.08
399,1994,Germany,16.14,1.28,26.79,5.79,456.13,753.30,7.75,14.25,18,4.01,8,68.69,3.15,63.71,58.55,160,1.96,63.54
444,2005,Germany,16.11,1.24,25.56,13.00,424.43,1176.85,2.68,16.09,44,2.23,12,67.77,0.57,35.03,45.03,70,2.36,93.10
548,1996,Australia,16.13,1.31,32.50,9.22,402.82,786.50,3.20,17.84,29,1.42,3,43.26,2.92,22.86,47.17,118,1.61,41.10

In [50]:
# Using | for OR
climate_df[(climate_df["country"] == "USA") | (climate_df["country"] == "Germany")]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
12,2015,USA,15.37,0.70,27.99,2.78,396.88,1201.52,2.02,18.83,41,3.90,11,44.90,2.73,27.40,8.42,79,2.56,45.24
18,2003,USA,14.83,1.44,33.61,7.67,440.49,1189.91,1.98,15.89,57,2.80,7,26.47,1.58,71.99,12.34,157,2.44,71.99
25,1991,Germany,14.59,0.93,42.02,-1.70,429.06,470.02,4.35,16.88,4,0.79,12,63.05,0.64,58.88,57.31,92,2.93,30.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1167,2005,USA,15.06,1.23,31.56,9.21,383.24,945.77,2.86,14.60,15,1.23,10,58.64,0.75,81.71,35.17,165,2.10,53.31
1172,1999,USA,14.38,1.02,24.64,9.49,383.04,858.09,2.97,15.55,15,2.42,4,62.24,2.18,34.25,54.85,146,1.99,92.69
1179,1980,USA,13.62,0.51,36.45,-2.57,453.07,782.18,4.59,16.28,44,1.49,8,63.11,0.82,43.30,48.41,172,2.00,49.09
1184,1998,USA,15.27,0.90,44.29,-0.90,464.54,1254.08,2.49,16.88,19,2.78,2,20.96,1.01,45.86,5.71,140,1.99,72.15
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,9,0.91,12,66.56,0.48,62.18,7.55,102,1.64,88.74

In [51]:
# Using ~ for NOT
climate_df[~(climate_df["country"] == "USA")]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,37,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77
5,2000,France,14.20,1.68,27.62,10.17,342.89,1178.57,2.31,16.28,22,4.38,9,43.17,0.77,50.15,59.28,172,1.17,68.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,44,1.96,3,19.13,2.38,21.56,22.78,112,1.91,25.39
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,54,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,5,3.99,13,19.46,2.76,64.51,12.09,103,1.40,83.67
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,41,0.47,4,33.91,1.78,54.68,46.40,91,2.92,6.43
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,9,0.91,12,66.56,0.48,62.18,7.55,102,1.64,88.74

# Lesson 6: Sorting Data

In [52]:
sorted_climate_df = climate_df.sort_values(by="global_avg_temperature", ascending= False)
sorted_climate_df.head()

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
399,1994,Germany,16.14,1.28,26.79,5.79,456.13,753.30,7.75,14.25,18,4.01,8,68.69,3.15,63.71,58.55,160,1.96,63.54
548,1996,Australia,16.13,1.31,32.50,9.22,402.82,786.50,3.20,17.84,29,1.42,3,43.26,2.92,22.86,47.17,118,1.61,41.10
444,2005,Germany,16.11,1.24,25.56,13.00,424.43,1176.85,2.68,16.09,44,2.23,12,67.77,0.57,35.03,45.03,70,2.36,93.10
361,1981,Australia,16.11,1.30,39.91,3.69,420.52,573.56,4.10,16.49,42,1.36,11,40.58,2.61,45.79,45.29,103,1.60,57.08
189,1994,Australia,16.10,1.42,43.52,10.76,417.07,1168.58,4.88,15.80,35,2.51,4,30.47,3.30,41.54,17.32,88,2.62,87.53

In [53]:
print(id(climate_df))
print(id(sorted_climate_df))

2117986374128
2117986673936

In [54]:
# Top 10 Hottest global average temp
sorted_climate_df.head(10)

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
399,1994,Germany,16.14,1.28,26.79,5.79,456.13,753.30,7.75,14.25,18,4.01,8,68.69,3.15,63.71,58.55,160,1.96,63.54
548,1996,Australia,16.13,1.31,32.50,9.22,402.82,786.50,3.20,17.84,29,1.42,3,43.26,2.92,22.86,47.17,118,1.61,41.10
444,2005,Germany,16.11,1.24,25.56,13.00,424.43,1176.85,2.68,16.09,44,2.23,12,67.77,0.57,35.03,45.03,70,2.36,93.10
361,1981,Australia,16.11,1.30,39.91,3.69,420.52,573.56,4.10,16.49,42,1.36,11,40.58,2.61,45.79,45.29,103,1.60,57.08
189,1994,Australia,16.10,1.42,43.52,10.76,417.07,1168.58,4.88,15.80,35,2.51,4,30.47,3.30,41.54,17.32,88,2.62,87.53
833,2005,France,16.08,0.88,28.13,12.46,346.85,1603.08,4.08,16.99,46,2.13,13,24.75,3.45,61.60,6.40,180,2.28,51.96
179,2018,India,15.95,1.09,39.10,5.91,401.88,292.69,3.14,14.80,32,3.42,9,15.06,0.50,47.63,46.89,118,2.63,50.70
558,1991,India,15.90,0.95,32.97,13.07,416.99,1055.04,5.25,15.56,9,2.32,1,11.44,0.70,63.21,12.63,46,1.87,64.86
519,1983,China,15.90,0.99,46.39,-0.56,416.59,646.40,3.16,14.73,49,1.05,5,29.96,1.46,74.09,48.91,80,2.18,30.51
52,1987,China,15.88,0.61,33.77,6.72,465.88,1120.25,1.86,16.44,36,4.79,14,34.17,1.36,56.21,25.27,107,1.77,66.93

In [55]:
climate_df.head(10)["country"]

0      Germany
1        India
2     Pakistan
3          USA
4    Australia
5       France
6       France
7        India
8       Canada
9       Canada
Name: country, dtype: str

In [56]:
climate_df["country"].head(10)

0      Germany
1        India
2     Pakistan
3          USA
4    Australia
5       France
6       France
7        India
8       Canada
9       Canada
Name: country, dtype: str

In [57]:
climate_df.head(10)[["country"]]

     country
0    Germany
1      India
2   Pakistan
3        USA
4  Australia
5     France
6     France
7      India
8     Canada
9     Canada

# Lesson 7: Creating New Columns

In [58]:
climate_df.head(20)

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,37,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77
5,2000,France,14.20,1.68,27.62,10.17,342.89,1178.57,2.31,16.28,22,4.38,9,43.17,0.77,50.15,59.28,172,1.17,68.62
6,2018,France,14.67,1.41,33.10,3.75,426.67,1422.19,1.48,15.78,45,1.05,5,44.54,3.46,65.85,21.51,71,2.67,23.87
7,1998,India,13.94,1.22,33.35,9.91,434.75,1122.34,4.60,14.54,48,3.13,10,22.86,0.93,31.12,11.51,110,2.10,83.59
8,2002,Canada,14.89,1.85,36.39,4.31,372.50,1244.87,4.16,17.39,29,0.41,13,38.26,2.95,71.61,45.23,113,2.86,72.18
9,1990,Canada,15.23,1.54,39.31,3.69,413.33,682.43,2.94,17.35,2,4.40,5,37.57,1.70,68.29,58.82,177,2.16,23.41
10,1990,India,14.15,1.06,28.75,5.23,419.83,1295.18,5.55,15.57,27,0.26,13,47.37,1.58,58.02,11.42,138,2.37,97.50
11,2003,China,14.52,0.61,29.46,6.14,439.12,928.97,1.38,14.85,32,2.77,13,25.58,1.10,59.61,28.74,60,2.38,66.48
12,2015,USA,15.37,0.70,27.99,2.78,396.88,1201.52,2.02,18.83,41,3.90,11,44.90,2.73,27.40,8.42,79,2.56,45.24
13,2019,France,15.58,1.47,41.60,5.09,393.12,485.46,2.85,16.87,2,0.58,13,24.46,3.09,50.52,47.71,81,2.42,15.75
14,2003,France,14.95,0.85,36.49,8.15,403.59,1189.05,3.07,17.10,4,2.02,10,36.79,0.99,26.06,57.18,111,1.75,53.32
15,1982,China,14.86,0.70,29.58,5.52,447.11,327.43,5.26,17.16,56,0.21,5,17.36,0.42,41.55,32.44,85,2.07,16.48
16,2001,France,13.99,0.80,32.78,5.17,441.10,917.23,3.56,14.70,18,3.41,9,12.24,0.57,83.02,27.52,121,2.20,42.95
17,1981,Australia,14.72,0.83,40.91,6.98,414.47,488.33,3.27,18.75,41,1.54,11,29.24,2.80,60.22,54.92,112,2.82,40.87
18,2003,USA,14.83,1.44,33.61,7.67,440.49,1189.91,1.98,15.89,57,2.80,7,26.47,1.58,71.99,12.34,157,2.44,71.99
19,2023,Brazil,14.37,1.04,33.31,4.75,355.78,1020.78,4.80,17.73,56,4.66,9,34.42,0.55,60.17,54.04,80,1.87,19.24

In [59]:
# Creating a new column

climate_df["doubled_temp"] = climate_df["global_avg_temperature"] * 2
climate_df

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,doubled_temp
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,...,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69,28.06
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,...,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10,30.06
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,...,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74,29.72
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,...,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59,30.58
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,...,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77,27.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,...,1.96,3,19.13,2.38,21.56,22.78,112,1.91,25.39,29.06
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,...,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97,30.28
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,...,3.99,13,19.46,2.76,64.51,12.09,103,1.40,83.67,30.84
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,...,0.47,4,33.91,1.78,54.68,46.40,91,2.92,6.43,28.14
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,...,0.91,12,66.56,0.48,62.18,7.55,102,1.64,88.74,29.64

In [60]:
# Rounding of global_avg_temperature to one decimal place into a new column
climate_df["rounded_global_avg_temp"] = climate_df["global_avg_temperature"].round(1)
climate_df

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,doubled_temp,rounded_global_avg_temp
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,...,11,64.33,1.26,28.14,42.30,148,3.30,23.69,28.06,14.0
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,...,11,42.69,0.62,86.40,53.65,50,2.63,70.10,30.06,15.0
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,...,1,65.47,2.08,34.95,47.20,107,1.33,34.74,29.72,14.9
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,...,6,44.34,2.15,77.11,36.65,129,2.51,45.59,30.58,15.3
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,...,4,14.18,0.76,37.27,50.35,149,2.87,55.77,27.50,13.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,...,3,19.13,2.38,21.56,22.78,112,1.91,25.39,29.06,14.5
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,...,4,40.94,1.77,74.75,20.81,96,2.71,4.97,30.28,15.1
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,...,13,19.46,2.76,64.51,12.09,103,1.40,83.67,30.84,15.4
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,...,4,33.91,1.78,54.68,46.40,91,2.92,6.43,28.14,14.1
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,...,12,66.56,0.48,62.18,7.55,102,1.64,88.74,29.64,14.8

In [61]:
# Creating a  new column for temperatures under 2 as cold

climate_df["is_cold"] = climate_df["max_temperature"] < 22
climate_df[climate_df["is_cold"] == True]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,doubled_temp,rounded_global_avg_temp,is_cold
69,2015,India,13.66,1.36,20.50,5.01,431.02,429.85,3.34,17.85,...,23.28,0.89,38.96,8.15,44,1.82,32.20,27.32,13.7,True
319,2012,India,13.13,1.29,21.90,2.21,402.70,848.40,1.63,14.82,...,67.01,3.43,73.27,47.28,174,2.36,76.91,26.26,13.1,True
325,2014,India,13.93,1.43,21.43,1.10,454.16,1397.26,3.14,18.23,...,64.47,2.22,72.80,52.56,134,2.66,61.38,27.86,13.9,True
428,1991,Germany,15.41,0.91,20.48,-0.83,415.86,1193.93,4.00,12.99,...,54.58,0.91,71.54,44.05,140,2.61,73.69,30.82,15.4,True
853,1993,Germany,15.07,1.43,21.89,4.28,436.60,834.79,3.81,18.37,...,47.77,3.35,45.80,26.84,186,1.49,93.74,30.14,15.1,True
924,2019,India,15.59,1.00,19.50,16.57,368.25,1528.50,4.20,19.59,...,14.22,1.34,57.23,12.07,51,2.13,13.96,31.18,15.6,True
960,1990,Brazil,13.79,0.48,18.62,1.92,357.65,1032.40,2.67,11.32,...,52.69,2.16,73.77,43.74,117,2.05,11.39,27.58,13.8,True
1169,2000,Australia,14.53,0.91,20.85,4.59,432.01,1541.53,2.89,16.23,...,62.62,1.76,40.69,24.40,149,1.44,35.72,29.06,14.5,True

In [62]:
climate_df["max_temperature"].min()

np.float64(18.62)