In [1]:
import pandas as pd

climate_df = pd.read_csv("../data/raw/climate_change_dataset.csv")

# Lesson 7: Data Cleaning
## Missing Values

In [2]:
# Detecting missing values
climate_df.isna()

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1196,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1197,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1198,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1199,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [3]:
climate_df.isna().sum()

year                          0
country                       0
global_avg_temperature        0
temperature_anomaly           0
max_temperature               0
min_temperature               0
co2_concentration_ppm         0
annual_rainfall_mm            0
sea_level_rise_mm             0
sea_surface_temperature       0
heatwave_days                 0
drought_index                 0
flood_events_count            0
forest_cover_percent          0
deforestation_rate            0
fossil_fuel_consumption       0
renewable_energy_share        0
air_quality_index             0
predicted_temperature_2050    0
climate_risk_index            0
dtype: int64

In [4]:
temp_avg_year_country = climate_df.pivot_table(
    index = "country",
    values= "global_avg_temperature",
    columns= "year",
    aggfunc= "mean"
)

temp_avg_year_country

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [5]:
# .sum(); Count the number of missing values in each column.
temp_avg_year_country.isna().sum()

year
1980    0
1981    1
1982    1
1983    0
1984    1
1985    0
1986    2
1987    0
1988    1
1989    0
1990    0
1991    1
1992    1
1993    1
1994    0
1995    2
1996    0
1997    1
1998    0
1999    0
2000    1
2001    2
2002    0
2003    2
2004    2
2005    0
2006    0
2007    0
2008    1
2009    0
2010    1
2011    1
2012    0
2013    1
2014    0
2015    1
2016    0
2017    1
2018    1
2019    0
2020    1
2021    1
2022    0
2023    1
2024    0
2025    1
dtype: int64

In [6]:
# .sum(axis =1 ); Count the number of missing values in each row.
temp_avg_year_country.isna().sum(axis=1)

country
Australia    3
Brazil       5
Canada       2
China        5
France       0
Germany      3
India        3
Pakistan     4
UK           2
USA          3
dtype: int64

In [7]:
# Does this row contain at least one missing value?
temp_avg_year_country.isna().any(axis=1)

country
Australia     True
Brazil        True
Canada        True
China         True
France       False
Germany       True
India         True
Pakistan      True
UK            True
USA           True
dtype: bool

In [8]:
climate_df[climate_df["country"] == "Brazil"].sort_values("year").head(20)

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
380,1980,Brazil,15.39,0.53,26.77,7.64,386.47,1321.91,3.28,17.19,18,0.33,2,26.39,1.53,44.06,17.84,190,2.88,33.22
745,1980,Brazil,14.28,0.65,30.78,4.78,443.76,1061.01,2.35,16.93,50,0.62,9,23.97,0.21,69.07,57.63,139,1.73,80.63
201,1981,Brazil,13.88,1.52,31.63,9.92,411.55,598.96,3.66,18.35,21,3.71,5,53.38,1.45,88.01,31.48,124,2.85,30.82
259,1981,Brazil,14.47,0.54,28.38,9.68,433.84,546.68,4.88,15.68,20,2.86,4,31.23,1.77,41.29,12.27,160,2.61,4.97
1080,1981,Brazil,13.21,0.69,31.53,4.46,436.82,1205.45,1.92,13.99,32,0.73,9,46.91,1.62,66.81,54.90,184,2.79,24.37
289,1981,Brazil,15.25,1.15,39.06,10.57,397.60,905.10,1.24,16.14,24,4.36,5,15.69,2.62,65.24,17.61,89,2.33,8.80
302,1982,Brazil,14.19,1.23,29.58,8.90,410.07,1304.28,4.09,14.37,29,3.36,5,30.53,1.31,56.86,11.22,99,3.05,25.88
197,1982,Brazil,14.47,0.51,31.95,4.38,405.90,1242.33,3.69,15.49,44,0.76,5,38.52,2.54,50.26,59.35,196,1.91,28.90
812,1983,Brazil,13.69,1.61,38.20,11.23,407.91,1329.84,3.21,15.59,20,1.94,13,45.09,1.58,52.01,23.27,197,1.70,4.49
1077,1983,Brazil,13.83,1.42,32.89,2.37,413.34,1013.94,1.83,15.71,29,3.52,6,60.59,1.24,72.50,33.53,170,2.85,51.88
162,1985,Brazil,14.18,1.65,33.75,-2.72,415.73,1375.09,4.00,15.59,59,4.45,11,33.67,2.06,56.08,23.13,154,2.45,40.96
929,1985,Brazil,15.33,0.51,45.14,12.17,446.18,922.07,2.19,15.82,39,2.13,1,69.16,1.20,86.01,47.75,67,2.23,66.22
313,1987,Brazil,15.00,0.60,31.82,5.37,416.70,1040.14,4.12,17.01,19,0.73,11,40.44,1.10,82.82,30.52,71,2.87,31.22
276,1987,Brazil,14.40,1.20,33.97,7.44,371.39,600.76,3.66,16.69,54,4.76,6,31.83,0.38,82.66,57.14,124,3.32,31.12
403,1987,Brazil,14.38,1.03,46.40,-1.30,430.02,1289.25,3.79,14.09,58,1.83,13,14.80,2.65,85.46,53.40,167,1.53,86.28
300,1987,Brazil,14.26,0.63,32.06,-1.00,437.39,660.58,-0.27,17.54,37,2.51,5,42.21,1.24,74.21,15.86,78,2.37,7.87
1074,1987,Brazil,14.08,1.13,32.88,5.90,435.84,766.55,4.86,16.87,0,1.74,14,68.14,0.40,38.80,53.71,52,2.44,28.13
897,1987,Brazil,15.10,1.54,29.11,12.09,428.37,764.92,1.77,16.43,17,0.93,3,36.95,2.09,72.29,49.65,141,2.47,51.10
559,1988,Brazil,14.62,1.57,31.92,5.92,455.01,1013.44,1.67,16.20,23,4.85,12,65.47,1.70,55.21,15.16,123,2.59,61.18
876,1989,Brazil,14.22,0.74,37.17,7.85,439.60,817.60,3.94,16.32,20,2.99,8,26.06,2.99,51.73,8.64,158,1.94,17.79

In [13]:
temp_avg_year_country

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [15]:
temp_avg_year_country.isna().sum()

year
1980    0
1981    1
1982    1
1983    0
1984    1
1985    0
1986    2
1987    0
1988    1
1989    0
1990    0
1991    1
1992    1
1993    1
1994    0
1995    2
1996    0
1997    1
1998    0
1999    0
2000    1
2001    2
2002    0
2003    2
2004    2
2005    0
2006    0
2007    0
2008    1
2009    0
2010    1
2011    1
2012    0
2013    1
2014    0
2015    1
2016    0
2017    1
2018    1
2019    0
2020    1
2021    1
2022    0
2023    1
2024    0
2025    1
dtype: int64

In [16]:
temp_avg_year_country.isna().sum(axis=1)

country
Australia    3
Brazil       5
Canada       2
China        5
France       0
Germany      3
India        3
Pakistan     4
UK           2
USA          3
dtype: int64

In [17]:
# Check if a dataset has any missing values(Not how many) per column

temp_avg_year_country.isna().any()

year
1980    False
1981     True
1982     True
1983    False
1984     True
1985    False
1986     True
1987    False
1988     True
1989    False
1990    False
1991     True
1992     True
1993     True
1994    False
1995     True
1996    False
1997     True
1998    False
1999    False
2000     True
2001     True
2002    False
2003     True
2004     True
2005    False
2006    False
2007    False
2008     True
2009    False
2010     True
2011     True
2012    False
2013     True
2014    False
2015     True
2016    False
2017     True
2018     True
2019    False
2020     True
2021     True
2022    False
2023     True
2024    False
2025     True
dtype: bool

In [18]:
# Check if a dataset has any missing values(Not how many) per row

temp_avg_year_country.isna().any(axis = 1)

country
Australia     True
Brazil        True
Canada        True
China         True
France       False
Germany       True
India         True
Pakistan      True
UK            True
USA           True
dtype: bool

In [21]:
# Check if the dataset has any missing values in general
temp_avg_year_country.isna().any().any()

np.True_

| Code                    | Purpose                                              |
| ----------------------- | ---------------------------------------------------- |
| `df.isna()`             | Show every missing value as True/False               |
| `df.isna().sum()`       | Count missing values in each column                  |
| `df.isna().sum(axis=1)` | Count missing values in each row                     |
| `df.isna().any()`       | Check which columns contain missing values           |
| `df.isna().any().any()` | Check if the entire DataFrame has any missing values |

### dropna()

In [23]:
# Total number of rows and columns before dropna()
temp_avg_year_country.shape

(10, 46)

In [27]:
# Total number of rows and columns after dropna()
temp_avg_year_country.dropna().shape

(1, 46)

In [31]:
temp_avg_year_country.dropna(axis=1).shape

(10, 21)

#### When to use dropna()

Usually when:

- the dataset is huge,
- only a few rows have missing values,
- and removing those rows won't hurt the analysis.

Otherwise, we look for smarter approaches, like:

- filling missing values,
- removing only specific columns,
- or removing rows only when certain columns are missing.

In [32]:
temp_avg_year_country.dropna(how="any").shape

(1, 46)

In [33]:
temp_avg_year_country.dropna(how="all").shape

(10, 46)

In [34]:
temp_avg_year_country

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [38]:
# Removing duplicates in a specific column using subset.

temp_avg_year_country.dropna(subset=[1984])

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410,13.280000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410,14.290000

#### DropNA Challenge 1

A climate researcher says:

> "I'm studying long-term climate trends, so I only want countries that have a complete temperature record for every year in the dataset."

Using `temp_avg_year_country`, produce a DataFrame that satisfies this request.

In [40]:
temp_avg_year_country.dropna(how="any")

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
France,14.58,14.506667,14.64,14.05,14.325714,14.32,14.365,14.855,14.755,14.52,...,14.916667,14.845,14.67,14.68,14.216667,14.6,13.81,15.58,15.32,15.35

#### Data Analysis Question

A researcher now changes the requirement.

> "I don't mind if a country is missing a few years of data. I only want to remove countries that have **no temperature records whatsoever**."

Using `temp_avg_year_country`, produce the required DataFrame.

In [41]:
temp_avg_year_country.dropna(axis= 0, how="all")

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

#### Data Analysis Question

A climate researcher says:

> "For my study, I only care about the years **2000**, **2001**, and **2002**.

> Remove countries that are missing temperature data in **any** of those three years, but ignore missing values in every other year."

Produce the required DataFrame.

In [44]:
temp_avg_year_country.dropna(subset=[2000,2001,2002])

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360,14.900000,14.740000,14.360000,14.5275,14.410000,13.28
Brazil,14.83500,14.202500,14.330000,13.760,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730,15.130000,NaN,14.200000,14.7300,14.273333,14.00
Canada,14.82000,14.595000,14.020000,14.495,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295,15.690000,14.140000,13.606667,14.0700,14.610000,14.02
China,14.73250,14.883333,14.037500,15.100,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680,14.216667,14.600000,13.810000,15.5800,15.320000,15.35
Germany,14.04500,14.490000,NaN,14.495,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550,14.545000,14.756667,13.610000,13.8100,14.685000,14.65
USA,14.42625,14.746667,14.236667,13.550,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620,14.586667,14.807500,15.290000,13.9525,14.410000,14.29

#### fillna()

A climate researcher says:

"I don't want to remove any countries from my pivot table.

Instead, replace every missing temperature value with 0 while keeping all countries and all years."

Use temp_avg_year_country to produce the required DataFrame.

In [45]:
temp_avg_year_country.fillna(0)

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,0.000000,14.755000,0.000000,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,0.000000,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,0.000000,15.323333,0.000000,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,0.000000
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,0.000000,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,0.000000,14.970000,15.090000,0.0000,14.740000,14.235000
Pakistan,14.18000,0.000000,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,0.000000,0.000000,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

A researcher says:

"I don't want to replace missing temperatures with zero because that would be misleading.

Instead, replace every missing value with the average temperature of the entire pivot table column (each year's average temperature)."

In [47]:
temp_avg_year_country.fillna(temp_avg_year_country.mean())

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.527500,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,14.596079,14.755000,14.505417,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,14.590463,14.200000,14.730000,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.070000,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,14.505417,15.323333,14.497593,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.364000,14.202000,14.369074
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.580000,15.320000,15.350000
Germany,14.04500,14.490000,14.392407,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.810000,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,14.858704,14.970000,15.090000,14.465444,14.740000,14.235000
Pakistan,14.18000,14.634185,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.930000,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.225000,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,14.529333,14.385185,14.620000,14.586667,14.807500,15.290000,13.952500,14.410000,14.290000


A researcher believes the temperature data contains a few unusually hot years that could affect the average.

Instead of filling missing values with the **mean**, replace every missing value in `temp_avg_year_country` with the **median temperature of its respective year**.

In [49]:
temp_avg_year_country.fillna(temp_avg_year_country.median())

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,14.655000,14.755000,14.535000,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,14.610000,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,14.535000,15.323333,14.585000,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,14.290000
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,14.330000,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,14.900000,14.970000,15.090000,14.3640,14.740000,14.235000
Pakistan,14.18000,14.557500,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,14.483333,14.550000,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000