In [1]:
import pandas as pd

climate_df = pd.read_csv("../data/raw/climate_change_dataset.csv")

# Lesson 7: Data Cleaning
## Missing Values

In [2]:
# Detecting missing values
climate_df.isna()

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1196,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1197,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1198,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1199,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [3]:
climate_df.isna().sum()

year                          0
country                       0
global_avg_temperature        0
temperature_anomaly           0
max_temperature               0
min_temperature               0
co2_concentration_ppm         0
annual_rainfall_mm            0
sea_level_rise_mm             0
sea_surface_temperature       0
heatwave_days                 0
drought_index                 0
flood_events_count            0
forest_cover_percent          0
deforestation_rate            0
fossil_fuel_consumption       0
renewable_energy_share        0
air_quality_index             0
predicted_temperature_2050    0
climate_risk_index            0
dtype: int64

In [4]:
temp_avg_year_country = climate_df.pivot_table(
    index = "country",
    values= "global_avg_temperature",
    columns= "year",
    aggfunc= "mean"
)

temp_avg_year_country

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [5]:
# .sum(); Count the number of missing values in each column.
temp_avg_year_country.isna().sum()

year
1980    0
1981    1
1982    1
1983    0
1984    1
1985    0
1986    2
1987    0
1988    1
1989    0
1990    0
1991    1
1992    1
1993    1
1994    0
1995    2
1996    0
1997    1
1998    0
1999    0
2000    1
2001    2
2002    0
2003    2
2004    2
2005    0
2006    0
2007    0
2008    1
2009    0
2010    1
2011    1
2012    0
2013    1
2014    0
2015    1
2016    0
2017    1
2018    1
2019    0
2020    1
2021    1
2022    0
2023    1
2024    0
2025    1
dtype: int64

In [6]:
# .sum(axis =1 ); Count the number of missing values in each row.
temp_avg_year_country.isna().sum(axis=1)

country
Australia    3
Brazil       5
Canada       2
China        5
France       0
Germany      3
India        3
Pakistan     4
UK           2
USA          3
dtype: int64

In [7]:
# Does this row contain at least one missing value?
temp_avg_year_country.isna().any(axis=1)

country
Australia     True
Brazil        True
Canada        True
China         True
France       False
Germany       True
India         True
Pakistan      True
UK            True
USA           True
dtype: bool

In [8]:
climate_df[climate_df["country"] == "Brazil"].sort_values("year").head(20)

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
380,1980,Brazil,15.39,0.53,26.77,7.64,386.47,1321.91,3.28,17.19,18,0.33,2,26.39,1.53,44.06,17.84,190,2.88,33.22
745,1980,Brazil,14.28,0.65,30.78,4.78,443.76,1061.01,2.35,16.93,50,0.62,9,23.97,0.21,69.07,57.63,139,1.73,80.63
201,1981,Brazil,13.88,1.52,31.63,9.92,411.55,598.96,3.66,18.35,21,3.71,5,53.38,1.45,88.01,31.48,124,2.85,30.82
259,1981,Brazil,14.47,0.54,28.38,9.68,433.84,546.68,4.88,15.68,20,2.86,4,31.23,1.77,41.29,12.27,160,2.61,4.97
1080,1981,Brazil,13.21,0.69,31.53,4.46,436.82,1205.45,1.92,13.99,32,0.73,9,46.91,1.62,66.81,54.90,184,2.79,24.37
289,1981,Brazil,15.25,1.15,39.06,10.57,397.60,905.10,1.24,16.14,24,4.36,5,15.69,2.62,65.24,17.61,89,2.33,8.80
302,1982,Brazil,14.19,1.23,29.58,8.90,410.07,1304.28,4.09,14.37,29,3.36,5,30.53,1.31,56.86,11.22,99,3.05,25.88
197,1982,Brazil,14.47,0.51,31.95,4.38,405.90,1242.33,3.69,15.49,44,0.76,5,38.52,2.54,50.26,59.35,196,1.91,28.90
812,1983,Brazil,13.69,1.61,38.20,11.23,407.91,1329.84,3.21,15.59,20,1.94,13,45.09,1.58,52.01,23.27,197,1.70,4.49
1077,1983,Brazil,13.83,1.42,32.89,2.37,413.34,1013.94,1.83,15.71,29,3.52,6,60.59,1.24,72.50,33.53,170,2.85,51.88
162,1985,Brazil,14.18,1.65,33.75,-2.72,415.73,1375.09,4.00,15.59,59,4.45,11,33.67,2.06,56.08,23.13,154,2.45,40.96
929,1985,Brazil,15.33,0.51,45.14,12.17,446.18,922.07,2.19,15.82,39,2.13,1,69.16,1.20,86.01,47.75,67,2.23,66.22
313,1987,Brazil,15.00,0.60,31.82,5.37,416.70,1040.14,4.12,17.01,19,0.73,11,40.44,1.10,82.82,30.52,71,2.87,31.22
276,1987,Brazil,14.40,1.20,33.97,7.44,371.39,600.76,3.66,16.69,54,4.76,6,31.83,0.38,82.66,57.14,124,3.32,31.12
403,1987,Brazil,14.38,1.03,46.40,-1.30,430.02,1289.25,3.79,14.09,58,1.83,13,14.80,2.65,85.46,53.40,167,1.53,86.28
300,1987,Brazil,14.26,0.63,32.06,-1.00,437.39,660.58,-0.27,17.54,37,2.51,5,42.21,1.24,74.21,15.86,78,2.37,7.87
1074,1987,Brazil,14.08,1.13,32.88,5.90,435.84,766.55,4.86,16.87,0,1.74,14,68.14,0.40,38.80,53.71,52,2.44,28.13
897,1987,Brazil,15.10,1.54,29.11,12.09,428.37,764.92,1.77,16.43,17,0.93,3,36.95,2.09,72.29,49.65,141,2.47,51.10
559,1988,Brazil,14.62,1.57,31.92,5.92,455.01,1013.44,1.67,16.20,23,4.85,12,65.47,1.70,55.21,15.16,123,2.59,61.18
876,1989,Brazil,14.22,0.74,37.17,7.85,439.60,817.60,3.94,16.32,20,2.99,8,26.06,2.99,51.73,8.64,158,1.94,17.79

In [9]:
temp_avg_year_country

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [10]:
temp_avg_year_country.isna().sum()

year
1980    0
1981    1
1982    1
1983    0
1984    1
1985    0
1986    2
1987    0
1988    1
1989    0
1990    0
1991    1
1992    1
1993    1
1994    0
1995    2
1996    0
1997    1
1998    0
1999    0
2000    1
2001    2
2002    0
2003    2
2004    2
2005    0
2006    0
2007    0
2008    1
2009    0
2010    1
2011    1
2012    0
2013    1
2014    0
2015    1
2016    0
2017    1
2018    1
2019    0
2020    1
2021    1
2022    0
2023    1
2024    0
2025    1
dtype: int64

In [11]:
temp_avg_year_country.isna().sum(axis=1)

country
Australia    3
Brazil       5
Canada       2
China        5
France       0
Germany      3
India        3
Pakistan     4
UK           2
USA          3
dtype: int64

In [12]:
# Check if a dataset has any missing values(Not how many) per column

temp_avg_year_country.isna().any()

year
1980    False
1981     True
1982     True
1983    False
1984     True
1985    False
1986     True
1987    False
1988     True
1989    False
1990    False
1991     True
1992     True
1993     True
1994    False
1995     True
1996    False
1997     True
1998    False
1999    False
2000     True
2001     True
2002    False
2003     True
2004     True
2005    False
2006    False
2007    False
2008     True
2009    False
2010     True
2011     True
2012    False
2013     True
2014    False
2015     True
2016    False
2017     True
2018     True
2019    False
2020     True
2021     True
2022    False
2023     True
2024    False
2025     True
dtype: bool

In [13]:
# Check if a dataset has any missing values(Not how many) per row

temp_avg_year_country.isna().any(axis = 1)

country
Australia     True
Brazil        True
Canada        True
China         True
France       False
Germany       True
India         True
Pakistan      True
UK            True
USA           True
dtype: bool

In [14]:
# Check if the dataset has any missing values in general
temp_avg_year_country.isna().any().any()

np.True_

| Code                    | Purpose                                              |
| ----------------------- | ---------------------------------------------------- |
| `df.isna()`             | Show every missing value as True/False               |
| `df.isna().sum()`       | Count missing values in each column                  |
| `df.isna().sum(axis=1)` | Count missing values in each row                     |
| `df.isna().any()`       | Check which columns contain missing values           |
| `df.isna().any().any()` | Check if the entire DataFrame has any missing values |

### dropna()

In [15]:
# Total number of rows and columns before dropna()
temp_avg_year_country.shape

(10, 46)

In [16]:
# Total number of rows and columns after dropna()
temp_avg_year_country.dropna().shape

(1, 46)

In [17]:
temp_avg_year_country.dropna(axis=1).shape

(10, 21)

#### When to use dropna()

Usually when:

- the dataset is huge,
- only a few rows have missing values,
- and removing those rows won't hurt the analysis.

Otherwise, we look for smarter approaches, like:

- filling missing values,
- removing only specific columns,
- or removing rows only when certain columns are missing.

In [18]:
temp_avg_year_country.dropna(how="any").shape

(1, 46)

In [19]:
temp_avg_year_country.dropna(how="all").shape

(10, 46)

In [20]:
temp_avg_year_country

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [21]:
# Removing nulls in a specific column using subset (Removes the whole row)

temp_avg_year_country.dropna(subset=[1984])

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410,13.280000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410,14.290000

#### DropNA Challenge 1

A climate researcher says:

> "I'm studying long-term climate trends, so I only want countries that have a complete temperature record for every year in the dataset."

Using `temp_avg_year_country`, produce a DataFrame that satisfies this request.

In [22]:
temp_avg_year_country.dropna(how="any")

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
France,14.58,14.506667,14.64,14.05,14.325714,14.32,14.365,14.855,14.755,14.52,...,14.916667,14.845,14.67,14.68,14.216667,14.6,13.81,15.58,15.32,15.35

#### Data Analysis Question

A researcher now changes the requirement.

> "I don't mind if a country is missing a few years of data. I only want to remove countries that have **no temperature records whatsoever**."

Using `temp_avg_year_country`, produce the required DataFrame.

In [23]:
temp_avg_year_country.dropna(axis= 0, how="all")

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

#### Data Analysis Question

A climate researcher says:

> "For my study, I only care about the years **2000**, **2001**, and **2002**.

> Remove countries that are missing temperature data in **any** of those three years, but ignore missing values in every other year."

Produce the required DataFrame.

In [24]:
temp_avg_year_country.dropna(subset=[2000,2001,2002])

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360,14.900000,14.740000,14.360000,14.5275,14.410000,13.28
Brazil,14.83500,14.202500,14.330000,13.760,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730,15.130000,NaN,14.200000,14.7300,14.273333,14.00
Canada,14.82000,14.595000,14.020000,14.495,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295,15.690000,14.140000,13.606667,14.0700,14.610000,14.02
China,14.73250,14.883333,14.037500,15.100,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680,14.216667,14.600000,13.810000,15.5800,15.320000,15.35
Germany,14.04500,14.490000,NaN,14.495,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550,14.545000,14.756667,13.610000,13.8100,14.685000,14.65
USA,14.42625,14.746667,14.236667,13.550,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620,14.586667,14.807500,15.290000,13.9525,14.410000,14.29

#### fillna()

A climate researcher says:

"I don't want to remove any countries from my pivot table.

Instead, replace every missing temperature value with 0 while keeping all countries and all years."

Use temp_avg_year_country to produce the required DataFrame.

In [25]:
temp_avg_year_country.fillna(0)

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,0.000000,14.755000,0.000000,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,0.000000,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,0.000000,15.323333,0.000000,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,0.000000
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,0.000000,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,0.000000,14.970000,15.090000,0.0000,14.740000,14.235000
Pakistan,14.18000,0.000000,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,0.000000,0.000000,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

A researcher says:

"I don't want to replace missing temperatures with zero because that would be misleading.

Instead, replace every missing value with the average temperature of the entire pivot table column (each year's average temperature)."

In [26]:
temp_avg_year_country.fillna(temp_avg_year_country.mean())

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.527500,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,14.596079,14.755000,14.505417,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,14.590463,14.200000,14.730000,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.070000,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,14.505417,15.323333,14.497593,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.364000,14.202000,14.369074
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.580000,15.320000,15.350000
Germany,14.04500,14.490000,14.392407,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.810000,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,14.858704,14.970000,15.090000,14.465444,14.740000,14.235000
Pakistan,14.18000,14.634185,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.930000,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.225000,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,14.529333,14.385185,14.620000,14.586667,14.807500,15.290000,13.952500,14.410000,14.290000


A researcher believes the temperature data contains a few unusually hot years that could affect the average.

Instead of filling missing values with the **mean**, replace every missing value in `temp_avg_year_country` with the **median temperature of its respective year**.

In [27]:
temp_avg_year_country.fillna(temp_avg_year_country.median())

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,14.655000,14.755000,14.535000,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,14.610000,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,14.535000,15.323333,14.585000,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,14.290000
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,14.330000,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,14.900000,14.970000,15.090000,14.3640,14.740000,14.235000
Pakistan,14.18000,14.557500,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,14.483333,14.550000,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

Challenge 1: The Cold Drop 

You're inspecting temp_avg_year_country. You notice that some countries have missing average temperatures for certain years. Your lead data scientist asks you to completely remove any country (row) that has at least one missing value across any of the years, and save this clean view as a new variable called complete_countries_df.

Write the code to accomplish this.

In [28]:
complete_countries_df= temp_avg_year_country.dropna()
complete_countries_df

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
France,14.58,14.506667,14.64,14.05,14.325714,14.32,14.365,14.855,14.755,14.52,...,14.916667,14.845,14.67,14.68,14.216667,14.6,13.81,15.58,15.32,15.35

Challenge 2: The Timeline Gap 

Now, instead of dropping entire countries, your team wants to keep all countries, but deal with missing values year-by-year.

A senior analyst asks: "If a country is missing its average temperature for a specific year, drop any year (column) from the pivot table that contains any missing data across all countries." Save this as complete_years_df.

In [29]:
complete_years_df = temp_avg_year_country.dropna(axis = 1)
complete_years_df

year,1980,1983,1985,1987,1989,1990,1994,1996,1998,1999,...,2005,2006,2007,2009,2012,2014,2016,2019,2022,2024
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,12.780000,14.155000,14.336000,14.820000,14.280000,16.1000,15.3600,14.3475,14.360000,...,13.705000,13.680000,14.358000,14.300000,14.823333,15.016667,14.185000,14.360000,14.360000,14.410000
Brazil,14.83500,13.760000,14.755000,14.536667,13.695000,13.790000,14.0500,15.4600,14.2500,13.880000,...,14.385000,14.776667,14.573333,14.950000,14.476000,14.520000,14.317500,14.730000,14.200000,14.273333
Canada,14.82000,14.495000,14.500000,14.283333,14.480000,14.750000,14.6400,14.7600,14.7600,14.263333,...,14.185000,14.575000,13.920000,13.865000,14.680000,14.196667,13.590000,14.295000,13.606667,14.610000
China,14.73250,15.100000,14.613333,15.323333,14.633333,14.050000,14.5940,14.2025,14.6400,14.283333,...,14.090000,14.395000,14.476667,14.885000,14.718889,15.150000,14.348571,14.938000,14.530000,14.202000
France,14.58000,14.050000,14.320000,14.855000,14.520000,15.140000,13.9050,15.2600,15.0125,14.085000,...,14.750000,14.360000,14.800000,14.406667,14.283333,14.170000,14.916667,14.680000,13.810000,15.320000
Germany,14.04500,14.495000,14.493333,14.356667,14.430000,14.335000,15.1650,14.1250,14.6900,13.810000,...,14.882000,14.850000,14.953333,14.528571,15.150000,14.110000,14.845000,14.550000,13.610000,14.685000
India,14.18250,14.252500,14.772500,14.700000,14.900000,13.835000,14.5125,14.7800,14.8750,14.950000,...,14.543333,14.626667,13.600000,15.226667,13.846667,14.246667,14.083333,15.086667,15.090000,14.740000
Pakistan,14.18000,14.093333,14.456667,14.130000,13.653333,14.490000,14.3900,14.8100,15.0700,14.265000,...,14.341000,14.890000,14.926667,14.477500,14.130000,15.690000,14.630000,13.963333,14.165000,14.170000
UK,14.43500,14.715000,14.776667,13.520000,14.660000,14.210000,14.9900,14.4300,14.5200,14.257500,...,14.860000,14.360000,14.320000,13.860000,14.694000,14.335000,15.060000,13.873333,14.090000,14.730000
USA,14.42625,13.550000,14.130000,14.535000,14.460000,14.338333,14.4450,14.5075,14.6750,14.075000,...,14.896667,14.483333,14.535000,13.670000,14.598000,14.630000,13.706667,14.620000,15.290000,14.410000

Challenge 3: The Reasonable Estimate 

Now, let's swap from dropping data to filling missing data!

Your lead analyst comes to you with a compromise:

"We don't want to lose whole rows or columns. Instead, if a country is missing its average temperature for any given year, let's fill in that missing cell using the overall average temperature of the entire dataset."

Save this filled table as filled_temp_df.

In [30]:
overall_mean = temp_avg_year_country.mean().mean()
overall_mean

filled_temp_df = temp_avg_year_country.fillna(overall_mean)
filled_temp_df

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.52750,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,14.499790,14.755000,14.499790,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,14.499790,14.200000,14.73000,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.07000,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,14.499790,15.323333,14.499790,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.36400,14.202000,14.499790
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.58000,15.320000,15.350000
Germany,14.04500,14.490000,14.499790,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.81000,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,14.499790,14.970000,15.090000,14.49979,14.740000,14.235000
Pakistan,14.18000,14.499790,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.93000,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.22500,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,14.499790,14.499790,14.620000,14.586667,14.807500,15.290000,13.95250,14.410000,14.290000

Challenge 4: Forward Fill Across Time 

If a country is missing a value in a specific year, fill it using the value from the most recent previous year (propagating values forward left-to-right across the year columns).

Save this as ffill_temp_df.

(Hint: Try using .ffill() or .fillna(method='ffill'), but remember to specify the right axis so it moves across columns/years instead of down rows!)

Write the code to accomplish this.

In [31]:
temp_avg_year_country

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [32]:
ffill_temp_df = temp_avg_year_country.ffill(axis=1)
ffill_temp_df

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,13.760000,14.755000,14.755000,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,15.130000,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,14.613333,15.323333,15.323333,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,14.202000
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,14.490000,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,15.086667,14.970000,15.090000,15.0900,14.740000,14.235000
Pakistan,14.18000,14.180000,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,13.706667,13.706667,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

 Challenges 5

 Modify your code so that it first tries to forward fill across years (axis=1), and then immediately uses backward fill (.bfill()) across years (axis=1) to catch any remaining leading missing values. Save the result as fully_filled_df.

In [33]:
fully_filled_df = temp_avg_year_country.ffill(axis=1).bfill(axis = 1)
fully_filled_df

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,13.760000,14.755000,14.755000,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,15.130000,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,14.613333,15.323333,15.323333,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,14.202000
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,14.490000,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,15.086667,14.970000,15.090000,15.0900,14.740000,14.235000
Pakistan,14.18000,14.180000,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,13.706667,13.706667,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

### Boolean Filtering 
Revision and reminder

In [34]:
climate_df[
    climate_df["global_avg_temperature"] > 25
]

Empty DataFrame
Columns: [year, country, global_avg_temperature, temperature_anomaly, max_temperature, min_temperature, co2_concentration_ppm, annual_rainfall_mm, sea_level_rise_mm, sea_surface_temperature, heatwave_days, drought_index, flood_events_count, forest_cover_percent, deforestation_rate, fossil_fuel_consumption, renewable_energy_share, air_quality_index, predicted_temperature_2050, climate_risk_index]
Index: []

In [35]:
climate_df[
    climate_df["country"] == "Brazil"
    ].head(10).sort_values(["country"])

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
19,2023,Brazil,14.37,1.04,33.31,4.75,355.78,1020.78,4.80,17.73,56,4.66,9,34.42,0.55,60.17,54.04,80,1.87,19.24
26,2001,Brazil,14.21,1.54,32.56,-2.30,431.47,740.50,3.16,15.63,58,1.96,3,15.88,1.50,20.30,50.71,167,1.83,38.62
66,2023,Brazil,15.27,1.59,36.49,5.57,435.26,709.94,3.82,16.15,49,4.82,11,53.96,0.45,73.30,46.74,199,2.59,7.98
82,2005,Brazil,14.85,0.56,38.92,-1.93,396.93,1007.97,3.31,15.73,54,4.76,0,36.17,3.00,35.54,34.23,187,0.43,97.22
85,2020,Brazil,15.37,1.16,40.47,3.30,398.00,350.86,3.69,15.49,31,2.05,6,48.38,1.76,53.61,45.48,141,1.57,1.69
87,1994,Brazil,14.05,1.32,32.15,5.16,412.59,1104.57,2.13,17.04,52,4.36,4,68.94,0.77,21.59,6.42,45,2.10,64.41
101,2014,Brazil,15.00,0.59,22.06,5.52,387.82,973.48,3.76,14.95,18,2.76,3,47.85,2.07,80.52,46.20,133,2.25,34.08
106,2018,Brazil,15.07,1.26,29.82,7.82,414.87,944.53,3.95,15.53,0,4.72,12,38.10,3.19,32.22,9.95,78,2.29,68.30
114,2012,Brazil,14.79,1.31,42.59,5.99,418.47,759.44,1.43,16.72,43,4.80,4,50.42,2.87,37.18,38.83,61,2.00,37.60
118,2014,Brazil,15.62,0.71,32.14,7.58,382.93,959.76,3.42,19.16,12,0.67,2,19.02,1.98,27.53,9.38,56,2.34,30.83

Suppose your manager asks:

Show me all records for Brazil after 2010.

In [36]:
climate_df[(climate_df["country"] == "Brazil") & (climate_df["year"]>= 2010)].sort_values(["year"])

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
660,2010,Brazil,13.87,1.14,32.33,2.09,395.92,1543.09,2.99,16.49,37,0.10,7,19.16,0.23,38.29,11.64,72,2.62,9.62
750,2010,Brazil,14.88,2.08,33.03,-4.08,447.30,1011.61,3.88,17.00,45,1.74,2,53.96,0.37,45.72,59.89,179,1.77,68.32
343,2011,Brazil,14.97,1.79,35.56,3.05,406.54,915.51,3.34,15.55,11,4.79,13,63.09,3.31,70.80,53.65,143,2.25,94.98
214,2011,Brazil,13.63,0.74,36.09,2.70,402.74,986.80,3.33,15.92,15,2.98,0,51.52,3.22,23.16,25.24,195,2.34,30.91
645,2011,Brazil,14.21,0.60,37.33,3.82,435.91,857.06,2.08,16.69,56,2.71,7,67.17,1.58,70.04,49.90,131,1.85,93.67
273,2012,Brazil,14.71,1.01,35.33,3.49,445.57,1335.06,4.34,17.58,55,1.78,13,34.76,2.66,51.12,8.40,81,1.74,43.89
114,2012,Brazil,14.79,1.31,42.59,5.99,418.47,759.44,1.43,16.72,43,4.80,4,50.42,2.87,37.18,38.83,61,2.00,37.60
341,2012,Brazil,14.32,0.35,41.31,4.90,427.00,1539.72,2.74,16.45,25,1.28,3,56.14,0.39,66.35,19.39,197,1.84,21.09
462,2012,Brazil,13.40,1.36,38.80,5.34,447.88,1089.17,5.20,15.16,50,1.04,8,23.45,3.39,21.05,21.10,102,1.88,31.97
1048,2012,Brazil,15.16,1.32,22.13,12.06,422.30,1130.85,4.41,19.75,35,2.98,2,32.93,2.18,29.47,6.92,96,2.20,30.18
754,2013,Brazil,14.70,0.77,33.58,-1.63,440.20,800.41,4.43,16.12,45,1.75,9,32.95,1.22,46.05,56.05,184,2.20,96.55
372,2014,Brazil,13.89,1.07,33.47,3.55,407.28,808.96,1.97,19.91,58,0.28,1,19.37,3.23,51.05,51.37,171,2.67,4.25
118,2014,Brazil,15.62,0.71,32.14,7.58,382.93,959.76,3.42,19.16,12,0.67,2,19.02,1.98,27.53,9.38,56,2.34,30.83
101,2014,Brazil,15.00,0.59,22.06,5.52,387.82,973.48,3.76,14.95,18,2.76,3,47.85,2.07,80.52,46.20,133,2.25,34.08
333,2014,Brazil,14.18,0.48,32.43,3.68,431.35,555.57,4.07,14.92,44,1.98,7,22.14,1.77,78.59,21.96,156,2.54,0.17
545,2014,Brazil,14.06,0.76,25.96,0.27,404.43,1234.56,4.78,14.75,8,4.67,7,48.83,1.62,44.99,33.70,83,1.61,54.63
996,2014,Brazil,14.37,1.06,28.06,-2.63,365.47,966.84,4.21,15.09,43,2.99,3,62.82,1.62,55.96,33.09,69,1.92,0.72
978,2016,Brazil,13.45,0.99,34.74,5.66,418.10,751.59,4.70,15.72,36,2.08,9,40.06,1.06,55.12,38.22,87,2.84,17.58
925,2016,Brazil,14.52,2.08,35.64,6.11,392.07,1367.08,4.23,18.54,27,0.33,13,55.42,0.44,36.43,19.71,161,1.83,78.35
909,2016,Brazil,15.06,0.41,44.98,12.96,389.32,1221.46,4.19,17.45,6,4.80,11,43.33,0.97,37.45,13.78,197,1.62,19.51
184,2016,Brazil,14.24,1.32,37.98,6.02,382.73,816.74,2.10,16.29,36,0.34,1,32.16,1.20,36.48,52.38,79,1.96,45.66
773,2017,Brazil,14.72,0.92,37.74,6.46,400.16,991.95,2.81,16.20,13,4.49,13,67.65,2.24,41.78,21.48,78,1.95,93.43
278,2017,Brazil,14.45,0.77,34.10,7.71,387.38,873.52,2.22,16.38,35,3.62,5,20.72,0.56,48.26,10.51,191,2.80,5.83
780,2017,Brazil,14.60,1.08,41.73,11.39,403.01,905.88,2.89,17.12,30,1.63,4,39.21,0.19,83.62,25.26,145,2.26,4.19
1027,2017,Brazil,13.98,1.27,42.02,5.61,414.78,937.22,4.53,15.98,3,3.27,1,24.11,2.22,82.47,19.64,149,2.72,83.16
1148,2017,Brazil,15.72,0.67,42.64,-0.93,430.48,1000.44,3.18,15.50,42,4.50,2,18.77,0.93,89.63,37.71,141,2.05,99.27
1039,2018,Brazil,15.53,1.24,35.28,5.02,422.21,527.95,4.96,15.04,17,4.69,8,15.33,1.15,34.72,15.49,150,2.16,88.46
438,2018,Brazil,14.73,0.62,23.69,3.34,431.47,620.84,1.46,14.92,51,4.06,14,66.88,2.94,62.52,25.13,46,1.39,24.96
752,2018,Brazil,14.34,0.38,32.47,1.39,431.95,1804.15,5.52,15.32,12,2.00,4,23.09,2.49,22.78,56.24,66,2.47,3.97
106,2018,Brazil,15.07,1.26,29.82,7.82,414.87,944.53,3.95,15.53,0,4.72,12,38.10,3.19,32.22,9.95,78,2.29,68.30
634,2018,Brazil,14.70,1.14,38.74,5.30,402.88,921.87,3.87,15.21,58,4.16,9,13.01,0.48,49.90,22.67,166,2.20,25.03
1050,2018,Brazil,15.78,1.02,32.33,11.15,414.73,523.29,2.94,16.40,50,0.17,10,10.78,3.02,75.93,49.62,77,2.40,31.92
1177,2019,Brazil,14.09,0.74,40.70,7.68,438.58,1187.02,3.05,15.96,43,3.02,7,25.17,3.18,87.57,5.56,100,1.66,20.08
1037,2019,Brazil,14.91,0.85,38.08,7.27,412.11,663.32,1.59,16.31,26,4.69,14,17.85,3.25,89.39,7.16,194,2.23,37.25
898,2019,Brazil,14.99,1.16,44.37,5.40,400.08,1039.29,5.90,16.47,55,4.64,3,51.23,2.49,55.49,16.65,187,1.86,60.70
999,2019,Brazil,14.93,0.77,37.07,4.25,400.64,1498.30,3.51,15.61,22,4.37,5,20.96,1.92,76.26,39.45,140,2.33,4.45
85,2020,Brazil,15.37,1.16,40.47,3.30,398.00,350.86,3.69,15.49,31,2.05,6,48.38,1.76,53.61,45.48,141,1.57,1.69
241,2020,Brazil,14.89,1.25,38.55,4.21,411.52,709.28,3.80,15.18,56,2.73,9,36.27,2.54,54.51,37.92,70,3.15,18.33
963,2022,Brazil,14.20,1.18,34.83,12.24,432.54,1123.75,3.88,15.06,8,2.49,8,29.54,0.66,25.93,20.26,145,2.36,97.17
500,2023,Brazil,14.82,0.96,40.23,1.85,432.12,1090.22,4.19,15.73,8,3.76,10,12.10,0.75,53.51,15.76,43,2.12,74.99
66,2023,Brazil,15.27,1.59,36.49,5.57,435.26,709.94,3.82,16.15,49,4.82,11,53.96,0.45,73.30,46.74,199,2.59,7.98
19,2023,Brazil,14.37,1.04,33.31,4.75,355.78,1020.78,4.80,17.73,56,4.66,9,34.42,0.55,60.17,54.04,80,1.87,19.24
899,2023,Brazil,14.46,1.10,39.89,6.88,387.30,743.06,4.91,15.71,20,2.96,12,42.37,1.42,36.67,54.59,144,1.43,27.61
703,2024,Brazil,13.05,0.59,37.08,2.79,428.54,555.47,4.13,16.93,34,3.91,0,62.69,1.36,53.34,24.25,95,1.90,50.51
644,2024,Brazil,14.94,1.57,29.27,-1.73,383.79,727.49,2.29,13.59,46,1.68,5,12.18,2.39,50.07,51.55,114,2.08,26.66
1070,2024,Brazil,14.83,1.24,35.86,3.22,415.05,708.70,4.43,17.10,19,2.85,6,14.71,0.38,49.51,56.26,93,2.15,35.31
453,2025,Brazil,14.05,0.90,25.03,1.56,375.28,1352.26,4.39,16.57,48,1.59,7,47.24,3.09,83.77,24.43,151,2.81,28.69
338,2025,Brazil,13.95,0.90,33.75,9.00,456.56,1226.11,2.82,16.86,11,2.21,10,14.25,3.35,21.81,47.60,183,1.61,96.57

Suppose the manager says:

Show me records from Brazil OR Canada.

In [37]:
brazil_canada_data_df = climate_df[(climate_df["country"]== "Brazil") | (climate_df["country"] == "Canada")]
brazil_canada_data_df

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
8,2002,Canada,14.89,1.85,36.39,4.31,372.50,1244.87,4.16,17.39,29,0.41,13,38.26,2.95,71.61,45.23,113,2.86,72.18
9,1990,Canada,15.23,1.54,39.31,3.69,413.33,682.43,2.94,17.35,2,4.40,5,37.57,1.70,68.29,58.82,177,2.16,23.41
19,2023,Brazil,14.37,1.04,33.31,4.75,355.78,1020.78,4.80,17.73,56,4.66,9,34.42,0.55,60.17,54.04,80,1.87,19.24
26,2001,Brazil,14.21,1.54,32.56,-2.30,431.47,740.50,3.16,15.63,58,1.96,3,15.88,1.50,20.30,50.71,167,1.83,38.62
44,1993,Canada,14.44,0.72,38.31,1.63,405.32,1662.56,4.35,17.44,37,4.83,0,29.47,1.02,31.22,54.11,100,3.20,80.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1156,2022,Canada,13.25,1.09,29.33,3.55,404.69,1074.97,5.87,14.54,50,3.25,5,64.45,0.21,69.69,56.32,60,2.33,75.61
1158,2003,Canada,14.36,0.81,37.62,7.84,396.41,1164.42,3.31,17.55,21,0.66,3,61.41,3.39,42.26,39.59,139,1.92,38.34
1177,2019,Brazil,14.09,0.74,40.70,7.68,438.58,1187.02,3.05,15.96,43,3.02,7,25.17,3.18,87.57,5.56,100,1.66,20.08
1189,2008,Canada,15.41,1.62,38.13,8.90,437.53,906.63,2.66,17.62,25,0.69,9,58.55,2.10,63.03,37.22,83,1.81,38.82
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,54,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97

Suppose the manager says:

Show me every country except Brazil.

In [38]:
climate_df[climate_df["country"] != "Brazil"]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,37,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,44,1.96,3,19.13,2.38,21.56,22.78,112,1.91,25.39
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,54,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,5,3.99,13,19.46,2.76,64.51,12.09,103,1.40,83.67
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,41,0.47,4,33.91,1.78,54.68,46.40,91,2.92,6.43
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,9,0.91,12,66.56,0.48,62.18,7.55,102,1.64,88.74

In [39]:
climate_df[~(climate_df["country"] == "Brazil")]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,37,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,44,1.96,3,19.13,2.38,21.56,22.78,112,1.91,25.39
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,54,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,5,3.99,13,19.46,2.76,64.51,12.09,103,1.40,83.67
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,41,0.47,4,33.91,1.78,54.68,46.40,91,2.92,6.43
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,9,0.91,12,66.56,0.48,62.18,7.55,102,1.64,88.74

isin()

In [40]:
climate_df[climate_df["country"].isin(["Brazil", "Canada"])]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
8,2002,Canada,14.89,1.85,36.39,4.31,372.50,1244.87,4.16,17.39,29,0.41,13,38.26,2.95,71.61,45.23,113,2.86,72.18
9,1990,Canada,15.23,1.54,39.31,3.69,413.33,682.43,2.94,17.35,2,4.40,5,37.57,1.70,68.29,58.82,177,2.16,23.41
19,2023,Brazil,14.37,1.04,33.31,4.75,355.78,1020.78,4.80,17.73,56,4.66,9,34.42,0.55,60.17,54.04,80,1.87,19.24
26,2001,Brazil,14.21,1.54,32.56,-2.30,431.47,740.50,3.16,15.63,58,1.96,3,15.88,1.50,20.30,50.71,167,1.83,38.62
44,1993,Canada,14.44,0.72,38.31,1.63,405.32,1662.56,4.35,17.44,37,4.83,0,29.47,1.02,31.22,54.11,100,3.20,80.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1156,2022,Canada,13.25,1.09,29.33,3.55,404.69,1074.97,5.87,14.54,50,3.25,5,64.45,0.21,69.69,56.32,60,2.33,75.61
1158,2003,Canada,14.36,0.81,37.62,7.84,396.41,1164.42,3.31,17.55,21,0.66,3,61.41,3.39,42.26,39.59,139,1.92,38.34
1177,2019,Brazil,14.09,0.74,40.70,7.68,438.58,1187.02,3.05,15.96,43,3.02,7,25.17,3.18,87.57,5.56,100,1.66,20.08
1189,2008,Canada,15.41,1.62,38.13,8.90,437.53,906.63,2.66,17.62,25,0.69,9,58.55,2.10,63.03,37.22,83,1.81,38.82
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,54,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97

Combining isin() with AND

Suppose the manager says:

Show me Brazil and Canada after 2015.

In [41]:
climate_df[~(climate_df["country"].isin(["Brazil", "Canada"])) & (climate_df["year"] >= 2015)]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
6,2018,France,14.67,1.41,33.10,3.75,426.67,1422.19,1.48,15.78,45,1.05,5,44.54,3.46,65.85,21.51,71,2.67,23.87
12,2015,USA,15.37,0.70,27.99,2.78,396.88,1201.52,2.02,18.83,41,3.90,11,44.90,2.73,27.40,8.42,79,2.56,45.24
13,2019,France,15.58,1.47,41.60,5.09,393.12,485.46,2.85,16.87,2,0.58,13,24.46,3.09,50.52,47.71,81,2.42,15.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1157,2023,China,14.39,1.47,34.24,11.84,399.97,912.74,3.05,15.21,47,4.31,10,15.79,1.47,25.26,31.83,182,1.83,26.65
1165,2022,Australia,14.08,1.22,32.94,11.11,363.42,1490.31,4.23,16.84,25,4.31,13,50.84,1.98,59.29,43.52,57,1.88,11.94
1173,2020,France,14.10,1.19,30.24,6.55,407.83,447.08,3.12,15.96,46,3.76,7,22.89,2.37,35.31,5.12,52,2.86,18.12
1188,2024,Australia,14.66,1.42,50.07,5.35,424.36,877.68,2.57,16.20,43,2.00,13,62.69,1.85,24.91,23.49,102,1.82,88.58
1192,2019,India,14.95,1.01,30.61,11.32,428.29,1405.82,5.38,16.19,34,4.98,14,67.18,1.57,28.24,46.21,69,2.67,25.94

between()

Suppose your manager asks:

Show me all climate records between 2000 and 2010.

In [42]:
climate_df[climate_df["year"].between(2000,2010)].sort_values(["year"])

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
77,2000,France,13.84,1.23,33.90,7.61,409.28,1251.36,3.60,16.37,58,4.63,0,10.40,1.29,44.51,27.85,156,2.67,46.88
1130,2000,UK,15.11,0.87,33.16,-6.33,451.64,533.91,4.28,17.65,52,3.07,2,17.81,2.38,72.90,50.09,91,1.64,76.91
1138,2000,China,14.76,1.10,28.04,10.16,417.19,1091.57,3.66,13.87,23,3.50,1,25.75,0.74,26.97,30.48,76,2.97,7.19
298,2000,Canada,15.22,1.38,31.62,1.71,368.56,1482.36,4.02,14.62,42,3.04,1,49.09,1.99,79.85,57.40,125,1.84,6.24
317,2000,USA,14.59,1.22,31.60,9.53,389.64,801.99,3.20,19.89,38,2.55,6,57.32,0.94,45.50,59.38,194,1.61,26.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,2010,India,14.06,1.07,38.82,7.45,486.53,1030.14,1.95,16.92,50,1.62,0,68.36,3.24,62.95,11.29,182,2.20,11.32
988,2010,Germany,15.40,0.78,42.91,0.90,396.04,981.72,2.90,15.92,0,1.00,12,10.28,0.97,76.05,6.73,123,2.27,41.36
1068,2010,China,14.08,0.71,41.03,7.96,433.86,1341.62,3.55,16.11,14,2.37,9,46.57,3.34,62.31,24.12,156,2.85,62.54
71,2010,Canada,15.37,1.38,33.74,4.78,389.47,1107.96,4.07,15.52,59,2.62,7,28.14,2.85,37.96,37.10,161,2.23,30.51
1082,2010,France,15.13,1.11,29.93,5.13,427.01,1358.89,4.27,14.92,56,2.13,8,19.80,2.73,86.38,29.13,180,2.17,10.63

### Boolean filtering practice questions

#### Question 1

A climate policy team is preparing a report on regions that may have experienced severe heat stress in recent years.

They define "recent years" as **2015 onwards**, and they are only interested in countries whose **global average temperature exceeded 25°C** during those years.

Retrieve all records that satisfy these requirements.

In [43]:
climate_df[(climate_df["global_avg_temperature"] > 25) & (climate_df["year"] >= 2015)]

Empty DataFrame
Columns: [year, country, global_avg_temperature, temperature_anomaly, max_temperature, min_temperature, co2_concentration_ppm, annual_rainfall_mm, sea_level_rise_mm, sea_surface_temperature, heatwave_days, drought_index, flood_events_count, forest_cover_percent, deforestation_rate, fossil_fuel_consumption, renewable_energy_share, air_quality_index, predicted_temperature_2050, climate_risk_index]
Index: []

#### Question 2

An international conservation organization is studying countries that receive **very high rainfall**.

For this phase of the project, they are interested **only** in:

- Brazil
- India
- Indonesia

(The dataset may or may not contain all of these countries.)

Retrieve all rainfall records for the countries that are available in the dataset.

In [44]:
climate_df.head()

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,37,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77

In [45]:
climate_df[
    climate_df["country"].isin(["Brazil", "India", "Indonesia"])
]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,37,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10
7,1998,India,13.94,1.22,33.35,9.91,434.75,1122.34,4.60,14.54,48,3.13,10,22.86,0.93,31.12,11.51,110,2.10,83.59
10,1990,India,14.15,1.06,28.75,5.23,419.83,1295.18,5.55,15.57,27,0.26,13,47.37,1.58,58.02,11.42,138,2.37,97.50
19,2023,Brazil,14.37,1.04,33.31,4.75,355.78,1020.78,4.80,17.73,56,4.66,9,34.42,0.55,60.17,54.04,80,1.87,19.24
21,2017,India,13.73,1.11,29.88,5.76,387.03,1430.32,1.97,16.62,0,0.24,9,41.33,1.85,61.64,35.77,171,2.53,32.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1180,2011,India,14.39,1.47,30.37,-2.18,395.36,1102.40,2.99,12.71,36,0.21,0,67.29,2.73,53.07,47.71,199,2.78,38.07
1182,2009,India,15.56,1.30,35.72,2.96,429.06,904.80,0.52,16.24,15,1.39,12,51.94,0.96,21.10,24.86,95,1.82,97.48
1192,2019,India,14.95,1.01,30.61,11.32,428.29,1405.82,5.38,16.19,34,4.98,14,67.18,1.57,28.24,46.21,69,2.67,25.94
1194,1997,India,13.81,0.90,36.56,13.64,420.34,1336.85,2.10,15.38,19,4.68,5,37.87,2.89,80.50,20.44,102,1.66,30.41
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,44,1.96,3,19.13,2.38,21.56,22.78,112,1.91,25.39

In [46]:
climate_df.loc[
    climate_df["country"].isin(["Brazil", "India", "Indonesia"]),
    ["country", "year", "annual_rainfall_mm"]
]

     country  year  annual_rainfall_mm
1      India  2008              735.61
7      India  1998             1122.34
10     India  1990             1295.18
19    Brazil  2023             1020.78
21     India  2017             1430.32
...      ...   ...                 ...
1180   India  2011             1102.40
1182   India  2009              904.80
1192   India  2019             1405.82
1194   India  1997             1336.85
1195   India  1980             1483.91

[234 rows x 3 columns]

In [47]:
# Recap on .loc

climate_df.loc[[2,5,6], ["country", "year", "annual_rainfall_mm"]]

    country  year  annual_rainfall_mm
2  Pakistan  1994             1982.92
5    France  2000             1178.57
6    France  2018             1422.19

In [48]:
climate_df.loc[[4,8]]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77
8,2002,Canada,14.89,1.85,36.39,4.31,372.50,1244.87,4.16,17.39,29,0.41,13,38.26,2.95,71.61,45.23,113,2.86,72.18

In [49]:
# recap on .iloc

climate_df.iloc[[4,8]]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77
8,2002,Canada,14.89,1.85,36.39,4.31,372.50,1244.87,4.16,17.39,29,0.41,13,38.26,2.95,71.61,45.23,113,2.86,72.18

In [50]:
climate_df.iloc[[2,4,6], [3,6]]

   temperature_anomaly  co2_concentration_ppm
2                 1.24                 450.54
4                 1.32                 403.42
6                 1.41                 426.67

In [51]:
climate_df.loc[
    climate_df["country"] == "Brazil",
    ["country", "year"]
]

     country  year
19    Brazil  2023
26    Brazil  2001
66    Brazil  2023
82    Brazil  2005
85    Brazil  2020
...      ...   ...
1141  Brazil  1989
1148  Brazil  2017
1151  Brazil  1997
1152  Brazil  2006
1177  Brazil  2019

[117 rows x 2 columns]

In [52]:
# Recap on creating columns

climate_df["temperature_range"] = climate_df["max_temperature"] - climate_df["min_temperature"]
climate_df

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,temperature_range
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,...,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69,32.71
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,...,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10,32.69
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,...,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74,40.49
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,...,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59,30.49
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,...,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77,30.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,...,1.96,3,19.13,2.38,21.56,22.78,112,1.91,25.39,46.36
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,...,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97,23.87
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,...,3.99,13,19.46,2.76,64.51,12.09,103,1.40,83.67,28.04
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,...,0.47,4,33.91,1.78,54.68,46.40,91,2.92,6.43,32.89
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,...,0.91,12,66.56,0.48,62.18,7.55,102,1.64,88.74,36.32

### Renaming Columns

In [53]:
climate_df

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,temperature_range
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,...,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69,32.71
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,...,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10,32.69
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,...,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74,40.49
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,...,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59,30.49
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,...,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77,30.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,...,1.96,3,19.13,2.38,21.56,22.78,112,1.91,25.39,46.36
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,...,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97,23.87
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,...,3.99,13,19.46,2.76,64.51,12.09,103,1.40,83.67,28.04
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,...,0.47,4,33.91,1.78,54.68,46.40,91,2.92,6.43,32.89
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,...,0.91,12,66.56,0.48,62.18,7.55,102,1.64,88.74,36.32

In [54]:
climate_df = climate_df.rename(columns={"temperature_range": "difference_in_temp"})
climate_df

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,difference_in_temp
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,...,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69,32.71
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,...,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10,32.69
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,...,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74,40.49
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,...,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59,30.49
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,...,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77,30.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,...,1.96,3,19.13,2.38,21.56,22.78,112,1.91,25.39,46.36
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,...,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97,23.87
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,...,3.99,13,19.46,2.76,64.51,12.09,103,1.40,83.67,28.04
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,...,0.47,4,33.91,1.78,54.68,46.40,91,2.92,6.43,32.89
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,...,0.91,12,66.56,0.48,62.18,7.55,102,1.64,88.74,36.32

#### Dropping Columns

In [55]:
climate_df.drop(columns = ["difference_in_temp"])

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,37,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,44,1.96,3,19.13,2.38,21.56,22.78,112,1.91,25.39
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,54,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,5,3.99,13,19.46,2.76,64.51,12.09,103,1.40,83.67
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,41,0.47,4,33.91,1.78,54.68,46.40,91,2.92,6.43
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,9,0.91,12,66.56,0.48,62.18,7.55,102,1.64,88.74

| Task           | Parameter    |
| -------------- | ------------ |
| Rename columns | `columns={}` |
| Rename rows    | `index={}`   |
| Drop columns   | `columns=[]` |
| Drop rows      | `index=[]`   |

## Duplicate Data

In [56]:
# Check for duplicates
climate_df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1195    False
1196    False
1197    False
1198    False
1199    False
Length: 1200, dtype: bool

In [57]:
# Count duplicate rows
climate_df.duplicated().sum()

np.int64(0)

In [58]:
temp_avg_year_country.duplicated().sum()

np.int64(0)

In [59]:
# View duplicate rows
climate_df[climate_df.duplicated()]

Empty DataFrame
Columns: [year, country, global_avg_temperature, temperature_anomaly, max_temperature, min_temperature, co2_concentration_ppm, annual_rainfall_mm, sea_level_rise_mm, sea_surface_temperature, heatwave_days, drought_index, flood_events_count, forest_cover_percent, deforestation_rate, fossil_fuel_consumption, renewable_energy_share, air_quality_index, predicted_temperature_2050, climate_risk_index, difference_in_temp]
Index: []

[0 rows x 21 columns]

In [60]:
# Check for duplicates in specific columns
climate_df.duplicated( subset=["country", "year"])

0       False
1       False
2       False
3       False
4       False
        ...
1195     True
1196     True
1197    False
1198     True
1199     True
Length: 1200, dtype: bool

In [61]:
# Removing duplicates
climate_df.drop_duplicates()

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,difference_in_temp
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,...,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69,32.71
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,...,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10,32.69
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,...,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74,40.49
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,...,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59,30.49
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,...,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77,30.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,...,1.96,3,19.13,2.38,21.56,22.78,112,1.91,25.39,46.36
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,...,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97,23.87
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,...,3.99,13,19.46,2.76,64.51,12.09,103,1.40,83.67,28.04
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,...,0.47,4,33.91,1.78,54.68,46.40,91,2.92,6.43,32.89
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,...,0.91,12,66.56,0.48,62.18,7.55,102,1.64,88.74,36.32

In [62]:
climate_df.drop_duplicates(
    subset=["country", "year"]
)

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,difference_in_temp
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,...,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69,32.71
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,...,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10,32.69
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,...,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74,40.49
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,...,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59,30.49
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,...,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77,30.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1151,1997,Brazil,15.00,0.57,38.35,5.43,403.40,569.56,3.95,12.78,...,1.91,9,69.32,0.21,82.68,59.51,127,2.31,30.91,32.92
1153,2013,USA,14.58,0.43,35.99,8.56,414.57,1267.84,3.44,16.84,...,1.39,9,34.03,0.96,88.12,46.33,90,2.44,55.87,27.43
1166,2001,USA,14.33,0.74,40.17,5.78,451.25,820.78,2.29,17.12,...,2.49,3,42.58,1.47,66.27,43.65,97,2.64,16.10,34.39
1168,2007,France,14.80,1.29,31.37,2.09,393.09,1377.75,4.30,16.15,...,3.44,11,48.90,2.73,24.91,9.98,112,1.68,97.09,29.28
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,...,3.99,13,19.46,2.76,64.51,12.09,103,1.40,83.67,28.04

## Data Cleaning Recap

### Data Cleaning Challenge

You have just received a new climate dataset from another research organization.

Before making **any modifications**, perform an initial inspection of the dataset to understand:

- its size,
- its structure,
- the data types,
- and the statistical summary of its numerical columns.

In [63]:
climate_df.shape

(1200, 21)

In [64]:
climate_df.columns

Index(['year', 'country', 'global_avg_temperature', 'temperature_anomaly',
       'max_temperature', 'min_temperature', 'co2_concentration_ppm',
       'annual_rainfall_mm', 'sea_level_rise_mm', 'sea_surface_temperature',
       'heatwave_days', 'drought_index', 'flood_events_count',
       'forest_cover_percent', 'deforestation_rate', 'fossil_fuel_consumption',
       'renewable_energy_share', 'air_quality_index',
       'predicted_temperature_2050', 'climate_risk_index',
       'difference_in_temp'],
      dtype='str')

In [65]:
climate_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   year                        1200 non-null   int64
 1   country                     1200 non-null   str
 2   global_avg_temperature      1200 non-null   float64
 3   temperature_anomaly         1200 non-null   float64
 4   max_temperature             1200 non-null   float64
 5   min_temperature             1200 non-null   float64
 6   co2_concentration_ppm       1200 non-null   float64
 7   annual_rainfall_mm          1200 non-null   float64
 8   sea_level_rise_mm           1200 non-null   float64
 9   sea_surface_temperature     1200 non-null   float64
 10  heatwave_days               1200 non-null   int64
 11  drought_index               1200 non-null   float64
 12  flood_events_count          1200 non-null   int64
 13  forest_cover_percent        1200 non-null   float64
 14  deforestation_rate          1200 non-null   float64
 15  fossil_fuel_consumption     1200 non-null   float64
 16  renewable_energy_share      1200 non-null   float64
 17  air_quality_index           1200 non-null   int64
 18  predicted_temperature_2050  1200 non-null   float64
 19  climate_risk_index          1200 non-null   float64
 20  difference_in_temp          1200 non-null   float64
dtypes: float64(16), int64(4), str(1)
memory usage: 197.0 KB

In [66]:
climate_df.describe().T

,count,mean,std,min,25%,50%,75%,max
year,1200.0,2002.452500,13.101493,1980.00,1991.0000,2003.000,2014.0000,2025.00
global_avg_temperature,1200.0,14.492850,0.594588,12.42,14.0800,14.510,14.9100,16.14
temperature_anomaly,1200.0,1.095058,0.392627,-0.23,0.8300,1.090,1.3700,2.32
max_temperature,1200.0,34.999692,4.915909,18.62,31.7300,34.715,38.2675,50.07
min_temperature,1200.0,4.775192,4.175590,-9.33,2.0075,4.850,7.5725,17.96
co2_concentration_ppm,1200.0,414.828717,25.528395,331.31,397.5925,414.625,432.1800,489.48
annual_rainfall_mm,1200.0,993.087992,309.935917,35.18,789.0900,998.040,1204.3875,2019.44
sea_level_rise_mm,1200.0,3.490333,1.190501,-0.27,2.6800,3.470,4.3000,7.75
sea_surface_temperature,1200.0,16.472383,1.470498,11.32,15.4575,16.460,17.4400,20.88
heatwave_days,1200.0,29.941667,17.266636,0.00,15.0000,31.000,45.0000,59.00
drought_index,1200.0,2.533758,1.416269,0.02,1.3575,2.495,3.6925,4.99
flood_events_count,1200.0,6.868333,4.271167,0.00,3.0000,7.000,11.0000,14.00
forest_cover_percent,1200.0,39.162892,17.072966,10.03,24.1050,39.345,53.4000,69.92
deforestation_rate,1200.0,1.774992,0.992647,0.10,0.9075,1.770,2.6425,3.50
fossil_fuel_consumption,1200.0,54.906158,20.238368,20.02,37.2650,54.965,72.0025,89.96
renewable_energy_share,1200.0,32.503275,16.002972,5.05,18.9975,32.405,46.8925,59.96
air_quality_index,1200.0,120.682500,47.400904,40.00,78.0000,123.000,164.0000,199.00
predicted_temperature_2050,1200.0,2.219142,0.486207,0.43,1.8900,2.210,2.5500,3.77
climate_risk_index,1200.0,49.612400,28.465540,0.11,25.0450,49.960,72.7950,99.95
difference_in_temp,1200.0,30.224500,6.656903,2.93,25.7750,30.125,34.7250,50.72

### Missing Values

In [67]:
# Detect Missing Values
temp_avg_year_country.isna()

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Brazil,False,False,False,False,True,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
Canada,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
China,False,False,False,False,False,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,True
France,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Germany,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
India,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
Pakistan,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
UK,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
USA,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,False,False,False,False,False

In [68]:
# Count missing values
temp_avg_year_country.isna().sum(axis=1)

country
Australia    3
Brazil       5
Canada       2
China        5
France       0
Germany      3
India        3
Pakistan     4
UK           2
USA          3
dtype: int64

In [69]:
temp_avg_year_country.isna().sum()

year
1980    0
1981    1
1982    1
1983    0
1984    1
1985    0
1986    2
1987    0
1988    1
1989    0
1990    0
1991    1
1992    1
1993    1
1994    0
1995    2
1996    0
1997    1
1998    0
1999    0
2000    1
2001    2
2002    0
2003    2
2004    2
2005    0
2006    0
2007    0
2008    1
2009    0
2010    1
2011    1
2012    0
2013    1
2014    0
2015    1
2016    0
2017    1
2018    1
2019    0
2020    1
2021    1
2022    0
2023    1
2024    0
2025    1
dtype: int64

In [70]:
# Total Missing Values
temp_avg_year_country.isna().sum().sum()

np.int64(30)

In [71]:
# Check percentage of missing values to determine if they are relevant
(temp_avg_year_country.isna().sum()/len(temp_avg_year_country)) * 100

year
1980     0.0
1981    10.0
1982    10.0
1983     0.0
1984    10.0
1985     0.0
1986    20.0
1987     0.0
1988    10.0
1989     0.0
1990     0.0
1991    10.0
1992    10.0
1993    10.0
1994     0.0
1995    20.0
1996     0.0
1997    10.0
1998     0.0
1999     0.0
2000    10.0
2001    20.0
2002     0.0
2003    20.0
2004    20.0
2005     0.0
2006     0.0
2007     0.0
2008    10.0
2009     0.0
2010    10.0
2011    10.0
2012     0.0
2013    10.0
2014     0.0
2015    10.0
2016     0.0
2017    10.0
2018    10.0
2019     0.0
2020    10.0
2021    10.0
2022     0.0
2023    10.0
2024     0.0
2025    10.0
dtype: float64

In [72]:
temp_avg_year_country.shape

(10, 46)

In [73]:
# Filling the missing values using the medina
temp_avg_year_country.median()

year
1980    14.507500
1981    14.557500
1982    14.330000
1983    14.172917
1984    14.655000
1985    14.496667
1986    14.535000
1987    14.445833
1988    14.585000
1989    14.500000
1990    14.307500
1991    14.290000
1992    14.375000
1993    14.734286
1994    14.553250
1995    14.440833
1996    14.770000
1997    14.616667
1998    14.682500
1999    14.260417
2000    14.475000
2001    14.394500
2002    14.420000
2003    14.663333
2004    14.692500
2005    14.464167
2006    14.529167
2007    14.505833
2008    14.473333
2009    14.442083
2010    14.850000
2011    14.506667
2012    14.639000
2013    14.380000
2014    14.427500
2015    14.810000
2016    14.333036
2017    14.483333
2018    14.550000
2019    14.585000
2020    14.900000
2021    14.610000
2022    14.182500
2023    14.364000
2024    14.510000
2025    14.290000
dtype: float64

In [74]:
temp_avg_year_country_median = temp_avg_year_country.fillna(temp_avg_year_country.median())
temp_avg_year_country_median

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,14.655000,14.755000,14.535000,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,14.610000,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,14.535000,15.323333,14.585000,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,14.290000
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,14.330000,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,14.900000,14.970000,15.090000,14.3640,14.740000,14.235000
Pakistan,14.18000,14.557500,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,14.483333,14.550000,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [75]:
temp_avg_year_country_median.isna().sum()

year
1980    0
1981    0
1982    0
1983    0
1984    0
1985    0
1986    0
1987    0
1988    0
1989    0
1990    0
1991    0
1992    0
1993    0
1994    0
1995    0
1996    0
1997    0
1998    0
1999    0
2000    0
2001    0
2002    0
2003    0
2004    0
2005    0
2006    0
2007    0
2008    0
2009    0
2010    0
2011    0
2012    0
2013    0
2014    0
2015    0
2016    0
2017    0
2018    0
2019    0
2020    0
2021    0
2022    0
2023    0
2024    0
2025    0
dtype: int64

In [76]:
temp_avg_year_country.mode()

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,14.04500,14.202500,14.020000,14.495,13.830000,14.130000,14.105000,13.520000,14.140000,13.653333,...,13.590000,13.730000,13.335000,13.873333,14.216667,14.140000,13.606667,13.8100,14.41,13.280000
1,14.18000,14.306000,14.037500,NaN,14.050000,14.155000,14.360000,14.130000,14.160000,13.695000,...,13.706667,14.226667,13.880000,13.963333,14.240000,14.320000,13.610000,13.9525,NaN,14.000000
2,14.18250,14.490000,14.236667,NaN,14.325714,14.320000,14.365000,14.283333,14.400000,14.430000,...,14.083333,14.345000,13.983333,14.295000,14.545000,14.370000,13.810000,14.0700,NaN,14.020000
3,14.42625,14.506667,14.237500,NaN,14.560000,14.456667,14.420000,14.336000,14.406667,14.460000,...,14.185000,14.350000,14.510000,14.360000,14.586667,14.600000,14.090000,14.2250,NaN,14.235000
4,14.43500,14.557500,14.330000,NaN,14.655000,14.493333,14.650000,14.356667,14.585000,14.480000,...,14.317500,14.483333,14.550000,14.550000,14.900000,14.610000,14.165000,14.3640,NaN,14.290000
5,14.58000,14.595000,14.630000,NaN,14.710000,14.500000,14.683333,14.535000,14.605000,14.520000,...,14.348571,14.694000,14.653333,14.620000,14.950000,14.740000,14.200000,14.5275,NaN,14.650000
6,14.71000,14.746667,14.640000,NaN,14.814000,14.613333,14.705000,14.536667,14.620000,14.633333,...,14.630000,14.845000,14.670000,14.680000,15.130000,14.756667,14.360000,14.7300,NaN,14.676667
7,14.73250,14.883333,14.650000,NaN,15.190000,14.755000,14.755000,14.700000,14.755000,14.660000,...,14.845000,14.920000,14.860000,14.730000,15.470000,14.807500,14.530000,14.9300,NaN,14.820000
8,14.82000,15.420000,14.750000,NaN,15.230000,14.772500,NaN,14.855000,14.806667,14.820000,...,14.916667,15.170000,15.025000,14.938000,15.690000,14.970000,15.090000,15.5800,NaN,15.350000
9,14.83500,NaN,NaN,NaN,NaN,14.776667,NaN,15.323333,NaN,14.900000,...,15.060000,NaN,NaN,15.086667,NaN,NaN,15.290000,NaN,NaN,NaN

In [77]:
# Filling missing values using the mode
temp_avg_year_country_mode = temp_avg_year_country.fillna(temp_avg_year_country.mode())
temp_avg_year_country_mode

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [78]:
temp_avg_year_country

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [79]:
# Filling using forward fill

temp_avg_year_country_ffill = temp_avg_year_country.ffill(axis = 1)
temp_avg_year_country_ffill

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,13.760000,14.755000,14.755000,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,15.130000,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,14.613333,15.323333,15.323333,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,14.202000
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,14.490000,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,15.086667,14.970000,15.090000,15.0900,14.740000,14.235000
Pakistan,14.18000,14.180000,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,13.706667,13.706667,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [80]:
# Backward fill
temp_avg_year_country_bfill = temp_avg_year_country.bfill(axis = 1)
temp_avg_year_country_bfill

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,14.755000,14.755000,14.536667,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,14.200000,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,15.323333,15.323333,14.633333,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,14.495000,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,14.970000,14.970000,15.090000,14.7400,14.740000,14.235000
Pakistan,14.18000,14.630000,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,14.620000,14.620000,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [81]:
# Interpolation

temp_avg_year_country

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [82]:
temp_avg_year_country_interp = temp_avg_year_country.interpolate(axis=1)
temp_avg_year_country_interp

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,14.257500,14.755000,14.645833,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,14.665000,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,14.968333,15.323333,14.978333,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,14.202000
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,14.492500,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,15.028333,14.970000,15.090000,14.9150,14.740000,14.235000
Pakistan,14.18000,14.405000,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,14.011111,14.315556,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

### Choosing the right filling method

| Method        | Best for                          | Example                         |
| ------------- | --------------------------------- | ------------------------------- |
| Constant      | Placeholder values                | Replace with 0 or "Unknown"     |
| Mean          | Normally distributed numeric data | Height, temperature             |
| Median        | Numeric data with outliers        | Income, house prices            |
| Mode          | Categorical data                  | Country, gender, weather type   |
| Forward fill  | Time series                       | Sensor readings, stock prices   |
| Backward fill | Time series                       | Missing values at the beginning |
| Interpolation | Continuous time series            | Temperature, rainfall           |

## Data Cleaning Summary


### 1. Missing Values

- Detecting missing values
- Counting missing values
- Calculating the percentage of missing values
- `dropna()`
  - `axis`
  - `how`
  - `subset`
- `fillna()`
- Filling with a constant value
- Mean imputation
- Median imputation
- Mode imputation
- Forward fill (`ffill`)
- Backward fill (`bfill`)
- Interpolation (`interpolate()`)
- How to choose the appropriate imputation technique

---

### 2. Data Manipulation

- Creating new columns
- Renaming columns (`rename()`)
- Dropping columns (`drop()`)
- Dropping rows (`drop()`)
- Understanding `axis=0` vs `axis=1`

---

### 3. Boolean Filtering

- Single conditions
- Multiple conditions using `&`
- Multiple conditions using `|`
- Negation using `~`
- Filtering with `isin()`
- Filtering with `between()`
- Boolean indexing
- Sorting filtered results using `sort_values()`

---

### 4. Indexing and Selection

- Selecting columns
- Selecting rows
- `.loc[]`
- `.iloc[]`
- Boolean indexing with `.loc[]`
- Understanding labels vs positions

---

### 5. Dataset Inspection

- `shape`
- `info()`
- `describe()`
- `describe().T`
- `columns`
- Understanding missing value summaries

### Advanced Pandas Recap

Climate Challenge 1

For each country, calculate:

- Mean annual rainfall
- Minimum annual rainfall
- Maximum annual rainfall

In [83]:
climate_df.groupby(["country"])["global_avg_temperature"].agg(["mean", "min", "max"])

                mean    min    max
country
Australia  14.423590  12.42  16.13
Brazil     14.501368  12.92  15.81
Canada     14.476897  12.84  15.83
China      14.542681  13.14  15.90
France     14.508525  13.06  16.08
Germany    14.545000  13.39  16.14
India      14.469487  13.11  15.95
Pakistan   14.446053  12.80  15.69
UK         14.548189  13.10  15.83
USA        14.452712  13.20  15.58

In [84]:
climate_df.columns

Index(['year', 'country', 'global_avg_temperature', 'temperature_anomaly',
       'max_temperature', 'min_temperature', 'co2_concentration_ppm',
       'annual_rainfall_mm', 'sea_level_rise_mm', 'sea_surface_temperature',
       'heatwave_days', 'drought_index', 'flood_events_count',
       'forest_cover_percent', 'deforestation_rate', 'fossil_fuel_consumption',
       'renewable_energy_share', 'air_quality_index',
       'predicted_temperature_2050', 'climate_risk_index',
       'difference_in_temp'],
      dtype='str')

In [85]:
climate_df.groupby([ "country", "temperature_anomaly"])["global_avg_temperature"].agg(["mean", "min", "max"])

                                    mean    min    max
country   temperature_anomaly
Australia -0.23                13.740000  13.74  13.74
           0.03                14.970000  14.97  14.97
           0.04                14.060000  14.06  14.06
           0.10                14.330000  14.33  14.33
           0.21                14.130000  14.13  14.13
...                                  ...    ...    ...
USA        1.71                14.360000  14.36  14.36
           1.72                14.080000  14.08  14.08
           1.75                14.756667  14.23  15.52
           1.79                13.850000  13.67  14.03
           1.93                14.650000  14.65  14.65

[795 rows x 3 columns]

In [86]:
climate_df.groupby("country")[["global_avg_temperature", "annual_rainfall_mm"]].agg(["mean", "min", "max"])

          global_avg_temperature               annual_rainfall_mm          \
                            mean    min    max               mean     min
country
Australia              14.423590  12.42  16.13        1027.148718   65.00
Brazil                 14.501368  12.92  15.81         946.186752  350.86
Canada                 14.476897  12.84  15.83        1014.297931   35.18
China                  14.542681  13.14  15.90         997.718986  219.83
France                 14.508525  13.06  16.08         990.668525   90.64
Germany                14.545000  13.39  16.14         984.862632  161.47
India                  14.469487  13.11  15.95        1000.260085  148.35
Pakistan               14.446053  12.80  15.69         996.769298  321.06
UK                     14.548189  13.10  15.83         954.305118  163.24
USA                    14.452712  13.20  15.58        1021.074407  190.20


               max
country
Australia  1796.12
Brazil     1804.15
Canada     2019.44
China      1895.90
France     1781.25
Germany    1721.84
India      1693.38
Pakistan   1982.92
UK         1760.00
USA        1789.18

In [87]:
# Name aggregation
climate_df.groupby("country").agg(
    avg_temp=("global_avg_temperature", "mean"),
    max_rain=("annual_rainfall_mm", "max"),
    min_temp=("global_avg_temperature", "min")
)

            avg_temp  max_rain  min_temp
country
Australia  14.423590   1796.12     12.42
Brazil     14.501368   1804.15     12.92
Canada     14.476897   2019.44     12.84
China      14.542681   1895.90     13.14
France     14.508525   1781.25     13.06
Germany    14.545000   1721.84     13.39
India      14.469487   1693.38     13.11
Pakistan   14.446053   1982.92     12.80
UK         14.548189   1760.00     13.10
USA        14.452712   1789.18     13.20

In [88]:
# Using Transform instead of .agg()

climate_df.groupby("country")["global_avg_temperature"].transform("mean")

0       14.545000
1       14.469487
2       14.446053
3       14.452712
4       14.423590
          ...
1195    14.469487
1196    14.476897
1197    14.548189
1198    14.548189
1199    14.545000
Name: global_avg_temperature, Length: 1200, dtype: float64

In [89]:
climate_df["country_avg_rainfall"] = climate_df.groupby(["country"])["annual_rainfall_mm"].transform("mean")
climate_df

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,difference_in_temp,country_avg_rainfall
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,...,11,64.33,1.26,28.14,42.30,148,3.30,23.69,32.71,984.862632
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,...,11,42.69,0.62,86.40,53.65,50,2.63,70.10,32.69,1000.260085
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,...,1,65.47,2.08,34.95,47.20,107,1.33,34.74,40.49,996.769298
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,...,6,44.34,2.15,77.11,36.65,129,2.51,45.59,30.49,1021.074407
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,...,4,14.18,0.76,37.27,50.35,149,2.87,55.77,30.61,1027.148718
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,...,3,19.13,2.38,21.56,22.78,112,1.91,25.39,46.36,1000.260085
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,...,4,40.94,1.77,74.75,20.81,96,2.71,4.97,23.87,1014.297931
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,...,13,19.46,2.76,64.51,12.09,103,1.40,83.67,28.04,954.305118
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,...,4,33.91,1.78,54.68,46.40,91,2.92,6.43,32.89,954.305118
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,...,12,66.56,0.48,62.18,7.55,102,1.64,88.74,36.32,984.862632

# Recap on .loc[] and .iloc[]

In [90]:

df = pd.DataFrame({
    'temp': [25, 31, -4, 18],
    'rain': [120, 300, 80, 150]
}, index=['Kenya', 'Brazil', 'Canada', 'Japan'])
df

        temp  rain
Kenya     25   120
Brazil    31   300
Canada    -4    80
Japan     18   150

In [91]:
# Selecting single values
df.loc["Kenya", "temp"]

np.int64(25)

In [92]:
# Grab specific rows and columns
df.loc[["Kenya", "Japan"], ["temp", "rain"]]

       temp  rain
Kenya    25   120
Japan    18   150

In [93]:
# Get all columns for rows where temp > 20
df["temp"]> 20

Kenya      True
Brazil     True
Canada    False
Japan     False
Name: temp, dtype: bool

In [94]:
# Returns a 1D Series (looks like a single list with an index)
df.loc[df["temp"] > 20, "rain"]

Kenya     120
Brazil    300
Name: rain, dtype: int64

In [95]:
# Returns a 2D DataFrame (looks like a full table with column headers)
df.loc[df["temp"] > 20, ["rain"]]

        rain
Kenya    120
Brazil   300

In [96]:
# Set rainfall to 0 for Canada
df.loc['Canada', 'rain'] = 0
df

        temp  rain
Kenya     25   120
Brazil    31   300
Canada    -4     0
Japan     18   150

In [97]:
# Flag warm countries in a new column
df.loc[df['temp'] > 20, 'climate'] = 'Warm'
df

        temp  rain climate
Kenya     25   120    Warm
Brazil    31   300    Warm
Canada    -4     0     NaN
Japan     18   150     NaN

Write a single line using .loc[] that updates temp to 0 for all countries where rain is strictly less than 100.

In [98]:
df.loc[df["rain"]< 100, "temp"] = 0
df

        temp  rain climate
Kenya     25   120    Warm
Brazil    31   300    Warm
Canada     0     0     NaN
Japan     18   150     NaN

Write a single line using .loc[] to retrieve a DataFrame (2D table output) containing only the rain column for Brazil and Japan.

In [99]:
df.loc[["Brazil", "Japan"], ["rain"]]

        rain
Brazil   300
Japan    150

Write a single line using .loc[] to retrieve all columns for countries where rain is greater than 100 AND temp is greater than 20.

In [100]:
df.loc[(df["rain"]> 100) & (df["temp"] > 20)]

        temp  rain climate
Kenya     25   120    Warm
Brazil    31   300    Warm

In [101]:
import pandas as pd

df = pd.DataFrame({
    'rain': [120, 300, 80, 150],
    'temp': [25, 31, -4, 18]
}, index=['Kenya', 'Brazil', 'Canada', 'Japan'])
df

        rain  temp
Kenya    120    25
Brazil   300    31
Canada    80    -4
Japan    150    18

### Modifying Values Based on Index Slicing
Write a single line using .loc[] and label slicing ("Start":"End") to select the temp column for all countries from Brazil through Japan (inclusive).

In [102]:
df.loc["Brazil": "Japan", ["temp"]]

        temp
Brazil    31
Canada    -4
Japan     18

In [103]:
df.loc["Brazil", "temp"]

np.int64(31)

In [104]:
df.loc["Brazil", ["temp"]]

temp    31
Name: Brazil, dtype: int64

In [105]:
df.loc[["Brazil"], ["temp"]]

        temp
Brazil    31

Write a single line using .loc[] to double the rain value (multiply by 2) for any country where temp is negative (< 0) OR rain is greater than 200.

In [106]:
df.loc[(df["temp"] < 0) | (df["rain"]> 200), ["rain"]] = df["rain"] * 2
df

        rain  temp
Kenya    120    25
Brazil   600    31
Canada   160    -4
Japan    150    18

###  Mastery of Lambda

In [107]:
# syntax: lambda ARGUMENTS: EXPRESSION
lambda x: x * 2

# Format: VALUE_IF_TRUE if CONDITION else VALUE_IF_FALSE
lambda x: "Pass" if x >= 50 else "Fail"

In [108]:
import pandas as pd

# Create the sample DataFrame
df = pd.DataFrame({
    "country": ["Brazil", "Canada", "Kenya", "Japan"],
    "temp": [31, -10, 25, 18],
    "rain": [300, 80, 150, 220]
})

df

  country  temp  rain
0  Brazil    31   300
1  Canada   -10    80
2   Kenya    25   150
3   Japan    18   220

Suppose we have a df["rain"] column containing numbers (e.g., 50, 150, 300).

Write a line of code using .apply() and a lambda to create a new column called "rain_category":

If rain is greater than 200, set it to "Heavy"

Otherwise, set it to "Light"

In [109]:
df["rain_category"] = df["rain"].apply(lambda x: "Heavy" if x > 200 else "Light")
df

  country  temp  rain rain_category
0  Brazil    31   300         Heavy
1  Canada   -10    80         Light
2   Kenya    25   150         Light
3   Japan    18   220         Heavy

What if you have three categories instead of two?

You can chain if/else statements inside a lambda like this:VALUE_1 if CONDITION_1 else (VALUE_2 if CONDITION_2 else VALUE_3)

Try creating a column called "temp_feel" based on df["temp"]:If temp is less than 0 $\rightarrow$ "Freezing"

If temp is between 0 and 25 (inclusive) $\rightarrow$ "Mild"

Otherwise $\rightarrow$ "Hot"

How would you write that .apply() with lambda

In [110]:
df["temp_feel"] = df["temp"].apply( lambda t: "Freezing" if t < 0 else ("Mild" if t <= 25 else "Hot"))
df

  country  temp  rain rain_category temp_feel
0  Brazil    31   300         Heavy       Hot
1  Canada   -10    80         Light  Freezing
2   Kenya    25   150         Light      Mild
3   Japan    18   220         Heavy      Mild

Write a line using df.apply(..., axis=1) to create a column "vacation_spot":

If temp is greater than 20 AND rain is less than 200 $\rightarrow$ "Ideal"

Otherwise $\rightarrow$ "Skip"

In [111]:
df["vacation_spot"] = df.apply(lambda v: "Ideal" if (v["temp" ]> 20) and (v["rain"] < 200) else "Skip", axis = 1)
df

  country  temp  rain rain_category temp_feel vacation_spot
0  Brazil    31   300         Heavy       Hot          Skip
1  Canada   -10    80         Light  Freezing          Skip
2   Kenya    25   150         Light      Mild         Ideal
3   Japan    18   220         Heavy      Mild          Skip

### .Groupby().filter() Recap

In [112]:
import pandas as pd

data = {
    "customer_id": [101, 101, 101, 102, 102, 103, 103, 103],
    "item": ["Phone", "Case", "Charger", "Laptop", "Mouse", "TV", "Cable", "Stand"],
    "amount": [800, 20, 25, 1200, 30, 1500, 15, 45]
}

orders = pd.DataFrame(data)
orders

   customer_id     item  amount
0          101    Phone     800
1          101     Case      20
2          101  Charger      25
3          102   Laptop    1200
4          102    Mouse      30
5          103       TV    1500
6          103    Cable      15
7          103    Stand      45

Write a groupby().filter() expression to find all orders for customers whose total spending across all their purchases combined is greater than $1,000.

If a customer spent $1,000 or less in total, all of their orders should be dropped.

In [113]:
higher_total_spending = orders.groupby(["customer_id"]).filter(lambda x: x["amount"].sum() > 1000)
higher_total_spending

   customer_id    item  amount
3          102  Laptop    1200
4          102   Mouse      30
5          103      TV    1500
6          103   Cable      15
7          103   Stand      45

In [114]:
orders.groupby("customer_id").apply(lambda x: x["amount"].sum() > 1000)

customer_id
101    False
102     True
103     True
dtype: bool

In [115]:
# Boolean Filtering
climate_df[climate_df["global_avg_temperature"] > 14]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,difference_in_temp,country_avg_rainfall
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,...,11,64.33,1.26,28.14,42.30,148,3.30,23.69,32.71,984.862632
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,...,11,42.69,0.62,86.40,53.65,50,2.63,70.10,32.69,1000.260085
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,...,1,65.47,2.08,34.95,47.20,107,1.33,34.74,40.49,996.769298
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,...,6,44.34,2.15,77.11,36.65,129,2.51,45.59,30.49,1021.074407
5,2000,France,14.20,1.68,27.62,10.17,342.89,1178.57,2.31,16.28,...,9,43.17,0.77,50.15,59.28,172,1.17,68.62,17.45,990.668525
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,...,3,19.13,2.38,21.56,22.78,112,1.91,25.39,46.36,1000.260085
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,...,4,40.94,1.77,74.75,20.81,96,2.71,4.97,23.87,1014.297931
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,...,13,19.46,2.76,64.51,12.09,103,1.40,83.67,28.04,954.305118
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,...,4,33.91,1.78,54.68,46.40,91,2.92,6.43,32.89,954.305118
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,...,12,66.56,0.48,62.18,7.55,102,1.64,88.74,36.32,984.862632

In [116]:
# Groupby filter()

climate_df.groupby("country").filter(
    lambda x: x["global_avg_temperature"].sum() > 14.5
).sort_values("country").head(20)

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,difference_in_temp,country_avg_rainfall
469,2013,Australia,13.77,1.07,38.42,-0.16,419.36,1390.30,4.50,16.68,...,0,41.63,2.03,37.25,33.64,190,1.68,38.66,38.58,1027.148718
397,2021,Australia,14.15,0.58,35.12,4.00,432.18,602.92,3.32,17.63,...,9,45.16,2.52,48.99,10.77,192,2.81,38.64,31.12,1027.148718
395,2001,Australia,14.50,1.07,35.73,-0.91,395.25,1036.77,3.55,13.98,...,10,20.20,1.77,68.52,43.25,108,2.04,52.22,36.64,1027.148718
216,1990,Australia,14.28,0.58,36.40,3.38,399.28,995.70,5.31,15.98,...,0,31.39,0.34,75.21,27.89,127,3.20,40.90,33.02,1027.148718
516,2013,Australia,14.40,0.85,35.85,2.52,388.40,1207.08,3.45,17.41,...,9,49.42,2.07,57.10,10.15,126,3.26,16.21,33.33,1027.148718
770,2018,Australia,14.38,1.02,43.88,1.86,434.25,1029.84,3.06,15.81,...,7,14.81,0.62,43.19,55.24,76,2.20,79.54,42.02,1027.148718
227,1988,Australia,14.80,0.70,34.85,1.52,400.11,728.26,1.63,18.11,...,6,64.04,1.39,83.87,45.37,112,2.11,5.57,33.33,1027.148718
232,1999,Australia,14.72,1.26,35.96,1.81,374.13,1194.19,5.20,14.65,...,13,56.67,2.71,62.02,49.73,54,1.44,45.03,34.15,1027.148718
538,2002,Australia,14.49,1.03,43.59,2.96,412.02,1017.97,2.78,16.31,...,10,55.60,2.74,65.28,10.23,107,1.54,29.03,40.63,1027.148718
369,2008,Australia,13.83,1.93,48.19,2.13,402.42,726.55,3.35,17.51,...,12,43.65,3.16,78.44,51.52,129,1.85,16.18,46.06,1027.148718
367,2022,Australia,14.64,0.83,39.68,1.74,404.78,1521.52,3.68,14.40,...,9,44.01,1.52,40.06,56.06,49,2.61,45.22,37.94,1027.148718
364,2019,Australia,15.38,0.69,28.46,7.57,398.70,1461.71,2.16,18.14,...,7,43.44,2.71,36.39,42.89,98,2.23,61.53,20.89,1027.148718
362,2005,Australia,13.41,1.17,34.51,-4.70,386.22,963.54,4.50,15.64,...,0,53.02,2.80,34.76,7.16,159,2.56,59.28,39.21,1027.148718
547,2009,Australia,13.05,0.64,31.14,2.04,402.62,855.20,2.16,17.31,...,13,65.82,2.56,67.12,49.72,117,2.44,15.24,29.10,1027.148718
548,1996,Australia,16.13,1.31,32.50,9.22,402.82,786.50,3.20,17.84,...,3,43.26,2.92,22.86,47.17,118,1.61,41.10,23.28,1027.148718
237,1998,Australia,14.38,0.83,26.84,10.83,385.51,1389.75,2.73,17.66,...,1,21.84,0.72,64.99,55.77,65,2.66,1.70,16.01,1027.148718
361,1981,Australia,16.11,1.30,39.91,3.69,420.52,573.56,4.10,16.49,...,11,40.58,2.61,45.79,45.29,103,1.60,57.08,36.22,1027.148718
1115,1987,Australia,14.86,0.94,39.05,1.91,400.08,1341.78,3.14,18.95,...,4,59.08,0.58,86.34,36.37,160,2.55,71.99,37.14,1027.148718
357,2002,Australia,15.20,1.42,34.69,3.83,402.23,579.54,3.47,17.40,...,10,62.81,0.76,67.83,30.48,43,1.95,9.62,30.86,1027.148718
912,2000,Australia,13.07,2.13,37.03,4.54,373.45,1432.99,2.73,16.70,...,11,36.82,0.42,80.08,21.75,54,1.72,85.08,32.49,1027.148718

In [117]:
climate_df.groupby("country").filter(lambda x: len(x) > 130)

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,difference_in_temp,country_avg_rainfall
11,2003,China,14.52,0.61,29.46,6.14,439.12,928.97,1.38,14.85,...,13,25.58,1.10,59.61,28.74,60,2.38,66.48,23.32,997.718986
15,1982,China,14.86,0.70,29.58,5.52,447.11,327.43,5.26,17.16,...,5,17.36,0.42,41.55,32.44,85,2.07,16.48,24.06,997.718986
32,1995,China,14.68,0.53,29.45,7.03,427.63,631.38,1.36,16.23,...,0,68.42,2.51,73.39,58.76,110,1.75,14.57,22.42,997.718986
42,1983,China,14.70,1.39,37.36,1.50,433.97,1242.18,4.94,15.06,...,14,60.90,2.57,64.79,16.91,76,2.72,30.02,35.86,997.718986
52,1987,China,15.88,0.61,33.77,6.72,465.88,1120.25,1.86,16.44,...,14,34.17,1.36,56.21,25.27,107,1.77,66.93,27.05,997.718986
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1136,2019,China,14.30,1.02,33.55,3.55,411.23,1022.69,3.71,16.77,...,6,44.51,2.73,39.47,48.91,146,2.30,11.54,30.00,997.718986
1138,2000,China,14.76,1.10,28.04,10.16,417.19,1091.57,3.66,13.87,...,1,25.75,0.74,26.97,30.48,76,2.97,7.19,17.88,997.718986
1154,2006,China,14.72,1.47,37.40,-0.26,456.85,1529.94,2.12,19.05,...,11,12.58,3.32,74.35,48.52,78,1.84,24.01,37.66,997.718986
1157,2023,China,14.39,1.47,34.24,11.84,399.97,912.74,3.05,15.21,...,10,15.79,1.47,25.26,31.83,182,1.83,26.65,22.40,997.718986
1162,2003,China,14.45,0.73,33.37,13.95,448.11,739.77,1.59,18.83,...,9,62.69,2.14,69.93,46.35,121,1.21,87.12,19.42,997.718986

In [118]:
# Len(dataframe) returns number of rows
len(climate_df)

1200

In [119]:
# Transform

# Here, x is automatically the 'global_avg_temperature' Series!
mask = climate_df.groupby("country")["global_avg_temperature"].transform(lambda x: x.mean() > 14.5)

# Then filter the original DataFrame
climate_df[mask]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,difference_in_temp,country_avg_rainfall
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,...,11,64.33,1.26,28.14,42.30,148,3.30,23.69,32.71,984.862632
5,2000,France,14.20,1.68,27.62,10.17,342.89,1178.57,2.31,16.28,...,9,43.17,0.77,50.15,59.28,172,1.17,68.62,17.45,990.668525
6,2018,France,14.67,1.41,33.10,3.75,426.67,1422.19,1.48,15.78,...,5,44.54,3.46,65.85,21.51,71,2.67,23.87,29.35,990.668525
11,2003,China,14.52,0.61,29.46,6.14,439.12,928.97,1.38,14.85,...,13,25.58,1.10,59.61,28.74,60,2.38,66.48,23.32,997.718986
13,2019,France,15.58,1.47,41.60,5.09,393.12,485.46,2.85,16.87,...,13,24.46,3.09,50.52,47.71,81,2.42,15.75,36.51,990.668525
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1187,2008,UK,15.77,1.11,33.32,-0.48,418.64,526.29,4.68,16.40,...,7,11.06,3.06,86.35,14.11,108,2.10,45.38,33.80,954.305118
1193,1998,France,14.87,0.80,22.98,0.15,426.41,1124.27,4.46,17.03,...,10,49.31,2.69,86.25,44.31,193,2.06,37.61,22.83,990.668525
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,...,13,19.46,2.76,64.51,12.09,103,1.40,83.67,28.04,954.305118
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,...,4,33.91,1.78,54.68,46.40,91,2.92,6.43,32.89,954.305118
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,...,12,66.56,0.48,62.18,7.55,102,1.64,88.74,36.32,984.862632

In [120]:
# 1. Get average temp per country broadcasted across all rows
country_means = climate_df.groupby("country")["global_avg_temperature"].transform("mean")

# 2. Filter rows where that mean > 14.5
climate_df[country_means > 14.5]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,...,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index,difference_in_temp,country_avg_rainfall
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,...,11,64.33,1.26,28.14,42.30,148,3.30,23.69,32.71,984.862632
5,2000,France,14.20,1.68,27.62,10.17,342.89,1178.57,2.31,16.28,...,9,43.17,0.77,50.15,59.28,172,1.17,68.62,17.45,990.668525
6,2018,France,14.67,1.41,33.10,3.75,426.67,1422.19,1.48,15.78,...,5,44.54,3.46,65.85,21.51,71,2.67,23.87,29.35,990.668525
11,2003,China,14.52,0.61,29.46,6.14,439.12,928.97,1.38,14.85,...,13,25.58,1.10,59.61,28.74,60,2.38,66.48,23.32,997.718986
13,2019,France,15.58,1.47,41.60,5.09,393.12,485.46,2.85,16.87,...,13,24.46,3.09,50.52,47.71,81,2.42,15.75,36.51,990.668525
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1187,2008,UK,15.77,1.11,33.32,-0.48,418.64,526.29,4.68,16.40,...,7,11.06,3.06,86.35,14.11,108,2.10,45.38,33.80,954.305118
1193,1998,France,14.87,0.80,22.98,0.15,426.41,1124.27,4.46,17.03,...,10,49.31,2.69,86.25,44.31,193,2.06,37.61,22.83,990.668525
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,...,13,19.46,2.76,64.51,12.09,103,1.40,83.67,28.04,954.305118
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,...,4,33.91,1.78,54.68,46.40,91,2.92,6.43,32.89,954.305118
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,...,12,66.56,0.48,62.18,7.55,102,1.64,88.74,36.32,984.862632

### Grouping and Aggregation Recap

Challenge 1

Using your climate_df, find the average, minimum, and maximum annual rainfall for each country.

In [121]:
climate_df.groupby("country").agg(
    average_rainfall = ("annual_rainfall_mm", "mean"),
    maximum_rainfall = ("annual_rainfall_mm", "max"),
    minimum_rainfall = ("annual_rainfall_mm", "min")
)

           average_rainfall  maximum_rainfall  minimum_rainfall
country
Australia       1027.148718           1796.12             65.00
Brazil           946.186752           1804.15            350.86
Canada          1014.297931           2019.44             35.18
China            997.718986           1895.90            219.83
France           990.668525           1781.25             90.64
Germany          984.862632           1721.84            161.47
India           1000.260085           1693.38            148.35
Pakistan         996.769298           1982.92            321.06
UK               954.305118           1760.00            163.24
USA             1021.074407           1789.18            190.20

Challenge 2 — Multiple columns

Using your climate_df, produce a summary for each country containing:

the mean and maximum of global_avg_temperature
the mean and minimum of annual_rainfall_mm

In [122]:
climate_df.groupby("country").agg(
    avg_global_avg_temp = ("global_avg_temperature", "mean"),
    max_g_avg_temp = ("global_avg_temperature", "max"),
    avg_rainfall = ("annual_rainfall_mm","mean"),
    min_rainfall = ("annual_rainfall_mm", "min")
)

           avg_global_avg_temp  max_g_avg_temp  avg_rainfall  min_rainfall
country
Australia            14.423590           16.13   1027.148718         65.00
Brazil               14.501368           15.81    946.186752        350.86
Canada               14.476897           15.83   1014.297931         35.18
China                14.542681           15.90    997.718986        219.83
France               14.508525           16.08    990.668525         90.64
Germany              14.545000           16.14    984.862632        161.47
India                14.469487           15.95   1000.260085        148.35
Pakistan             14.446053           15.69    996.769298        321.06
UK                   14.548189           15.83    954.305118        163.24
USA                  14.452712           15.58   1021.074407        190.20

Challenge 3

For each country, calculate:

- the minimum temperature
- the maximum temperature
- the range of temperature (max - min)
- the mean rainfall
- the maximum rainfall

You can choose the names of the output columns.

In [123]:
temp_summary = climate_df.groupby("country").agg(
    max_temp = ("max_temperature", "max"),
    min_temp = ("min_temperature", "min"),
    min_rain = ("annual_rainfall_mm", "min"),
    max_rain = ("annual_rainfall_mm", "max")
)
temp_summary

           max_temp  min_temp  min_rain  max_rain
country
Australia     50.07     -4.89     65.00   1796.12
Brazil        47.51     -9.16    350.86   1804.15
Canada        48.19     -2.59     35.18   2019.44
China         46.39     -9.33    219.83   1895.90
France        45.74     -4.62     90.64   1781.25
Germany       47.56     -4.85    161.47   1721.84
India         47.07     -7.28    148.35   1693.38
Pakistan      48.84     -7.48    321.06   1982.92
UK            47.97     -6.33    163.24   1760.00
USA           46.08     -4.62    190.20   1789.18

In [124]:
temp_summary["range_temp"] = temp_summary["max_temp"] - temp_summary["min_temp"]
temp_summary

           max_temp  min_temp  min_rain  max_rain  range_temp
country
Australia     50.07     -4.89     65.00   1796.12       54.96
Brazil        47.51     -9.16    350.86   1804.15       56.67
Canada        48.19     -2.59     35.18   2019.44       50.78
China         46.39     -9.33    219.83   1895.90       55.72
France        45.74     -4.62     90.64   1781.25       50.36
Germany       47.56     -4.85    161.47   1721.84       52.41
India         47.07     -7.28    148.35   1693.38       54.35
Pakistan      48.84     -7.48    321.06   1982.92       56.32
UK            47.97     -6.33    163.24   1760.00       54.30
USA           46.08     -4.62    190.20   1789.18       50.70

Using the same climate_df, calculate the range of annual rainfall for each country — meaning:

highest annual rainfall − lowest annual rainfall

In [125]:
climate_df.groupby("country").agg(
    range_rain = ("annual_rainfall_mm", lambda x : x.max()- x.min()))

           range_rain
country
Australia     1731.12
Brazil        1453.29
Canada        1984.26
China         1676.07
France        1690.61
Germany       1560.37
India         1545.03
Pakistan      1661.86
UK            1596.76
USA           1598.98

Challenge 4

Using climate_df, for each country, calculate:

- average global temperature
- temperature range: highest max_temperature − lowest min_temperature
- rainfall range: highest rainfall − lowest rainfall

In [126]:
climate_summary = climate_df.groupby("country").agg(
    avg_g_temp = ("global_avg_temperature", "mean"),
    highest_max_temp = ("max_temperature", "max"),
    lowest_min_temp = ("min_temperature", "min"),
    highest_rainfall = ("annual_rainfall_mm", "max"),
    lowest_rainfall = ("annual_rainfall_mm", "min")
)

climate_summary
climate_summary["temperature_range"] = climate_summary["highest_max_temp"] - climate_summary["lowest_min_temp"]
climate_summary["rainfall_range"] = climate_summary["highest_rainfall"] - climate_summary["lowest_rainfall"]
climate_summary

,avg_g_temp,highest_max_temp,lowest_min_temp,highest_rainfall,lowest_rainfall,temperature_range,rainfall_range
country,,,,,,,
Australia,14.423590,50.07,-4.89,1796.12,65.00,54.96,1731.12
Brazil,14.501368,47.51,-9.16,1804.15,350.86,56.67,1453.29
Canada,14.476897,48.19,-2.59,2019.44,35.18,50.78,1984.26
China,14.542681,46.39,-9.33,1895.90,219.83,55.72,1676.07
France,14.508525,45.74,-4.62,1781.25,90.64,50.36,1690.61
Germany,14.545000,47.56,-4.85,1721.84,161.47,52.41,1560.37
India,14.469487,47.07,-7.28,1693.38,148.35,54.35,1545.03
Pakistan,14.446053,48.84,-7.48,1982.92,321.06,56.32,1661.86
UK,14.548189,47.97,-6.33,1760.00,163.24,54.30,1596.76
USA,14.452712,46.08,-4.62,1789.18,190.20,50.70,1598.98

Challenge 5

For each country, produce:

- the average global_avg_temperature
- the median global_avg_temperature
- the standard deviation of global_avg_temperature
- the average annual_rainfall_mm
- the maximum annual_rainfall_mm

In [127]:
climate_df.groupby("country").agg(
    average_global_avg_temp = ("global_avg_temperature", "mean"),
    median_global_avg_temp = ("global_avg_temperature", "median"),
    std_global_avg_temp = ("global_avg_temperature", "std"),
    average_annual_rainfall = ("annual_rainfall_mm", "mean"),
    max_annual_rainfall = ("annual_rainfall_mm", "max") 
)

,average_global_avg_temp,median_global_avg_temp,std_global_avg_temp,average_annual_rainfall,max_annual_rainfall
country,,,,,
Australia,14.423590,14.400,0.662705,1027.148718,1796.12
Brazil,14.501368,14.470,0.614160,946.186752,1804.15
Canada,14.476897,14.455,0.656200,1014.297931,2019.44
China,14.542681,14.575,0.599782,997.718986,1895.90
France,14.508525,14.495,0.535589,990.668525,1781.25
Germany,14.545000,14.555,0.525762,984.862632,1721.84
India,14.469487,14.500,0.594049,1000.260085,1693.38
Pakistan,14.446053,14.435,0.588946,996.769298,1982.92
UK,14.548189,14.610,0.590286,954.305118,1760.00
USA,14.452712,14.480,0.571641,1021.074407,1789.18

Challenge 6.

For each country, calculate all three of the following for annual_rainfall_mm:

- mean
- median
- standard deviation

This time, don't rename the output columns.

In [128]:
climate_df.groupby("country")["annual_rainfall_mm"].agg(["mean","median", "std"])

                  mean    median         std
country
Australia  1027.148718  1030.470  302.943076
Brazil      946.186752   944.530  268.845796
Canada     1014.297931  1016.405  361.755195
China       997.718986   992.370  312.584323
France      990.668525   979.305  304.727988
Germany     984.862632   960.375  272.732239
India      1000.260085  1030.140  344.577095
Pakistan    996.769298  1000.425  312.465287
UK          954.305118   956.550  314.532477
USA        1021.074407  1064.125  293.088652

Challenge 7 — different columns, different functions

For each country, calculate:

- global_avg_temperature → mean and median
- annual_rainfall_mm → mean and maximum
- max_temperature → maximum

This time, don't rename the output columns manually.

In [129]:
climate_df.groupby("country").agg({
    "global_avg_temperature": ["mean", "median"],
    "annual_rainfall_mm": ["mean", "max"],
    "max_temperature": ["max"]
})

          global_avg_temperature         annual_rainfall_mm           \
                            mean  median               mean      max
country
Australia              14.423590  14.400        1027.148718  1796.12
Brazil                 14.501368  14.470         946.186752  1804.15
Canada                 14.476897  14.455        1014.297931  2019.44
China                  14.542681  14.575         997.718986  1895.90
France                 14.508525  14.495         990.668525  1781.25
Germany                14.545000  14.555         984.862632  1721.84
India                  14.469487  14.500        1000.260085  1693.38
Pakistan               14.446053  14.435         996.769298  1982.92
UK                     14.548189  14.610         954.305118  1760.00
USA                    14.452712  14.480        1021.074407  1789.18

          max_temperature
                      max
country
Australia           50.07
Brazil              47.51
Canada              48.19
China               46.39
France              45.74
Germany             47.56
India               47.07
Pakistan            48.84
UK                  47.97
USA                 46.08