In [1]:
import pandas as pd

climate_df = pd.read_csv("../data/raw/climate_change_dataset.csv")

# Lesson 7: Data Cleaning
## Missing Values

In [2]:
# Detecting missing values
climate_df.isna()

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1196,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1197,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1198,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1199,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [3]:
climate_df.isna().sum()

year                          0
country                       0
global_avg_temperature        0
temperature_anomaly           0
max_temperature               0
min_temperature               0
co2_concentration_ppm         0
annual_rainfall_mm            0
sea_level_rise_mm             0
sea_surface_temperature       0
heatwave_days                 0
drought_index                 0
flood_events_count            0
forest_cover_percent          0
deforestation_rate            0
fossil_fuel_consumption       0
renewable_energy_share        0
air_quality_index             0
predicted_temperature_2050    0
climate_risk_index            0
dtype: int64

In [4]:
temp_avg_year_country = climate_df.pivot_table(
    index = "country",
    values= "global_avg_temperature",
    columns= "year",
    aggfunc= "mean"
)

temp_avg_year_country

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [5]:
# .sum(); Count the number of missing values in each column.
temp_avg_year_country.isna().sum()

year
1980    0
1981    1
1982    1
1983    0
1984    1
1985    0
1986    2
1987    0
1988    1
1989    0
1990    0
1991    1
1992    1
1993    1
1994    0
1995    2
1996    0
1997    1
1998    0
1999    0
2000    1
2001    2
2002    0
2003    2
2004    2
2005    0
2006    0
2007    0
2008    1
2009    0
2010    1
2011    1
2012    0
2013    1
2014    0
2015    1
2016    0
2017    1
2018    1
2019    0
2020    1
2021    1
2022    0
2023    1
2024    0
2025    1
dtype: int64

In [6]:
# .sum(axis =1 ); Count the number of missing values in each row.
temp_avg_year_country.isna().sum(axis=1)

country
Australia    3
Brazil       5
Canada       2
China        5
France       0
Germany      3
India        3
Pakistan     4
UK           2
USA          3
dtype: int64

In [7]:
# Does this row contain at least one missing value?
temp_avg_year_country.isna().any(axis=1)

country
Australia     True
Brazil        True
Canada        True
China         True
France       False
Germany       True
India         True
Pakistan      True
UK            True
USA           True
dtype: bool

In [8]:
climate_df[climate_df["country"] == "Brazil"].sort_values("year").head(20)

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
380,1980,Brazil,15.39,0.53,26.77,7.64,386.47,1321.91,3.28,17.19,18,0.33,2,26.39,1.53,44.06,17.84,190,2.88,33.22
745,1980,Brazil,14.28,0.65,30.78,4.78,443.76,1061.01,2.35,16.93,50,0.62,9,23.97,0.21,69.07,57.63,139,1.73,80.63
201,1981,Brazil,13.88,1.52,31.63,9.92,411.55,598.96,3.66,18.35,21,3.71,5,53.38,1.45,88.01,31.48,124,2.85,30.82
259,1981,Brazil,14.47,0.54,28.38,9.68,433.84,546.68,4.88,15.68,20,2.86,4,31.23,1.77,41.29,12.27,160,2.61,4.97
1080,1981,Brazil,13.21,0.69,31.53,4.46,436.82,1205.45,1.92,13.99,32,0.73,9,46.91,1.62,66.81,54.90,184,2.79,24.37
289,1981,Brazil,15.25,1.15,39.06,10.57,397.60,905.10,1.24,16.14,24,4.36,5,15.69,2.62,65.24,17.61,89,2.33,8.80
302,1982,Brazil,14.19,1.23,29.58,8.90,410.07,1304.28,4.09,14.37,29,3.36,5,30.53,1.31,56.86,11.22,99,3.05,25.88
197,1982,Brazil,14.47,0.51,31.95,4.38,405.90,1242.33,3.69,15.49,44,0.76,5,38.52,2.54,50.26,59.35,196,1.91,28.90
812,1983,Brazil,13.69,1.61,38.20,11.23,407.91,1329.84,3.21,15.59,20,1.94,13,45.09,1.58,52.01,23.27,197,1.70,4.49
1077,1983,Brazil,13.83,1.42,32.89,2.37,413.34,1013.94,1.83,15.71,29,3.52,6,60.59,1.24,72.50,33.53,170,2.85,51.88
162,1985,Brazil,14.18,1.65,33.75,-2.72,415.73,1375.09,4.00,15.59,59,4.45,11,33.67,2.06,56.08,23.13,154,2.45,40.96
929,1985,Brazil,15.33,0.51,45.14,12.17,446.18,922.07,2.19,15.82,39,2.13,1,69.16,1.20,86.01,47.75,67,2.23,66.22
313,1987,Brazil,15.00,0.60,31.82,5.37,416.70,1040.14,4.12,17.01,19,0.73,11,40.44,1.10,82.82,30.52,71,2.87,31.22
276,1987,Brazil,14.40,1.20,33.97,7.44,371.39,600.76,3.66,16.69,54,4.76,6,31.83,0.38,82.66,57.14,124,3.32,31.12
403,1987,Brazil,14.38,1.03,46.40,-1.30,430.02,1289.25,3.79,14.09,58,1.83,13,14.80,2.65,85.46,53.40,167,1.53,86.28
300,1987,Brazil,14.26,0.63,32.06,-1.00,437.39,660.58,-0.27,17.54,37,2.51,5,42.21,1.24,74.21,15.86,78,2.37,7.87
1074,1987,Brazil,14.08,1.13,32.88,5.90,435.84,766.55,4.86,16.87,0,1.74,14,68.14,0.40,38.80,53.71,52,2.44,28.13
897,1987,Brazil,15.10,1.54,29.11,12.09,428.37,764.92,1.77,16.43,17,0.93,3,36.95,2.09,72.29,49.65,141,2.47,51.10
559,1988,Brazil,14.62,1.57,31.92,5.92,455.01,1013.44,1.67,16.20,23,4.85,12,65.47,1.70,55.21,15.16,123,2.59,61.18
876,1989,Brazil,14.22,0.74,37.17,7.85,439.60,817.60,3.94,16.32,20,2.99,8,26.06,2.99,51.73,8.64,158,1.94,17.79

In [9]:
temp_avg_year_country

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [10]:
temp_avg_year_country.isna().sum()

year
1980    0
1981    1
1982    1
1983    0
1984    1
1985    0
1986    2
1987    0
1988    1
1989    0
1990    0
1991    1
1992    1
1993    1
1994    0
1995    2
1996    0
1997    1
1998    0
1999    0
2000    1
2001    2
2002    0
2003    2
2004    2
2005    0
2006    0
2007    0
2008    1
2009    0
2010    1
2011    1
2012    0
2013    1
2014    0
2015    1
2016    0
2017    1
2018    1
2019    0
2020    1
2021    1
2022    0
2023    1
2024    0
2025    1
dtype: int64

In [11]:
temp_avg_year_country.isna().sum(axis=1)

country
Australia    3
Brazil       5
Canada       2
China        5
France       0
Germany      3
India        3
Pakistan     4
UK           2
USA          3
dtype: int64

In [12]:
# Check if a dataset has any missing values(Not how many) per column

temp_avg_year_country.isna().any()

year
1980    False
1981     True
1982     True
1983    False
1984     True
1985    False
1986     True
1987    False
1988     True
1989    False
1990    False
1991     True
1992     True
1993     True
1994    False
1995     True
1996    False
1997     True
1998    False
1999    False
2000     True
2001     True
2002    False
2003     True
2004     True
2005    False
2006    False
2007    False
2008     True
2009    False
2010     True
2011     True
2012    False
2013     True
2014    False
2015     True
2016    False
2017     True
2018     True
2019    False
2020     True
2021     True
2022    False
2023     True
2024    False
2025     True
dtype: bool

In [13]:
# Check if a dataset has any missing values(Not how many) per row

temp_avg_year_country.isna().any(axis = 1)

country
Australia     True
Brazil        True
Canada        True
China         True
France       False
Germany       True
India         True
Pakistan      True
UK            True
USA           True
dtype: bool

In [14]:
# Check if the dataset has any missing values in general
temp_avg_year_country.isna().any().any()

np.True_

| Code                    | Purpose                                              |
| ----------------------- | ---------------------------------------------------- |
| `df.isna()`             | Show every missing value as True/False               |
| `df.isna().sum()`       | Count missing values in each column                  |
| `df.isna().sum(axis=1)` | Count missing values in each row                     |
| `df.isna().any()`       | Check which columns contain missing values           |
| `df.isna().any().any()` | Check if the entire DataFrame has any missing values |

### dropna()

In [15]:
# Total number of rows and columns before dropna()
temp_avg_year_country.shape

(10, 46)

In [16]:
# Total number of rows and columns after dropna()
temp_avg_year_country.dropna().shape

(1, 46)

In [17]:
temp_avg_year_country.dropna(axis=1).shape

(10, 21)

#### When to use dropna()

Usually when:

- the dataset is huge,
- only a few rows have missing values,
- and removing those rows won't hurt the analysis.

Otherwise, we look for smarter approaches, like:

- filling missing values,
- removing only specific columns,
- or removing rows only when certain columns are missing.

In [18]:
temp_avg_year_country.dropna(how="any").shape

(1, 46)

In [19]:
temp_avg_year_country.dropna(how="all").shape

(10, 46)

In [20]:
temp_avg_year_country

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [ ]:
# Removing nulls in a specific column using subset (Removes the whole row)

temp_avg_year_country.dropna(subset=[1984])

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410,13.280000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410,14.290000

#### DropNA Challenge 1

A climate researcher says:

> "I'm studying long-term climate trends, so I only want countries that have a complete temperature record for every year in the dataset."

Using `temp_avg_year_country`, produce a DataFrame that satisfies this request.

In [22]:
temp_avg_year_country.dropna(how="any")

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
France,14.58,14.506667,14.64,14.05,14.325714,14.32,14.365,14.855,14.755,14.52,...,14.916667,14.845,14.67,14.68,14.216667,14.6,13.81,15.58,15.32,15.35

#### Data Analysis Question

A researcher now changes the requirement.

> "I don't mind if a country is missing a few years of data. I only want to remove countries that have **no temperature records whatsoever**."

Using `temp_avg_year_country`, produce the required DataFrame.

In [23]:
temp_avg_year_country.dropna(axis= 0, how="all")

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

#### Data Analysis Question

A climate researcher says:

> "For my study, I only care about the years **2000**, **2001**, and **2002**.

> Remove countries that are missing temperature data in **any** of those three years, but ignore missing values in every other year."

Produce the required DataFrame.

In [24]:
temp_avg_year_country.dropna(subset=[2000,2001,2002])

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360,14.900000,14.740000,14.360000,14.5275,14.410000,13.28
Brazil,14.83500,14.202500,14.330000,13.760,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730,15.130000,NaN,14.200000,14.7300,14.273333,14.00
Canada,14.82000,14.595000,14.020000,14.495,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295,15.690000,14.140000,13.606667,14.0700,14.610000,14.02
China,14.73250,14.883333,14.037500,15.100,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680,14.216667,14.600000,13.810000,15.5800,15.320000,15.35
Germany,14.04500,14.490000,NaN,14.495,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550,14.545000,14.756667,13.610000,13.8100,14.685000,14.65
USA,14.42625,14.746667,14.236667,13.550,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620,14.586667,14.807500,15.290000,13.9525,14.410000,14.29

#### fillna()

A climate researcher says:

"I don't want to remove any countries from my pivot table.

Instead, replace every missing temperature value with 0 while keeping all countries and all years."

Use temp_avg_year_country to produce the required DataFrame.

In [25]:
temp_avg_year_country.fillna(0)

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,0.000000,14.755000,0.000000,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,0.000000,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,0.000000,15.323333,0.000000,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,0.000000
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,0.000000,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,0.000000,14.970000,15.090000,0.0000,14.740000,14.235000
Pakistan,14.18000,0.000000,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,0.000000,0.000000,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

A researcher says:

"I don't want to replace missing temperatures with zero because that would be misleading.

Instead, replace every missing value with the average temperature of the entire pivot table column (each year's average temperature)."

In [26]:
temp_avg_year_country.fillna(temp_avg_year_country.mean())

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.527500,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,14.596079,14.755000,14.505417,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,14.590463,14.200000,14.730000,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.070000,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,14.505417,15.323333,14.497593,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.364000,14.202000,14.369074
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.580000,15.320000,15.350000
Germany,14.04500,14.490000,14.392407,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.810000,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,14.858704,14.970000,15.090000,14.465444,14.740000,14.235000
Pakistan,14.18000,14.634185,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.930000,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.225000,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,14.529333,14.385185,14.620000,14.586667,14.807500,15.290000,13.952500,14.410000,14.290000


A researcher believes the temperature data contains a few unusually hot years that could affect the average.

Instead of filling missing values with the **mean**, replace every missing value in `temp_avg_year_country` with the **median temperature of its respective year**.

In [27]:
temp_avg_year_country.fillna(temp_avg_year_country.median())

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,14.655000,14.755000,14.535000,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,14.610000,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,14.535000,15.323333,14.585000,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,14.290000
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,14.330000,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,14.900000,14.970000,15.090000,14.3640,14.740000,14.235000
Pakistan,14.18000,14.557500,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,14.483333,14.550000,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

Challenge 1: The Cold Drop 

You're inspecting temp_avg_year_country. You notice that some countries have missing average temperatures for certain years. Your lead data scientist asks you to completely remove any country (row) that has at least one missing value across any of the years, and save this clean view as a new variable called complete_countries_df.

Write the code to accomplish this.

In [28]:
complete_countries_df= temp_avg_year_country.dropna()
complete_countries_df

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
France,14.58,14.506667,14.64,14.05,14.325714,14.32,14.365,14.855,14.755,14.52,...,14.916667,14.845,14.67,14.68,14.216667,14.6,13.81,15.58,15.32,15.35

Challenge 2: The Timeline Gap 

Now, instead of dropping entire countries, your team wants to keep all countries, but deal with missing values year-by-year.

A senior analyst asks: "If a country is missing its average temperature for a specific year, drop any year (column) from the pivot table that contains any missing data across all countries." Save this as complete_years_df.

In [44]:
complete_years_df = temp_avg_year_country.dropna(axis = 1)
complete_years_df

year,1980,1983,1985,1987,1989,1990,1994,1996,1998,1999,...,2005,2006,2007,2009,2012,2014,2016,2019,2022,2024
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,12.780000,14.155000,14.336000,14.820000,14.280000,16.1000,15.3600,14.3475,14.360000,...,13.705000,13.680000,14.358000,14.300000,14.823333,15.016667,14.185000,14.360000,14.360000,14.410000
Brazil,14.83500,13.760000,14.755000,14.536667,13.695000,13.790000,14.0500,15.4600,14.2500,13.880000,...,14.385000,14.776667,14.573333,14.950000,14.476000,14.520000,14.317500,14.730000,14.200000,14.273333
Canada,14.82000,14.495000,14.500000,14.283333,14.480000,14.750000,14.6400,14.7600,14.7600,14.263333,...,14.185000,14.575000,13.920000,13.865000,14.680000,14.196667,13.590000,14.295000,13.606667,14.610000
China,14.73250,15.100000,14.613333,15.323333,14.633333,14.050000,14.5940,14.2025,14.6400,14.283333,...,14.090000,14.395000,14.476667,14.885000,14.718889,15.150000,14.348571,14.938000,14.530000,14.202000
France,14.58000,14.050000,14.320000,14.855000,14.520000,15.140000,13.9050,15.2600,15.0125,14.085000,...,14.750000,14.360000,14.800000,14.406667,14.283333,14.170000,14.916667,14.680000,13.810000,15.320000
Germany,14.04500,14.495000,14.493333,14.356667,14.430000,14.335000,15.1650,14.1250,14.6900,13.810000,...,14.882000,14.850000,14.953333,14.528571,15.150000,14.110000,14.845000,14.550000,13.610000,14.685000
India,14.18250,14.252500,14.772500,14.700000,14.900000,13.835000,14.5125,14.7800,14.8750,14.950000,...,14.543333,14.626667,13.600000,15.226667,13.846667,14.246667,14.083333,15.086667,15.090000,14.740000
Pakistan,14.18000,14.093333,14.456667,14.130000,13.653333,14.490000,14.3900,14.8100,15.0700,14.265000,...,14.341000,14.890000,14.926667,14.477500,14.130000,15.690000,14.630000,13.963333,14.165000,14.170000
UK,14.43500,14.715000,14.776667,13.520000,14.660000,14.210000,14.9900,14.4300,14.5200,14.257500,...,14.860000,14.360000,14.320000,13.860000,14.694000,14.335000,15.060000,13.873333,14.090000,14.730000
USA,14.42625,13.550000,14.130000,14.535000,14.460000,14.338333,14.4450,14.5075,14.6750,14.075000,...,14.896667,14.483333,14.535000,13.670000,14.598000,14.630000,13.706667,14.620000,15.290000,14.410000

Challenge 3: The Reasonable Estimate 

Now, let's swap from dropping data to filling missing data!

Your lead analyst comes to you with a compromise:

"We don't want to lose whole rows or columns. Instead, if a country is missing its average temperature for any given year, let's fill in that missing cell using the overall average temperature of the entire dataset."

Save this filled table as filled_temp_df.

In [30]:
overall_mean = temp_avg_year_country.mean().mean()
overall_mean

filled_temp_df = temp_avg_year_country.fillna(overall_mean)
filled_temp_df

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.52750,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,14.499790,14.755000,14.499790,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,14.499790,14.200000,14.73000,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.07000,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,14.499790,15.323333,14.499790,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.36400,14.202000,14.499790
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.58000,15.320000,15.350000
Germany,14.04500,14.490000,14.499790,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.81000,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,14.499790,14.970000,15.090000,14.49979,14.740000,14.235000
Pakistan,14.18000,14.499790,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.93000,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.22500,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,14.499790,14.499790,14.620000,14.586667,14.807500,15.290000,13.95250,14.410000,14.290000

Challenge 4: Forward Fill Across Time 

If a country is missing a value in a specific year, fill it using the value from the most recent previous year (propagating values forward left-to-right across the year columns).

Save this as ffill_temp_df.

(Hint: Try using .ffill() or .fillna(method='ffill'), but remember to specify the right axis so it moves across columns/years instead of down rows!)

Write the code to accomplish this.

In [31]:
temp_avg_year_country

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,NaN,14.755000,NaN,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,NaN,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,NaN,15.323333,NaN,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,NaN
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,NaN,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,NaN,14.970000,15.090000,NaN,14.740000,14.235000
Pakistan,14.18000,NaN,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,NaN,NaN,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

In [32]:
ffill_temp_df = temp_avg_year_country.ffill(axis=1)
ffill_temp_df

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,13.760000,14.755000,14.755000,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,15.130000,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,14.613333,15.323333,15.323333,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,14.202000
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,14.490000,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,15.086667,14.970000,15.090000,15.0900,14.740000,14.235000
Pakistan,14.18000,14.180000,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,13.706667,13.706667,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

 Challenges 5

 Modify your code so that it first tries to forward fill across years (axis=1), and then immediately uses backward fill (.bfill()) across years (axis=1) to catch any remaining leading missing values. Save the result as fully_filled_df.

In [33]:
fully_filled_df = temp_avg_year_country.ffill(axis=1).bfill(axis = 1)
fully_filled_df

year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
country,,,,,,,,,,,,,,,,,,,,,
Australia,14.71000,14.306000,14.237500,12.780000,15.230000,14.155000,14.105000,14.336000,14.400000,14.820000,...,14.185000,15.170000,14.510000,14.360000,14.900000,14.740000,14.360000,14.5275,14.410000,13.280000
Brazil,14.83500,14.202500,14.330000,13.760000,13.760000,14.755000,14.755000,14.536667,14.620000,13.695000,...,14.317500,14.694000,15.025000,14.730000,15.130000,15.130000,14.200000,14.7300,14.273333,14.000000
Canada,14.82000,14.595000,14.020000,14.495000,15.190000,14.500000,14.360000,14.283333,14.806667,14.480000,...,13.590000,14.226667,14.653333,14.295000,15.690000,14.140000,13.606667,14.0700,14.610000,14.020000
China,14.73250,14.883333,14.037500,15.100000,14.560000,14.613333,14.613333,15.323333,15.323333,14.633333,...,14.348571,14.350000,14.550000,14.938000,14.240000,14.320000,14.530000,14.3640,14.202000,14.202000
France,14.58000,14.506667,14.640000,14.050000,14.325714,14.320000,14.365000,14.855000,14.755000,14.520000,...,14.916667,14.845000,14.670000,14.680000,14.216667,14.600000,13.810000,15.5800,15.320000,15.350000
Germany,14.04500,14.490000,14.490000,14.495000,14.710000,14.493333,14.650000,14.356667,14.585000,14.430000,...,14.845000,14.345000,13.983333,14.550000,14.545000,14.756667,13.610000,13.8100,14.685000,14.650000
India,14.18250,14.557500,14.650000,14.252500,13.830000,14.772500,14.705000,14.700000,14.605000,14.900000,...,14.083333,13.730000,14.860000,15.086667,15.086667,14.970000,15.090000,15.0900,14.740000,14.235000
Pakistan,14.18000,14.180000,14.630000,14.093333,14.655000,14.456667,14.420000,14.130000,14.140000,13.653333,...,14.630000,14.920000,13.335000,13.963333,14.950000,14.610000,14.165000,14.9300,14.170000,14.820000
UK,14.43500,15.420000,14.750000,14.715000,14.050000,14.776667,14.755000,13.520000,14.160000,14.660000,...,15.060000,14.483333,13.880000,13.873333,15.470000,14.370000,14.090000,14.2250,14.730000,14.676667
USA,14.42625,14.746667,14.236667,13.550000,14.814000,14.130000,14.683333,14.535000,14.406667,14.460000,...,13.706667,13.706667,13.706667,14.620000,14.586667,14.807500,15.290000,13.9525,14.410000,14.290000

### Boolean Filtering 
Revision and reminder

In [34]:
climate_df[
    climate_df["global_avg_temperature"] > 25
]

Empty DataFrame
Columns: [year, country, global_avg_temperature, temperature_anomaly, max_temperature, min_temperature, co2_concentration_ppm, annual_rainfall_mm, sea_level_rise_mm, sea_surface_temperature, heatwave_days, drought_index, flood_events_count, forest_cover_percent, deforestation_rate, fossil_fuel_consumption, renewable_energy_share, air_quality_index, predicted_temperature_2050, climate_risk_index]
Index: []

In [35]:
climate_df[
    climate_df["country"] == "Brazil"
    ].head(10).sort_values(["country"])

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
19,2023,Brazil,14.37,1.04,33.31,4.75,355.78,1020.78,4.80,17.73,56,4.66,9,34.42,0.55,60.17,54.04,80,1.87,19.24
26,2001,Brazil,14.21,1.54,32.56,-2.30,431.47,740.50,3.16,15.63,58,1.96,3,15.88,1.50,20.30,50.71,167,1.83,38.62
66,2023,Brazil,15.27,1.59,36.49,5.57,435.26,709.94,3.82,16.15,49,4.82,11,53.96,0.45,73.30,46.74,199,2.59,7.98
82,2005,Brazil,14.85,0.56,38.92,-1.93,396.93,1007.97,3.31,15.73,54,4.76,0,36.17,3.00,35.54,34.23,187,0.43,97.22
85,2020,Brazil,15.37,1.16,40.47,3.30,398.00,350.86,3.69,15.49,31,2.05,6,48.38,1.76,53.61,45.48,141,1.57,1.69
87,1994,Brazil,14.05,1.32,32.15,5.16,412.59,1104.57,2.13,17.04,52,4.36,4,68.94,0.77,21.59,6.42,45,2.10,64.41
101,2014,Brazil,15.00,0.59,22.06,5.52,387.82,973.48,3.76,14.95,18,2.76,3,47.85,2.07,80.52,46.20,133,2.25,34.08
106,2018,Brazil,15.07,1.26,29.82,7.82,414.87,944.53,3.95,15.53,0,4.72,12,38.10,3.19,32.22,9.95,78,2.29,68.30
114,2012,Brazil,14.79,1.31,42.59,5.99,418.47,759.44,1.43,16.72,43,4.80,4,50.42,2.87,37.18,38.83,61,2.00,37.60
118,2014,Brazil,15.62,0.71,32.14,7.58,382.93,959.76,3.42,19.16,12,0.67,2,19.02,1.98,27.53,9.38,56,2.34,30.83

Suppose your manager asks:

Show me all records for Brazil after 2010.

In [36]:
climate_df[(climate_df["country"] == "Brazil") & (climate_df["year"]>= 2010)].sort_values(["year"])

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
660,2010,Brazil,13.87,1.14,32.33,2.09,395.92,1543.09,2.99,16.49,37,0.10,7,19.16,0.23,38.29,11.64,72,2.62,9.62
750,2010,Brazil,14.88,2.08,33.03,-4.08,447.30,1011.61,3.88,17.00,45,1.74,2,53.96,0.37,45.72,59.89,179,1.77,68.32
343,2011,Brazil,14.97,1.79,35.56,3.05,406.54,915.51,3.34,15.55,11,4.79,13,63.09,3.31,70.80,53.65,143,2.25,94.98
214,2011,Brazil,13.63,0.74,36.09,2.70,402.74,986.80,3.33,15.92,15,2.98,0,51.52,3.22,23.16,25.24,195,2.34,30.91
645,2011,Brazil,14.21,0.60,37.33,3.82,435.91,857.06,2.08,16.69,56,2.71,7,67.17,1.58,70.04,49.90,131,1.85,93.67
273,2012,Brazil,14.71,1.01,35.33,3.49,445.57,1335.06,4.34,17.58,55,1.78,13,34.76,2.66,51.12,8.40,81,1.74,43.89
114,2012,Brazil,14.79,1.31,42.59,5.99,418.47,759.44,1.43,16.72,43,4.80,4,50.42,2.87,37.18,38.83,61,2.00,37.60
341,2012,Brazil,14.32,0.35,41.31,4.90,427.00,1539.72,2.74,16.45,25,1.28,3,56.14,0.39,66.35,19.39,197,1.84,21.09
462,2012,Brazil,13.40,1.36,38.80,5.34,447.88,1089.17,5.20,15.16,50,1.04,8,23.45,3.39,21.05,21.10,102,1.88,31.97
1048,2012,Brazil,15.16,1.32,22.13,12.06,422.30,1130.85,4.41,19.75,35,2.98,2,32.93,2.18,29.47,6.92,96,2.20,30.18
754,2013,Brazil,14.70,0.77,33.58,-1.63,440.20,800.41,4.43,16.12,45,1.75,9,32.95,1.22,46.05,56.05,184,2.20,96.55
372,2014,Brazil,13.89,1.07,33.47,3.55,407.28,808.96,1.97,19.91,58,0.28,1,19.37,3.23,51.05,51.37,171,2.67,4.25
118,2014,Brazil,15.62,0.71,32.14,7.58,382.93,959.76,3.42,19.16,12,0.67,2,19.02,1.98,27.53,9.38,56,2.34,30.83
101,2014,Brazil,15.00,0.59,22.06,5.52,387.82,973.48,3.76,14.95,18,2.76,3,47.85,2.07,80.52,46.20,133,2.25,34.08
333,2014,Brazil,14.18,0.48,32.43,3.68,431.35,555.57,4.07,14.92,44,1.98,7,22.14,1.77,78.59,21.96,156,2.54,0.17
545,2014,Brazil,14.06,0.76,25.96,0.27,404.43,1234.56,4.78,14.75,8,4.67,7,48.83,1.62,44.99,33.70,83,1.61,54.63
996,2014,Brazil,14.37,1.06,28.06,-2.63,365.47,966.84,4.21,15.09,43,2.99,3,62.82,1.62,55.96,33.09,69,1.92,0.72
978,2016,Brazil,13.45,0.99,34.74,5.66,418.10,751.59,4.70,15.72,36,2.08,9,40.06,1.06,55.12,38.22,87,2.84,17.58
925,2016,Brazil,14.52,2.08,35.64,6.11,392.07,1367.08,4.23,18.54,27,0.33,13,55.42,0.44,36.43,19.71,161,1.83,78.35
909,2016,Brazil,15.06,0.41,44.98,12.96,389.32,1221.46,4.19,17.45,6,4.80,11,43.33,0.97,37.45,13.78,197,1.62,19.51
184,2016,Brazil,14.24,1.32,37.98,6.02,382.73,816.74,2.10,16.29,36,0.34,1,32.16,1.20,36.48,52.38,79,1.96,45.66
773,2017,Brazil,14.72,0.92,37.74,6.46,400.16,991.95,2.81,16.20,13,4.49,13,67.65,2.24,41.78,21.48,78,1.95,93.43
278,2017,Brazil,14.45,0.77,34.10,7.71,387.38,873.52,2.22,16.38,35,3.62,5,20.72,0.56,48.26,10.51,191,2.80,5.83
780,2017,Brazil,14.60,1.08,41.73,11.39,403.01,905.88,2.89,17.12,30,1.63,4,39.21,0.19,83.62,25.26,145,2.26,4.19
1027,2017,Brazil,13.98,1.27,42.02,5.61,414.78,937.22,4.53,15.98,3,3.27,1,24.11,2.22,82.47,19.64,149,2.72,83.16
1148,2017,Brazil,15.72,0.67,42.64,-0.93,430.48,1000.44,3.18,15.50,42,4.50,2,18.77,0.93,89.63,37.71,141,2.05,99.27
1039,2018,Brazil,15.53,1.24,35.28,5.02,422.21,527.95,4.96,15.04,17,4.69,8,15.33,1.15,34.72,15.49,150,2.16,88.46
438,2018,Brazil,14.73,0.62,23.69,3.34,431.47,620.84,1.46,14.92,51,4.06,14,66.88,2.94,62.52,25.13,46,1.39,24.96
752,2018,Brazil,14.34,0.38,32.47,1.39,431.95,1804.15,5.52,15.32,12,2.00,4,23.09,2.49,22.78,56.24,66,2.47,3.97
106,2018,Brazil,15.07,1.26,29.82,7.82,414.87,944.53,3.95,15.53,0,4.72,12,38.10,3.19,32.22,9.95,78,2.29,68.30
634,2018,Brazil,14.70,1.14,38.74,5.30,402.88,921.87,3.87,15.21,58,4.16,9,13.01,0.48,49.90,22.67,166,2.20,25.03
1050,2018,Brazil,15.78,1.02,32.33,11.15,414.73,523.29,2.94,16.40,50,0.17,10,10.78,3.02,75.93,49.62,77,2.40,31.92
1177,2019,Brazil,14.09,0.74,40.70,7.68,438.58,1187.02,3.05,15.96,43,3.02,7,25.17,3.18,87.57,5.56,100,1.66,20.08
1037,2019,Brazil,14.91,0.85,38.08,7.27,412.11,663.32,1.59,16.31,26,4.69,14,17.85,3.25,89.39,7.16,194,2.23,37.25
898,2019,Brazil,14.99,1.16,44.37,5.40,400.08,1039.29,5.90,16.47,55,4.64,3,51.23,2.49,55.49,16.65,187,1.86,60.70
999,2019,Brazil,14.93,0.77,37.07,4.25,400.64,1498.30,3.51,15.61,22,4.37,5,20.96,1.92,76.26,39.45,140,2.33,4.45
85,2020,Brazil,15.37,1.16,40.47,3.30,398.00,350.86,3.69,15.49,31,2.05,6,48.38,1.76,53.61,45.48,141,1.57,1.69
241,2020,Brazil,14.89,1.25,38.55,4.21,411.52,709.28,3.80,15.18,56,2.73,9,36.27,2.54,54.51,37.92,70,3.15,18.33
963,2022,Brazil,14.20,1.18,34.83,12.24,432.54,1123.75,3.88,15.06,8,2.49,8,29.54,0.66,25.93,20.26,145,2.36,97.17
500,2023,Brazil,14.82,0.96,40.23,1.85,432.12,1090.22,4.19,15.73,8,3.76,10,12.10,0.75,53.51,15.76,43,2.12,74.99
66,2023,Brazil,15.27,1.59,36.49,5.57,435.26,709.94,3.82,16.15,49,4.82,11,53.96,0.45,73.30,46.74,199,2.59,7.98
19,2023,Brazil,14.37,1.04,33.31,4.75,355.78,1020.78,4.80,17.73,56,4.66,9,34.42,0.55,60.17,54.04,80,1.87,19.24
899,2023,Brazil,14.46,1.10,39.89,6.88,387.30,743.06,4.91,15.71,20,2.96,12,42.37,1.42,36.67,54.59,144,1.43,27.61
703,2024,Brazil,13.05,0.59,37.08,2.79,428.54,555.47,4.13,16.93,34,3.91,0,62.69,1.36,53.34,24.25,95,1.90,50.51
644,2024,Brazil,14.94,1.57,29.27,-1.73,383.79,727.49,2.29,13.59,46,1.68,5,12.18,2.39,50.07,51.55,114,2.08,26.66
1070,2024,Brazil,14.83,1.24,35.86,3.22,415.05,708.70,4.43,17.10,19,2.85,6,14.71,0.38,49.51,56.26,93,2.15,35.31
453,2025,Brazil,14.05,0.90,25.03,1.56,375.28,1352.26,4.39,16.57,48,1.59,7,47.24,3.09,83.77,24.43,151,2.81,28.69
338,2025,Brazil,13.95,0.90,33.75,9.00,456.56,1226.11,2.82,16.86,11,2.21,10,14.25,3.35,21.81,47.60,183,1.61,96.57

Suppose the manager says:

Show me records from Brazil OR Canada.

In [37]:
brazil_canada_data_df = climate_df[(climate_df["country"]== "Brazil") | (climate_df["country"] == "Canada")]
brazil_canada_data_df

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
8,2002,Canada,14.89,1.85,36.39,4.31,372.50,1244.87,4.16,17.39,29,0.41,13,38.26,2.95,71.61,45.23,113,2.86,72.18
9,1990,Canada,15.23,1.54,39.31,3.69,413.33,682.43,2.94,17.35,2,4.40,5,37.57,1.70,68.29,58.82,177,2.16,23.41
19,2023,Brazil,14.37,1.04,33.31,4.75,355.78,1020.78,4.80,17.73,56,4.66,9,34.42,0.55,60.17,54.04,80,1.87,19.24
26,2001,Brazil,14.21,1.54,32.56,-2.30,431.47,740.50,3.16,15.63,58,1.96,3,15.88,1.50,20.30,50.71,167,1.83,38.62
44,1993,Canada,14.44,0.72,38.31,1.63,405.32,1662.56,4.35,17.44,37,4.83,0,29.47,1.02,31.22,54.11,100,3.20,80.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1156,2022,Canada,13.25,1.09,29.33,3.55,404.69,1074.97,5.87,14.54,50,3.25,5,64.45,0.21,69.69,56.32,60,2.33,75.61
1158,2003,Canada,14.36,0.81,37.62,7.84,396.41,1164.42,3.31,17.55,21,0.66,3,61.41,3.39,42.26,39.59,139,1.92,38.34
1177,2019,Brazil,14.09,0.74,40.70,7.68,438.58,1187.02,3.05,15.96,43,3.02,7,25.17,3.18,87.57,5.56,100,1.66,20.08
1189,2008,Canada,15.41,1.62,38.13,8.90,437.53,906.63,2.66,17.62,25,0.69,9,58.55,2.10,63.03,37.22,83,1.81,38.82
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,54,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97

Suppose the manager says:

Show me every country except Brazil.

In [38]:
climate_df[climate_df["country"] != "Brazil"]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,37,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,44,1.96,3,19.13,2.38,21.56,22.78,112,1.91,25.39
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,54,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,5,3.99,13,19.46,2.76,64.51,12.09,103,1.40,83.67
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,41,0.47,4,33.91,1.78,54.68,46.40,91,2.92,6.43
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,9,0.91,12,66.56,0.48,62.18,7.55,102,1.64,88.74

In [39]:
climate_df[~(climate_df["country"] == "Brazil")]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,37,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,44,1.96,3,19.13,2.38,21.56,22.78,112,1.91,25.39
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,54,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97
1197,1981,UK,15.42,1.26,35.28,7.24,464.19,251.69,2.13,15.99,5,3.99,13,19.46,2.76,64.51,12.09,103,1.40,83.67
1198,2007,UK,14.07,1.32,31.47,-1.42,407.62,1343.91,2.10,15.19,41,0.47,4,33.91,1.78,54.68,46.40,91,2.92,6.43
1199,2009,Germany,14.82,1.05,37.61,1.29,445.16,914.09,2.77,14.54,9,0.91,12,66.56,0.48,62.18,7.55,102,1.64,88.74

isin()

In [40]:
climate_df[climate_df["country"].isin(["Brazil", "Canada"])]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
8,2002,Canada,14.89,1.85,36.39,4.31,372.50,1244.87,4.16,17.39,29,0.41,13,38.26,2.95,71.61,45.23,113,2.86,72.18
9,1990,Canada,15.23,1.54,39.31,3.69,413.33,682.43,2.94,17.35,2,4.40,5,37.57,1.70,68.29,58.82,177,2.16,23.41
19,2023,Brazil,14.37,1.04,33.31,4.75,355.78,1020.78,4.80,17.73,56,4.66,9,34.42,0.55,60.17,54.04,80,1.87,19.24
26,2001,Brazil,14.21,1.54,32.56,-2.30,431.47,740.50,3.16,15.63,58,1.96,3,15.88,1.50,20.30,50.71,167,1.83,38.62
44,1993,Canada,14.44,0.72,38.31,1.63,405.32,1662.56,4.35,17.44,37,4.83,0,29.47,1.02,31.22,54.11,100,3.20,80.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1156,2022,Canada,13.25,1.09,29.33,3.55,404.69,1074.97,5.87,14.54,50,3.25,5,64.45,0.21,69.69,56.32,60,2.33,75.61
1158,2003,Canada,14.36,0.81,37.62,7.84,396.41,1164.42,3.31,17.55,21,0.66,3,61.41,3.39,42.26,39.59,139,1.92,38.34
1177,2019,Brazil,14.09,0.74,40.70,7.68,438.58,1187.02,3.05,15.96,43,3.02,7,25.17,3.18,87.57,5.56,100,1.66,20.08
1189,2008,Canada,15.41,1.62,38.13,8.90,437.53,906.63,2.66,17.62,25,0.69,9,58.55,2.10,63.03,37.22,83,1.81,38.82
1196,1993,Canada,15.14,1.05,26.85,2.98,420.29,777.83,4.97,16.96,54,2.20,4,40.94,1.77,74.75,20.81,96,2.71,4.97

Combining isin() with AND

Suppose the manager says:

Show me Brazil and Canada after 2015.

In [41]:
climate_df[~(climate_df["country"].isin(["Brazil", "Canada"])) & (climate_df["year"] >= 2015)]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
6,2018,France,14.67,1.41,33.10,3.75,426.67,1422.19,1.48,15.78,45,1.05,5,44.54,3.46,65.85,21.51,71,2.67,23.87
12,2015,USA,15.37,0.70,27.99,2.78,396.88,1201.52,2.02,18.83,41,3.90,11,44.90,2.73,27.40,8.42,79,2.56,45.24
13,2019,France,15.58,1.47,41.60,5.09,393.12,485.46,2.85,16.87,2,0.58,13,24.46,3.09,50.52,47.71,81,2.42,15.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1157,2023,China,14.39,1.47,34.24,11.84,399.97,912.74,3.05,15.21,47,4.31,10,15.79,1.47,25.26,31.83,182,1.83,26.65
1165,2022,Australia,14.08,1.22,32.94,11.11,363.42,1490.31,4.23,16.84,25,4.31,13,50.84,1.98,59.29,43.52,57,1.88,11.94
1173,2020,France,14.10,1.19,30.24,6.55,407.83,447.08,3.12,15.96,46,3.76,7,22.89,2.37,35.31,5.12,52,2.86,18.12
1188,2024,Australia,14.66,1.42,50.07,5.35,424.36,877.68,2.57,16.20,43,2.00,13,62.69,1.85,24.91,23.49,102,1.82,88.58
1192,2019,India,14.95,1.01,30.61,11.32,428.29,1405.82,5.38,16.19,34,4.98,14,67.18,1.57,28.24,46.21,69,2.67,25.94

between()

Suppose your manager asks:

Show me all climate records between 2000 and 2010.

In [46]:
climate_df[climate_df["year"].between(2000,2010)].sort_values(["year"])

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
77,2000,France,13.84,1.23,33.90,7.61,409.28,1251.36,3.60,16.37,58,4.63,0,10.40,1.29,44.51,27.85,156,2.67,46.88
1130,2000,UK,15.11,0.87,33.16,-6.33,451.64,533.91,4.28,17.65,52,3.07,2,17.81,2.38,72.90,50.09,91,1.64,76.91
1138,2000,China,14.76,1.10,28.04,10.16,417.19,1091.57,3.66,13.87,23,3.50,1,25.75,0.74,26.97,30.48,76,2.97,7.19
298,2000,Canada,15.22,1.38,31.62,1.71,368.56,1482.36,4.02,14.62,42,3.04,1,49.09,1.99,79.85,57.40,125,1.84,6.24
317,2000,USA,14.59,1.22,31.60,9.53,389.64,801.99,3.20,19.89,38,2.55,6,57.32,0.94,45.50,59.38,194,1.61,26.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,2010,India,14.06,1.07,38.82,7.45,486.53,1030.14,1.95,16.92,50,1.62,0,68.36,3.24,62.95,11.29,182,2.20,11.32
988,2010,Germany,15.40,0.78,42.91,0.90,396.04,981.72,2.90,15.92,0,1.00,12,10.28,0.97,76.05,6.73,123,2.27,41.36
1068,2010,China,14.08,0.71,41.03,7.96,433.86,1341.62,3.55,16.11,14,2.37,9,46.57,3.34,62.31,24.12,156,2.85,62.54
71,2010,Canada,15.37,1.38,33.74,4.78,389.47,1107.96,4.07,15.52,59,2.62,7,28.14,2.85,37.96,37.10,161,2.23,30.51
1082,2010,France,15.13,1.11,29.93,5.13,427.01,1358.89,4.27,14.92,56,2.13,8,19.80,2.73,86.38,29.13,180,2.17,10.63

### Boolean filtering practice questions

#### Question 1

A climate policy team is preparing a report on regions that may have experienced severe heat stress in recent years.

They define "recent years" as **2015 onwards**, and they are only interested in countries whose **global average temperature exceeded 25°C** during those years.

Retrieve all records that satisfy these requirements.

In [47]:
climate_df[(climate_df["global_avg_temperature"] > 25) & (climate_df["year"] >= 2015)]

Empty DataFrame
Columns: [year, country, global_avg_temperature, temperature_anomaly, max_temperature, min_temperature, co2_concentration_ppm, annual_rainfall_mm, sea_level_rise_mm, sea_surface_temperature, heatwave_days, drought_index, flood_events_count, forest_cover_percent, deforestation_rate, fossil_fuel_consumption, renewable_energy_share, air_quality_index, predicted_temperature_2050, climate_risk_index]
Index: []

#### Question 2

An international conservation organization is studying countries that receive **very high rainfall**.

For this phase of the project, they are interested **only** in:

- Brazil
- India
- Indonesia

(The dataset may or may not contain all of these countries.)

Retrieve all rainfall records for the countries that are available in the dataset.

In [48]:
climate_df.head()

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
0,2018,Germany,14.03,1.16,37.02,4.31,387.85,814.11,2.14,14.38,50,0.85,11,64.33,1.26,28.14,42.30,148,3.30,23.69
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,37,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10
2,1994,Pakistan,14.86,1.24,41.57,1.08,450.54,1982.92,6.46,15.90,27,4.59,1,65.47,2.08,34.95,47.20,107,1.33,34.74
3,2022,USA,15.29,1.19,32.17,1.68,415.42,1162.01,3.37,17.26,25,4.29,6,44.34,2.15,77.11,36.65,129,2.51,45.59
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77

In [54]:
climate_df[
    climate_df["country"].isin(["Brazil", "India", "Indonesia"])
]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
1,2008,India,15.03,1.05,32.25,-0.44,407.24,735.61,4.19,15.33,37,1.01,11,42.69,0.62,86.40,53.65,50,2.63,70.10
7,1998,India,13.94,1.22,33.35,9.91,434.75,1122.34,4.60,14.54,48,3.13,10,22.86,0.93,31.12,11.51,110,2.10,83.59
10,1990,India,14.15,1.06,28.75,5.23,419.83,1295.18,5.55,15.57,27,0.26,13,47.37,1.58,58.02,11.42,138,2.37,97.50
19,2023,Brazil,14.37,1.04,33.31,4.75,355.78,1020.78,4.80,17.73,56,4.66,9,34.42,0.55,60.17,54.04,80,1.87,19.24
21,2017,India,13.73,1.11,29.88,5.76,387.03,1430.32,1.97,16.62,0,0.24,9,41.33,1.85,61.64,35.77,171,2.53,32.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1180,2011,India,14.39,1.47,30.37,-2.18,395.36,1102.40,2.99,12.71,36,0.21,0,67.29,2.73,53.07,47.71,199,2.78,38.07
1182,2009,India,15.56,1.30,35.72,2.96,429.06,904.80,0.52,16.24,15,1.39,12,51.94,0.96,21.10,24.86,95,1.82,97.48
1192,2019,India,14.95,1.01,30.61,11.32,428.29,1405.82,5.38,16.19,34,4.98,14,67.18,1.57,28.24,46.21,69,2.67,25.94
1194,1997,India,13.81,0.90,36.56,13.64,420.34,1336.85,2.10,15.38,19,4.68,5,37.87,2.89,80.50,20.44,102,1.66,30.41
1195,1980,India,14.53,1.06,43.91,-2.45,409.92,1483.91,4.72,17.81,44,1.96,3,19.13,2.38,21.56,22.78,112,1.91,25.39

In [55]:
climate_df.loc[
    climate_df["country"].isin(["Brazil", "India", "Indonesia"]),
    ["country", "year", "annual_rainfall_mm"]
]

     country  year  annual_rainfall_mm
1      India  2008              735.61
7      India  1998             1122.34
10     India  1990             1295.18
19    Brazil  2023             1020.78
21     India  2017             1430.32
...      ...   ...                 ...
1180   India  2011             1102.40
1182   India  2009              904.80
1192   India  2019             1405.82
1194   India  1997             1336.85
1195   India  1980             1483.91

[234 rows x 3 columns]

In [57]:
# Recap on .loc

climate_df.loc[[2,5,6], ["country", "year", "annual_rainfall_mm"]]

    country  year  annual_rainfall_mm
2  Pakistan  1994             1982.92
5    France  2000             1178.57
6    France  2018             1422.19

In [63]:
climate_df.loc[[4,8]]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77
8,2002,Canada,14.89,1.85,36.39,4.31,372.50,1244.87,4.16,17.39,29,0.41,13,38.26,2.95,71.61,45.23,113,2.86,72.18

In [67]:
# recap on .iloc

climate_df.iloc[[4,8]]

,year,country,global_avg_temperature,temperature_anomaly,max_temperature,min_temperature,co2_concentration_ppm,annual_rainfall_mm,sea_level_rise_mm,sea_surface_temperature,heatwave_days,drought_index,flood_events_count,forest_cover_percent,deforestation_rate,fossil_fuel_consumption,renewable_energy_share,air_quality_index,predicted_temperature_2050,climate_risk_index
4,1987,Australia,13.75,1.32,40.99,10.38,403.42,1170.25,4.64,16.62,41,1.00,4,14.18,0.76,37.27,50.35,149,2.87,55.77
8,2002,Canada,14.89,1.85,36.39,4.31,372.50,1244.87,4.16,17.39,29,0.41,13,38.26,2.95,71.61,45.23,113,2.86,72.18

In [69]:
climate_df.iloc[[2,4,6], [3,6]]

   temperature_anomaly  co2_concentration_ppm
2                 1.24                 450.54
4                 1.32                 403.42
6                 1.41                 426.67

In [68]:
climate_df.loc[
    climate_df["country"] == "Brazil",
    ["country", "year"]
]

     country  year
19    Brazil  2023
26    Brazil  2001
66    Brazil  2023
82    Brazil  2005
85    Brazil  2020
...      ...   ...
1141  Brazil  1989
1148  Brazil  2017
1151  Brazil  1997
1152  Brazil  2006
1177  Brazil  2019

[117 rows x 2 columns]